[package]
name = "uniffi-ohos-public-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
futures-util = "0.3"
thiserror = "2"
uniffi = { path = "../../..", default-features = false, features = ["macro-scaffolding", "default-async-runtime-tokio"] }

[workspace]
