/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use crate::{rust_future_new, FutureLowerReturn, Handle, LiftArgsError};
use anyhow::anyhow;
use futures_core::Stream;
use once_cell::sync::Lazy;
use std::{
    collections::HashMap,
    future::Future,
    pin::Pin,
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    task::{Context, Poll},
};

/// Rust stream type supported by the first native stream ABI slice.
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
pub type UniFfiStream<T, E> = Pin<Box<dyn Stream<Item = Result<T, E>> + Send + 'static>>;

/// Single-threaded wasm stream type reserved for the JavaScript wasm backend.
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
pub type UniFfiStream<T, E> = Pin<Box<dyn Stream<Item = Result<T, E>> + 'static>>;

/// Marker trait for values that can be stored in a UniFFI Rust stream registry.
///
/// Native targets keep the same `Send + 'static` guarantee as Rust futures. The
/// wasm single-threaded JavaScript backend can opt into local, non-`Send` stream
/// state because JS drives Rust on one thread.
#[doc(hidden)]
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
pub trait UniffiCompatibleStreamValue: Send + 'static {}

#[doc(hidden)]
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
impl<T> UniffiCompatibleStreamValue for T where T: Send + 'static {}

#[doc(hidden)]
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
pub trait UniffiCompatibleStreamValue: 'static {}

#[doc(hidden)]
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
impl<T> UniffiCompatibleStreamValue for T where T: 'static {}

/// Per-stream-function registry generated by the scaffolding code.
pub type RustStreamRegistry<T, E> = Lazy<Mutex<HashMap<u64, Arc<RustStream<T, E>>>>>;

enum RustStreamState<T, E> {
    Open {
        stream: UniFfiStream<T, E>,
        next_pending: bool,
    },
    Closed,
}

/// Runtime state for one Rust stream handle.
pub struct RustStream<T, E> {
    state: Mutex<RustStreamState<T, E>>,
}

// The wasm JavaScript backend is single-threaded under
// `wasm-unstable-single-threaded`, but `static` registries still require
// `Sync` at compile time. The stream is only ever touched from the one JS
// thread, and access remains guarded by the registry mutex.
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
unsafe impl<T, E> Send for RustStream<T, E> {}

#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
unsafe impl<T, E> Sync for RustStream<T, E> {}

impl<T, E> RustStream<T, E> {
    fn new(stream: UniFfiStream<T, E>) -> Self {
        Self {
            state: Mutex::new(RustStreamState::Open {
                stream,
                next_pending: false,
            }),
        }
    }

    fn begin_next(self: Arc<Self>) -> RustStreamNext<T, E> {
        let start_error = {
            let mut state = self.state.lock().unwrap();
            match &mut *state {
                RustStreamState::Open { next_pending, .. } if *next_pending => {
                    Some("concurrent stream next() is not supported")
                }
                RustStreamState::Open { next_pending, .. } => {
                    *next_pending = true;
                    None
                }
                RustStreamState::Closed => None,
            }
        };

        RustStreamNext {
            stream: Some(self),
            active: start_error.is_none(),
            start_error,
        }
    }

    fn cancel(&self) {
        *self.state.lock().unwrap() = RustStreamState::Closed;
    }

    fn clear_pending(&self) {
        let mut state = self.state.lock().unwrap();
        if let RustStreamState::Open { next_pending, .. } = &mut *state {
            *next_pending = false;
        }
    }
}

pub struct RustStreamNext<T, E> {
    stream: Option<Arc<RustStream<T, E>>>,
    active: bool,
    start_error: Option<&'static str>,
}

impl<T, E> Unpin for RustStreamNext<T, E> {}

impl<T, E> Future for RustStreamNext<T, E> {
    type Output = Result<Result<Option<T>, E>, LiftArgsError>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        if let Some(message) = self.start_error.take() {
            self.active = false;
            self.stream = None;
            return Poll::Ready(Err(LiftArgsError {
                arg_name: "stream",
                error: anyhow!(message),
            }));
        }

        let Some(stream) = self.stream.as_ref().cloned() else {
            return Poll::Ready(Ok(Ok(None)));
        };

        let mut state = stream.state.lock().unwrap();
        match &mut *state {
            RustStreamState::Closed => {
                self.active = false;
                self.stream = None;
                Poll::Ready(Ok(Ok(None)))
            }
            RustStreamState::Open {
                stream: inner,
                next_pending,
            } => match inner.as_mut().poll_next(cx) {
                Poll::Pending => Poll::Pending,
                Poll::Ready(Some(Ok(value))) => {
                    *next_pending = false;
                    self.active = false;
                    self.stream = None;
                    Poll::Ready(Ok(Ok(Some(value))))
                }
                Poll::Ready(Some(Err(error))) => {
                    *state = RustStreamState::Closed;
                    self.active = false;
                    self.stream = None;
                    Poll::Ready(Ok(Err(error)))
                }
                Poll::Ready(None) => {
                    *state = RustStreamState::Closed;
                    self.active = false;
                    self.stream = None;
                    Poll::Ready(Ok(Ok(None)))
                }
            },
        }
    }
}

impl<T, E> Drop for RustStreamNext<T, E> {
    fn drop(&mut self) {
        if self.active {
            if let Some(stream) = &self.stream {
                stream.clear_pending();
            }
        }
    }
}

static NEXT_STREAM_HANDLE: AtomicU64 = AtomicU64::new(2);

fn next_stream_handle() -> Handle {
    Handle::from_raw_unchecked(NEXT_STREAM_HANDLE.fetch_add(2, Ordering::Relaxed))
}

pub fn rust_stream_new<T, E>(
    registry: &'static RustStreamRegistry<T, E>,
    stream: UniFfiStream<T, E>,
) -> Handle
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    let handle = next_stream_handle();
    registry
        .lock()
        .unwrap()
        .insert(handle.as_raw(), Arc::new(RustStream::new(stream)));
    handle
}

pub fn rust_stream_next<T, E, UT>(
    registry: &'static RustStreamRegistry<T, E>,
    handle: Handle,
    tag: UT,
) -> Handle
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
    Result<Option<T>, E>: FutureLowerReturn<UT> + 'static,
{
    let stream = registry.lock().unwrap().get(&handle.as_raw()).cloned();
    let future = RustStreamRegistryNext {
        registry,
        handle: handle.as_raw(),
        inner: stream.map(RustStream::begin_next),
    };
    rust_future_new(future, tag)
}

pub async fn rust_stream_next_async<T, E>(
    registry: &'static RustStreamRegistry<T, E>,
    handle: Handle,
) -> Result<Result<Option<T>, E>, LiftArgsError>
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    let stream = registry.lock().unwrap().get(&handle.as_raw()).cloned();
    RustStreamRegistryNext {
        registry,
        handle: handle.as_raw(),
        inner: stream.map(RustStream::begin_next),
    }
    .await
}

pub fn rust_stream_cancel<T, E>(registry: &'static RustStreamRegistry<T, E>, handle: Handle)
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    if let Some(stream) = registry.lock().unwrap().remove(&handle.as_raw()) {
        stream.cancel();
    }
}

struct RustStreamRegistryNext<T: 'static, E: 'static> {
    registry: &'static RustStreamRegistry<T, E>,
    handle: u64,
    inner: Option<RustStreamNext<T, E>>,
}

impl<T, E> Unpin for RustStreamRegistryNext<T, E> {}

impl<T, E> Future for RustStreamRegistryNext<T, E> {
    type Output = Result<Result<Option<T>, E>, LiftArgsError>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let Some(inner) = &mut self.inner else {
            return Poll::Ready(Ok(Ok(None)));
        };

        match Pin::new(inner).poll(cx) {
            Poll::Pending => Poll::Pending,
            Poll::Ready(output) => {
                if !matches!(output, Ok(Ok(Some(_)))) {
                    self.registry.lock().unwrap().remove(&self.handle);
                }
                self.inner = None;
                Poll::Ready(output)
            }
        }
    }
}
