/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use crate::{rust_future_new, FutureLowerReturn, Handle, LiftArgsError};
use anyhow::anyhow;
use futures_core::Stream;
use once_cell::sync::Lazy;
use std::{
    collections::HashMap,
    future::Future,
    pin::Pin,
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    task::{Context, Poll, Waker},
};

/// Rust stream type supported by the first native stream ABI slice.
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
pub type UniFfiStream<T, E> = Pin<Box<dyn Stream<Item = Result<T, E>> + Send + 'static>>;

/// Single-threaded wasm stream type reserved for the JavaScript wasm backend.
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
pub type UniFfiStream<T, E> = Pin<Box<dyn Stream<Item = Result<T, E>> + 'static>>;

/// Marker trait for values that can be stored in a UniFFI Rust stream registry.
///
/// Native targets keep the same `Send + 'static` guarantee as Rust futures. The
/// wasm single-threaded JavaScript backend can opt into local, non-`Send` stream
/// state because JS drives Rust on one thread.
#[doc(hidden)]
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
pub trait UniffiCompatibleStreamValue: Send + 'static {}

#[doc(hidden)]
#[cfg(not(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded")))]
impl<T> UniffiCompatibleStreamValue for T where T: Send + 'static {}

#[doc(hidden)]
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
pub trait UniffiCompatibleStreamValue: 'static {}

#[doc(hidden)]
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
impl<T> UniffiCompatibleStreamValue for T where T: 'static {}

/// Per-stream-function registry generated by the scaffolding code.
pub type RustStreamRegistry<T, E> = Lazy<Mutex<HashMap<u64, Arc<RustStream<T, E>>>>>;

enum RustStreamState<T, E> {
    Open {
        // The active `RustStreamNext` temporarily owns the stream while it is
        // polling.  This keeps arbitrary `Stream::poll_next`/`Drop` code out
        // of the state mutex and lets cancellation transition the shared
        // state without deadlocking re-entrant user code.
        stream: Option<UniFfiStream<T, E>>,
        next_pending: bool,
        pending_waker: Option<Waker>,
    },
    Closed,
}

/// Runtime state for one Rust stream handle.
pub struct RustStream<T, E> {
    state: Mutex<RustStreamState<T, E>>,
}

// The wasm JavaScript backend is single-threaded under
// `wasm-unstable-single-threaded`, but `static` registries still require
// `Sync` at compile time. The stream is only ever touched from the one JS
// thread, and access remains guarded by the registry mutex.
#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
unsafe impl<T, E> Send for RustStream<T, E> {}

#[cfg(all(target_arch = "wasm32", feature = "wasm-unstable-single-threaded"))]
unsafe impl<T, E> Sync for RustStream<T, E> {}

impl<T, E> RustStream<T, E> {
    fn new(stream: UniFfiStream<T, E>) -> Self {
        Self {
            state: Mutex::new(RustStreamState::Open {
                stream: Some(stream),
                next_pending: false,
                pending_waker: None,
            }),
        }
    }

    fn begin_next(self: Arc<Self>) -> RustStreamNext<T, E> {
        let (inner, start_error, stale_waker) = {
            let mut state = self.state.lock().unwrap();
            match &mut *state {
                RustStreamState::Open { next_pending, .. } if *next_pending => (
                    None,
                    Some("concurrent stream next() is not supported"),
                    None,
                ),
                RustStreamState::Open {
                    stream,
                    next_pending,
                    pending_waker,
                } => {
                    *next_pending = true;
                    let stale_waker = pending_waker.take();
                    // `next_pending == false` guarantees the prior owner put
                    // the stream back before another next operation begins.
                    let inner = stream
                        .take()
                        .expect("open UniFFI stream has no active next owner");
                    (Some(inner), None, stale_waker)
                }
                RustStreamState::Closed => (None, None, None),
            }
        };
        // A stale RawWaker is an invariant cleanup, but its destructor may be
        // user-controlled and must not run under the state mutex.
        drop(stale_waker);

        let active = inner.is_some() && start_error.is_none();
        let owner = active.then_some(self);

        RustStreamNext {
            owner,
            inner,
            active,
            start_error,
        }
    }

    fn cancel(&self) {
        let previous = {
            let mut state = self.state.lock().unwrap();
            std::mem::replace(&mut *state, RustStreamState::Closed)
        };
        let (idle_stream, pending_waker) = match previous {
            RustStreamState::Open {
                stream,
                pending_waker,
                ..
            } => (stream, pending_waker),
            RustStreamState::Closed => (None, None),
        };
        // Both operations may execute arbitrary user code.  The state mutex
        // has been released before either one runs.
        if let Some(waker) = pending_waker {
            waker.wake();
        }
        drop(idle_stream);
    }
}

pub struct RustStreamNext<T, E> {
    owner: Option<Arc<RustStream<T, E>>>,
    inner: Option<UniFfiStream<T, E>>,
    active: bool,
    start_error: Option<&'static str>,
}

impl<T, E> Unpin for RustStreamNext<T, E> {}

impl<T, E> Future for RustStreamNext<T, E> {
    type Output = Result<Result<Option<T>, E>, LiftArgsError>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        if let Some(message) = self.start_error.take() {
            self.active = false;
            self.owner = None;
            let inner = self.inner.take();
            drop(inner);
            return Poll::Ready(Err(LiftArgsError {
                arg_name: "stream",
                error: anyhow!(message),
            }));
        }

        let Some(owner) = self.owner.as_ref().cloned() else {
            return Poll::Ready(Ok(Ok(None)));
        };

        // Publish the current task waker before polling user code.  cancel()
        // uses the same state mutex, so it either observes this waker and
        // wakes it, or this poll observes Closed before invoking the stream.
        // Cloning a custom RawWaker can execute user-controlled code too, so
        // prepare the replacement before taking the stream-state mutex.
        let mut candidate_waker = Some(cx.waker().clone());
        let mut replaced_waker = None;
        let open = {
            let mut state = owner.state.lock().unwrap();
            match &mut *state {
                RustStreamState::Closed => false,
                RustStreamState::Open { pending_waker, .. } => {
                    if pending_waker
                        .as_ref()
                        .is_none_or(|registered| !registered.will_wake(cx.waker()))
                    {
                        replaced_waker = pending_waker.replace(
                            candidate_waker
                                .take()
                                .expect("stream next replacement waker is available"),
                        );
                    }
                    true
                }
            }
        };
        // Dropping either custom RawWaker may execute arbitrary code.
        drop(candidate_waker);
        drop(replaced_waker);
        if !open {
            self.active = false;
            self.owner = None;
            let inner = self.inner.take();
            drop(inner);
            return Poll::Ready(Ok(Ok(None)));
        }

        // The stream is owned by this future, so user poll code runs without
        // either the registry or stream-state mutex held.
        let polled = self
            .inner
            .as_mut()
            .expect("active UniFFI stream next has no stream")
            .as_mut()
            .poll_next(cx);

        match polled {
            Poll::Pending => {
                let closed = matches!(*owner.state.lock().unwrap(), RustStreamState::Closed);
                if closed {
                    self.active = false;
                    self.owner = None;
                    let inner = self.inner.take();
                    drop(inner);
                    Poll::Ready(Ok(Ok(None)))
                } else {
                    Poll::Pending
                }
            }
            Poll::Ready(Some(Ok(value))) => {
                let mut inner = self.inner.take();
                let mut stale_waker = None;
                let closed = {
                    let mut state = owner.state.lock().unwrap();
                    match &mut *state {
                        RustStreamState::Closed => true,
                        RustStreamState::Open {
                            stream,
                            next_pending,
                            pending_waker,
                        } => {
                            *next_pending = false;
                            stale_waker = pending_waker.take();
                            *stream = inner.take();
                            false
                        }
                    }
                };
                drop(stale_waker);
                drop(inner);
                self.active = false;
                self.owner = None;
                if closed {
                    Poll::Ready(Ok(Ok(None)))
                } else {
                    Poll::Ready(Ok(Ok(Some(value))))
                }
            }
            Poll::Ready(Some(Err(error))) => {
                self.finish_terminal(&owner);
                Poll::Ready(Ok(Err(error)))
            }
            Poll::Ready(None) => {
                self.finish_terminal(&owner);
                Poll::Ready(Ok(Ok(None)))
            }
        }
    }
}

impl<T, E> RustStreamNext<T, E> {
    fn finish_terminal(&mut self, owner: &RustStream<T, E>) {
        let previous = {
            let mut state = owner.state.lock().unwrap();
            std::mem::replace(&mut *state, RustStreamState::Closed)
        };
        let (idle_stream, pending_waker) = match previous {
            RustStreamState::Open {
                stream,
                pending_waker,
                ..
            } => (stream, pending_waker),
            RustStreamState::Closed => (None, None),
        };
        self.active = false;
        self.owner = None;
        let inner = self.inner.take();
        // All user-controlled drops happen after the state mutex is released.
        drop(pending_waker);
        drop(idle_stream);
        drop(inner);
    }
}

impl<T, E> Drop for RustStreamNext<T, E> {
    fn drop(&mut self) {
        if !self.active {
            return;
        }
        let Some(owner) = self.owner.take() else {
            return;
        };
        let mut inner = self.inner.take();
        let mut stale_waker = None;
        {
            let mut state = owner.state.lock().unwrap();
            if let RustStreamState::Open {
                stream,
                next_pending,
                pending_waker,
            } = &mut *state
            {
                *next_pending = false;
                stale_waker = pending_waker.take();
                *stream = inner.take();
            }
        }
        self.active = false;
        // A canceled owner leaves `inner` populated; drop it outside the lock.
        drop(stale_waker);
        drop(inner);
    }
}

static NEXT_STREAM_HANDLE: AtomicU64 = AtomicU64::new(2);

fn next_stream_handle() -> Handle {
    Handle::from_raw_unchecked(NEXT_STREAM_HANDLE.fetch_add(2, Ordering::Relaxed))
}

pub fn rust_stream_new<T, E>(
    registry: &'static RustStreamRegistry<T, E>,
    stream: UniFfiStream<T, E>,
) -> Handle
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    let handle = next_stream_handle();
    registry
        .lock()
        .unwrap()
        .insert(handle.as_raw(), Arc::new(RustStream::new(stream)));
    handle
}

pub fn rust_stream_next<T, E, UT>(
    registry: &'static RustStreamRegistry<T, E>,
    handle: Handle,
    tag: UT,
) -> Handle
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
    Result<Option<T>, E>: FutureLowerReturn<UT> + 'static,
{
    let stream = registry.lock().unwrap().get(&handle.as_raw()).cloned();
    let future = RustStreamRegistryNext {
        registry,
        handle: handle.as_raw(),
        inner: stream.map(RustStream::begin_next),
    };
    #[cfg(all(feature = "tokio", not(target_arch = "wasm32")))]
    let future = async_compat::Compat::new(future);
    rust_future_new(future, tag)
}

pub async fn rust_stream_next_async<T, E>(
    registry: &'static RustStreamRegistry<T, E>,
    handle: Handle,
) -> Result<Result<Option<T>, E>, LiftArgsError>
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    let stream = registry.lock().unwrap().get(&handle.as_raw()).cloned();
    RustStreamRegistryNext {
        registry,
        handle: handle.as_raw(),
        inner: stream.map(RustStream::begin_next),
    }
    .await
}

pub fn rust_stream_cancel<T, E>(registry: &'static RustStreamRegistry<T, E>, handle: Handle)
where
    T: UniffiCompatibleStreamValue,
    E: UniffiCompatibleStreamValue,
{
    let stream = { registry.lock().unwrap().remove(&handle.as_raw()) };
    if let Some(stream) = stream {
        stream.cancel();
    }
}

struct RustStreamRegistryNext<T: 'static, E: 'static> {
    registry: &'static RustStreamRegistry<T, E>,
    handle: u64,
    inner: Option<RustStreamNext<T, E>>,
}

impl<T, E> Unpin for RustStreamRegistryNext<T, E> {}

impl<T, E> Future for RustStreamRegistryNext<T, E> {
    type Output = Result<Result<Option<T>, E>, LiftArgsError>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let Some(inner) = &mut self.inner else {
            return Poll::Ready(Ok(Ok(None)));
        };

        match Pin::new(inner).poll(cx) {
            Poll::Pending => Poll::Pending,
            Poll::Ready(output) => {
                if matches!(output, Ok(Ok(None)) | Ok(Err(_))) {
                    let removed = { self.registry.lock().unwrap().remove(&self.handle) };
                    drop(removed);
                }
                self.inner = None;
                Poll::Ready(output)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering as AtomicOrdering};
    use std::sync::{mpsc, Barrier, Weak};
    use std::task::{Wake, Waker};
    use std::time::Duration;

    struct AlwaysPending;

    impl Stream for AlwaysPending {
        type Item = Result<u32, String>;

        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
            Poll::Pending
        }
    }

    struct GatedPending {
        entered: Arc<Barrier>,
        release: Arc<Barrier>,
        first_poll: bool,
    }

    impl Stream for GatedPending {
        type Item = Result<u32, String>;

        fn poll_next(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
            if self.first_poll {
                self.first_poll = false;
                self.entered.wait();
                self.release.wait();
            }
            Poll::Pending
        }
    }

    #[derive(Default)]
    struct WakeCounter(AtomicUsize);

    impl Wake for WakeCounter {
        fn wake(self: Arc<Self>) {
            self.0.fetch_add(1, AtomicOrdering::SeqCst);
        }

        fn wake_by_ref(self: &Arc<Self>) {
            self.0.fetch_add(1, AtomicOrdering::SeqCst);
        }
    }

    static PENDING_REGISTRY: RustStreamRegistry<u32, String> =
        Lazy::new(|| Mutex::new(HashMap::new()));

    struct CancelOwnerOnWake {
        owner: Arc<RustStream<u32, String>>,
        calls: Arc<AtomicUsize>,
    }

    struct ProbeRegistryOnWake {
        available: Arc<AtomicUsize>,
    }

    impl Wake for ProbeRegistryOnWake {
        fn wake(self: Arc<Self>) {
            let available = PENDING_REGISTRY.try_lock().is_ok();
            self.available
                .store(if available { 1 } else { 2 }, AtomicOrdering::SeqCst);
        }
    }

    impl Wake for CancelOwnerOnWake {
        fn wake(self: Arc<Self>) {
            self.calls.fetch_add(1, AtomicOrdering::SeqCst);
            self.owner.cancel();
        }
    }

    struct CancelOwnerOnWakerDrop {
        owner: Weak<RustStream<u32, String>>,
        calls: Arc<AtomicUsize>,
    }

    impl Wake for CancelOwnerOnWakerDrop {
        fn wake(self: Arc<Self>) {}
    }

    impl Drop for CancelOwnerOnWakerDrop {
        fn drop(&mut self) {
            self.calls.fetch_add(1, AtomicOrdering::SeqCst);
            if let Some(owner) = self.owner.upgrade() {
                owner.cancel();
            }
        }
    }

    struct ReentrantPollAndDropStream {
        owner: Arc<Mutex<Option<Weak<RustStream<u32, String>>>>>,
        poll_calls: Arc<AtomicUsize>,
        drop_calls: Arc<AtomicUsize>,
    }

    impl Stream for ReentrantPollAndDropStream {
        type Item = Result<u32, String>;

        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
            self.poll_calls.fetch_add(1, AtomicOrdering::SeqCst);
            if let Some(owner) = self.owner.lock().unwrap().as_ref().and_then(Weak::upgrade) {
                owner.cancel();
            }
            Poll::Pending
        }
    }

    impl Drop for ReentrantPollAndDropStream {
        fn drop(&mut self) {
            self.drop_calls.fetch_add(1, AtomicOrdering::SeqCst);
            if let Some(owner) = self.owner.lock().unwrap().as_ref().and_then(Weak::upgrade) {
                owner.cancel();
            }
        }
    }

    struct CancelRegistryOnDropStream {
        handle: Arc<Mutex<Option<Handle>>>,
    }

    impl Stream for CancelRegistryOnDropStream {
        type Item = Result<u32, String>;

        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
            Poll::Ready(None)
        }
    }

    impl Drop for CancelRegistryOnDropStream {
        fn drop(&mut self) {
            if let Some(handle) = self.handle.lock().unwrap().clone() {
                rust_stream_cancel(&PENDING_REGISTRY, handle);
            }
        }
    }

    fn completes_within_timeout(action: impl FnOnce() + Send + 'static) {
        let (sender, receiver) = mpsc::channel();
        let worker = std::thread::spawn(move || {
            action();
            sender.send(()).unwrap();
        });
        match receiver.recv_timeout(Duration::from_secs(2)) {
            Ok(()) => worker.join().unwrap(),
            Err(mpsc::RecvTimeoutError::Disconnected) => worker.join().unwrap(),
            Err(mpsc::RecvTimeoutError::Timeout) => {
                panic!("re-entrant stream callback deadlocked for more than two seconds")
            }
        }
    }

    #[test]
    fn cancelling_pending_next_wakes_and_completes_eof() {
        let handle = rust_stream_new(&PENDING_REGISTRY, Box::pin(AlwaysPending));
        let mut next = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, handle.clone()));
        let counter = Arc::new(WakeCounter::default());
        let waker = Waker::from(counter.clone());
        let mut cx = Context::from_waker(&waker);

        assert!(matches!(next.as_mut().poll(&mut cx), Poll::Pending));
        rust_stream_cancel(&PENDING_REGISTRY, handle.clone());
        assert_eq!(counter.0.load(AtomicOrdering::SeqCst), 1);
        assert!(matches!(
            next.as_mut().poll(&mut cx),
            Poll::Ready(Ok(Ok(None)))
        ));
        assert!(!PENDING_REGISTRY
            .lock()
            .unwrap()
            .contains_key(&handle.as_raw()));

        // Repeated cancellation is idempotent and never emits a second wake.
        rust_stream_cancel(&PENDING_REGISTRY, handle);
        assert_eq!(counter.0.load(AtomicOrdering::SeqCst), 1);
    }

    #[test]
    fn concurrent_next_lift_error_preserves_registry_for_pending_cancel() {
        let handle = rust_stream_new(&PENDING_REGISTRY, Box::pin(AlwaysPending));
        let mut first = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, handle.clone()));
        let counter = Arc::new(WakeCounter::default());
        let waker = Waker::from(counter.clone());
        let mut cx = Context::from_waker(&waker);
        assert!(matches!(first.as_mut().poll(&mut cx), Poll::Pending));

        let mut concurrent = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, handle.clone()));
        assert!(matches!(
            concurrent.as_mut().poll(&mut cx),
            Poll::Ready(Err(_))
        ));
        assert!(PENDING_REGISTRY
            .lock()
            .unwrap()
            .contains_key(&handle.as_raw()));

        rust_stream_cancel(&PENDING_REGISTRY, handle.clone());
        assert_eq!(counter.0.load(AtomicOrdering::SeqCst), 1);
        assert!(matches!(
            first.as_mut().poll(&mut cx),
            Poll::Ready(Ok(Ok(None)))
        ));
        assert!(!PENDING_REGISTRY
            .lock()
            .unwrap()
            .contains_key(&handle.as_raw()));
    }

    #[test]
    fn cancel_wakes_after_releasing_registry_mutex() {
        let handle = rust_stream_new(&PENDING_REGISTRY, Box::pin(AlwaysPending));
        let mut next = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, handle.clone()));
        let available = Arc::new(AtomicUsize::new(0));
        let waker = Waker::from(Arc::new(ProbeRegistryOnWake {
            available: available.clone(),
        }));
        let mut cx = Context::from_waker(&waker);
        assert!(matches!(next.as_mut().poll(&mut cx), Poll::Pending));
        rust_stream_cancel(&PENDING_REGISTRY, handle);
        assert_eq!(available.load(AtomicOrdering::SeqCst), 1);
        assert!(matches!(
            next.as_mut().poll(&mut cx),
            Poll::Ready(Ok(Ok(None)))
        ));
    }

    #[test]
    fn wake_and_waker_drop_can_reenter_stream_state_without_deadlock() {
        completes_within_timeout(|| {
            let owner = Arc::new(RustStream::new(Box::pin(AlwaysPending)));
            let wake_calls = Arc::new(AtomicUsize::new(0));
            let mut next = Box::pin(owner.clone().begin_next());
            let waker = Waker::from(Arc::new(CancelOwnerOnWake {
                owner: owner.clone(),
                calls: wake_calls.clone(),
            }));
            let mut cx = Context::from_waker(&waker);
            assert!(matches!(next.as_mut().poll(&mut cx), Poll::Pending));
            owner.cancel();
            assert_eq!(wake_calls.load(AtomicOrdering::SeqCst), 1);
            assert!(matches!(
                next.as_mut().poll(&mut cx),
                Poll::Ready(Ok(Ok(None)))
            ));

            let owner = Arc::new(RustStream::new(Box::pin(AlwaysPending)));
            let drop_calls = Arc::new(AtomicUsize::new(0));
            let mut next = Box::pin(owner.clone().begin_next());
            {
                let waker = Waker::from(Arc::new(CancelOwnerOnWakerDrop {
                    owner: Arc::downgrade(&owner),
                    calls: drop_calls.clone(),
                }));
                let mut cx = Context::from_waker(&waker);
                assert!(matches!(next.as_mut().poll(&mut cx), Poll::Pending));
            }
            let waker = Waker::noop();
            let mut cx = Context::from_waker(waker);
            assert!(matches!(
                next.as_mut().poll(&mut cx),
                Poll::Ready(Ok(Ok(None)))
            ));
            assert_eq!(drop_calls.load(AtomicOrdering::SeqCst), 1);
        });
    }

    #[test]
    fn user_stream_poll_and_drop_can_reenter_state_without_deadlock() {
        completes_within_timeout(|| {
            let owner_slot = Arc::new(Mutex::new(None));
            let poll_calls = Arc::new(AtomicUsize::new(0));
            let drop_calls = Arc::new(AtomicUsize::new(0));
            let owner = Arc::new(RustStream::new(Box::pin(ReentrantPollAndDropStream {
                owner: owner_slot.clone(),
                poll_calls: poll_calls.clone(),
                drop_calls: drop_calls.clone(),
            })));
            *owner_slot.lock().unwrap() = Some(Arc::downgrade(&owner));
            let mut next = Box::pin(owner.clone().begin_next());
            let waker = Waker::noop();
            let mut cx = Context::from_waker(waker);
            assert!(matches!(
                next.as_mut().poll(&mut cx),
                Poll::Ready(Ok(Ok(None)))
            ));
            assert_eq!(poll_calls.load(AtomicOrdering::SeqCst), 1);
            assert_eq!(drop_calls.load(AtomicOrdering::SeqCst), 1);
        });
    }

    #[test]
    fn stream_drop_can_reenter_raw_cancel_without_registry_deadlock() {
        completes_within_timeout(|| {
            let handle_slot = Arc::new(Mutex::new(None));
            let handle = rust_stream_new(
                &PENDING_REGISTRY,
                Box::pin(CancelRegistryOnDropStream {
                    handle: handle_slot.clone(),
                }),
            );
            *handle_slot.lock().unwrap() = Some(handle.clone());
            let mut next = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, handle.clone()));
            let waker = Waker::noop();
            let mut cx = Context::from_waker(waker);
            assert!(matches!(
                next.as_mut().poll(&mut cx),
                Poll::Ready(Ok(Ok(None)))
            ));
            assert!(!PENDING_REGISTRY
                .lock()
                .unwrap()
                .contains_key(&handle.as_raw()));
        });
    }

    #[test]
    fn cancel_before_poll_and_dropped_pending_next_release_state() {
        let before_poll = rust_stream_new(&PENDING_REGISTRY, Box::pin(AlwaysPending));
        let mut next = Box::pin(rust_stream_next_async(
            &PENDING_REGISTRY,
            before_poll.clone(),
        ));
        rust_stream_cancel(&PENDING_REGISTRY, before_poll);
        let waker = Waker::noop();
        let mut cx = Context::from_waker(waker);
        assert!(matches!(
            next.as_mut().poll(&mut cx),
            Poll::Ready(Ok(Ok(None)))
        ));

        let dropped = rust_stream_new(&PENDING_REGISTRY, Box::pin(AlwaysPending));
        let mut first = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, dropped.clone()));
        assert!(matches!(first.as_mut().poll(&mut cx), Poll::Pending));
        drop(first);
        let mut second = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, dropped.clone()));
        assert!(matches!(second.as_mut().poll(&mut cx), Poll::Pending));
        rust_stream_cancel(&PENDING_REGISTRY, dropped);
        assert!(matches!(
            second.as_mut().poll(&mut cx),
            Poll::Ready(Ok(Ok(None)))
        ));
    }

    #[test]
    fn cancel_racing_with_pending_poll_has_no_lost_wake() {
        let entered = Arc::new(Barrier::new(2));
        let release = Arc::new(Barrier::new(2));
        let handle = rust_stream_new(
            &PENDING_REGISTRY,
            Box::pin(GatedPending {
                entered: entered.clone(),
                release: release.clone(),
                first_poll: true,
            }),
        );
        let counter = Arc::new(WakeCounter::default());
        let thread_counter = counter.clone();
        let thread_handle = handle.clone();
        let (first_poll_sender, first_poll_receiver) = mpsc::channel();
        let (resume_sender, resume_receiver) = mpsc::channel();
        let poller = std::thread::spawn(move || {
            let mut next = Box::pin(rust_stream_next_async(&PENDING_REGISTRY, thread_handle));
            let waker = Waker::from(thread_counter);
            let mut cx = Context::from_waker(&waker);
            match next.as_mut().poll(&mut cx) {
                Poll::Pending => {
                    first_poll_sender.send(false).unwrap();
                    resume_receiver
                        .recv_timeout(Duration::from_secs(5))
                        .unwrap();
                    assert!(matches!(
                        next.as_mut().poll(&mut cx),
                        Poll::Ready(Ok(Ok(None)))
                    ));
                }
                Poll::Ready(Ok(Ok(None))) => {
                    // Cancellation won the race while user poll code was
                    // gated, so this very poll observed Closed and settled.
                    first_poll_sender.send(true).unwrap();
                }
                other => panic!("unexpected first racing poll result: {other:?}"),
            }
        });

        entered.wait();
        let cancel_started = Arc::new(Barrier::new(2));
        let cancel_thread_started = cancel_started.clone();
        let canceller = std::thread::spawn(move || {
            cancel_thread_started.wait();
            rust_stream_cancel(&PENDING_REGISTRY, handle);
        });
        cancel_started.wait();
        release.wait();
        let completed_in_first_poll = first_poll_receiver
            .recv_timeout(Duration::from_secs(5))
            .unwrap();
        canceller.join().unwrap();
        assert_eq!(counter.0.load(AtomicOrdering::SeqCst), 1);
        if !completed_in_first_poll {
            resume_sender.send(()).unwrap();
        }
        poller.join().unwrap();
    }
}
