/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Electron preload + renderer facade emitter.
//!
//! The templates below implement the contract pinned in
//! `docs/manual/src/javascript/contract.md` under the
//! "Electron preload ↔ renderer message shape" section:
//!
//! - each component preload module loads its `.node` addon and owns a handle
//!   registry; the generated aggregate root is the only file that calls
//!   `contextBridge.exposeInMainWorld("__uniffi__", ...)`.
//! - renderer.ts installs an `__uniffiBackend` Proxy that forwards every
//!   call through the bridge, so `common/api.ts` runs unchanged inside
//!   the renderer.
//!
//! Because the preload is generic (it just forwards named calls through
//! to the addon), it does not need to enumerate the namespace's
//! functions. That said, the addon path and namespace are still baked
//! in so the file is self-contained and requires no extra wiring in
//! `BrowserWindow`.
//!
//! This backend grew out of earlier application-level prototypes, but
//! the generator now treats it as a generic Electron integration for
//! any uniffi namespace.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;
use uniffi_bindgen::Component;

use crate::{JsConfig, JS_RUNTIME_ABI_VERSION};

pub fn emit(
    dir: &Utf8Path,
    component: &Component<JsConfig>,
    default_addon_path: Option<&str>,
) -> Result<()> {
    let ci = &component.ci;
    let ns = ci.namespace();
    let async_keys = crate::dispatch_key::collect_async_keys(ci);
    let name_pairs = crate::name_map::collect(ci);
    let name_map_literal = crate::name_map::render_name_map_js_literal(&name_pairs);
    let enum_shape_helpers = crate::enum_shape::helper_js();
    fs::write(
        dir.join("preload.cjs"),
        render_preload(
            ns,
            &name_map_literal,
            enum_shape_helpers,
            default_addon_path,
        ),
    )?;
    fs::write(dir.join("renderer.ts"), render_renderer(ns, &async_keys))?;
    Ok(())
}

fn render_preload(
    namespace: &str,
    name_map_literal: &str,
    enum_shape_helpers: &str,
    default_addon_path: Option<&str>,
) -> String {
    let default_addon_path = default_addon_path
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("{namespace}.node"));
    let env_var = crate::flavors::napi::napi_path_env_var(namespace);
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (electron preload).\n\
         //\n\
         // Generic preload for namespace `{namespace}`. Loads the compiled\n\
         // napi addon, owns the handle registry, serialises errors, and\n\
         // exports one bridge object. The aggregate preload is the only\n\
         // file that installs contextBridge, so components cannot overwrite\n\
         // one another. The shape is pinned in docs/manual/src/javascript/contract.md.\n\
         \n\
         const path = require(\"node:path\");\n\
         const __uniffiSpecificNapiPathEnv = \"{env_var}\";\n\
         const __uniffiDefaultAddonPath = \"{default_addon_path}\";\n\
         \n\
         function __uniffiResolveEnvAddonPath(value) {{\n\
             return path.isAbsolute(value) ? value : path.resolve(value);\n\
         }}\n\
         \n\
         function __uniffiAddonCandidate() {{\n\
             const specific = process.env[__uniffiSpecificNapiPathEnv];\n\
             if (specific && specific.length > 0) {{\n\
                 return {{ label: __uniffiSpecificNapiPathEnv, specifier: __uniffiResolveEnvAddonPath(specific) }};\n\
             }}\n\
             const generic = process.env.UNIFFI_NAPI_PATH;\n\
             if (generic && generic.length > 0) {{\n\
                 return {{ label: \"UNIFFI_NAPI_PATH\", specifier: __uniffiResolveEnvAddonPath(generic) }};\n\
             }}\n\
             return {{ label: \"default\", specifier: path.resolve(__dirname, __uniffiDefaultAddonPath) }};\n\
         }}\n\
         \n\
         const addonCandidate = __uniffiAddonCandidate();\n\
         const addon = require(addonCandidate.specifier);\n\
         \n\
         // Generator-computed map from the low-level snake_case keys used\n\
         // by `common/api.ts` to exact component-prefixed native names.\n\
         // Same source of truth as\n\
         // `node/backend-napi.ts` — see\n\
         // `uniffi_bindgen_javascript/src/name_map.rs`.\n\
         const __uniffiNameMap = {name_map_literal};\n\
         \n\
         {enum_shape_helpers}\n\
         function resolveMethod(method) {{\n\
             const exportName = __uniffiNameMap[method];\n\
             if (typeof exportName !== \"string\") {{\n\
                 throw new Error(\"unknown uniffi method: \" + method + \" (no canonical native export mapping)\");\n\
             }}\n\
             const fn = addon[exportName];\n\
             if (typeof fn !== \"function\") {{\n\
                 throw new Error(\n\
                     \"unknown uniffi method: \" + method +\n\
                     \" (addon export \\\"\" + exportName + \"\\\" missing)\",\n\
                 );\n\
             }}\n\
             return fn;\n\
         }}\n\
         \n\
         const handles = new Map();\n\
         let nextHandleId = 1;\n\
         const __uniffiReturnedCallbacks = new Map();\n\
         let __uniffiNextReturnedCallbackId = 1;\n\
         \n\
         function serializeError(raw) {{\n\
             if (raw && typeof raw === \"object\") {{\n\
                 return {{\n\
                     errorName: typeof raw.errorName === \"string\" ? raw.errorName : \"UniffiUnknownError\",\n\
                     variant: typeof raw.variant === \"string\" ? raw.variant : null,\n\
                     data: raw.data ?? null,\n\
                     message: typeof raw.message === \"string\" ? raw.message : String(raw),\n\
                     stack: typeof raw.stack === \"string\" ? raw.stack : undefined,\n\
                 }};\n\
             }}\n\
             return {{ errorName: \"UniffiUnknownError\", variant: null, data: null, message: String(raw) }};\n\
         }}\n\
         \n\
         function storeHandle(value) {{\n\
             const id = nextHandleId++;\n\
             handles.set(id, value);\n\
             return id;\n\
         }}\n\
         \n\
         function __uniffiIsHostPlainObject(v) {{\n\
             if (v === null || typeof v !== \"object\") return false;\n\
             if (Array.isArray(v)) return false;\n\
             const proto = Object.getPrototypeOf(v);\n\
             return proto === Object.prototype || proto === null;\n\
         }}\n\
         \n\
         function __uniffiCallbackErrorPayload(error, shape) {{\n\
             if (error !== null && typeof error === \"object\") {{\n\
                 const raw = error;\n\
                 if (shape === \"flat\") {{\n\
                     if (typeof raw.variant === \"string\") return raw.variant;\n\
                     if (typeof raw.tag === \"string\") return raw.tag;\n\
                     if (typeof raw.type === \"string\") return raw.type;\n\
                 }}\n\
                 if (typeof raw.tag === \"string\" || typeof raw.type === \"string\") {{\n\
                     return __uniffiLowerShape(raw);\n\
                 }}\n\
                 if (typeof raw.variant === \"string\") {{\n\
                     const data = raw.data;\n\
                     const payload = {{ tag: raw.variant }};\n\
                     if (data !== null && typeof data === \"object\" && !Array.isArray(data)) {{\n\
                         Object.assign(payload, data);\n\
                     }}\n\
                     return __uniffiLowerShape(payload);\n\
                 }}\n\
             }}\n\
             throw error;\n\
         }}\n\
         \n\
         function __uniffiDispatchReturnedCallback(...rawArgs) {{\n\
             const args = rawArgs.length >= 3 && (rawArgs[0] === null || rawArgs[0] === undefined || rawArgs[0] instanceof Error)\n\
                 ? rawArgs.slice(1)\n\
                 : rawArgs;\n\
             const id = args[0];\n\
             const method = args[1];\n\
             if (typeof id !== \"number\" || typeof method !== \"string\") {{\n\
                 throw new Error(\"invalid uniffi returned-callback dispatch arguments\");\n\
             }}\n\
             const obj = __uniffiReturnedCallbacks.get(id);\n\
             if (!obj) {{\n\
                 throw new Error(\"uniffi returned callback \" + id + \" is not available\");\n\
             }}\n\
             const fn = obj[method];\n\
             if (typeof fn !== \"function\") {{\n\
                 throw new Error(\"uniffi returned callback \" + id + \" has no method \" + method);\n\
             }}\n\
             return fn(...args.slice(2).map(__uniffiLiftShape));\n\
         }}\n\
         \n\
         function __uniffiStoreCallbackReturn(value) {{\n\
             const marker = value && typeof value === \"object\" && value.__uniffiCallback === true ? value : null;\n\
             const obj = marker ? __uniffiNormalizeCallbackObject(marker.object, marker) : __uniffiNormalizeCallbackObject(value);\n\
             const id = __uniffiNextReturnedCallbackId++;\n\
             __uniffiReturnedCallbacks.set(id, obj);\n\
             return {{ id }};\n\
         }}\n\
         \n\
         function __uniffiNormalizeCallbackObject(obj, marker) {{\n\
             if (obj === null || typeof obj !== \"object\") return obj;\n\
             const fallibleMethods = (marker && marker.fallibleMethods) || {{}};\n\
             const asyncMethods = (marker && marker.asyncMethods) || {{}};\n\
             const callbackReturnMethods = (marker && marker.callbackReturnMethods) || {{}};\n\
             const out = {{}};\n\
             const keys = Object.keys(obj);\n\
             for (let i = 0; i < keys.length; i++) {{\n\
                 const k = keys[i];\n\
                 const v = obj[k];\n\
                 if (typeof v === \"function\") {{\n\
                     out[k] = (...args) => {{\n\
                         const callArgs = args.length >= 2 && (args[0] === null || args[0] === undefined || args[0] instanceof Error)\n\
                             ? args.slice(1)\n\
                             : args;\n\
                         const liftedArgs = callArgs.map(__uniffiLiftShape);\n\
                         const errorShape = fallibleMethods[k];\n\
                         const isAsync = asyncMethods[k] === true;\n\
                         const returnsCallback = callbackReturnMethods[k] === true;\n\
                         if (!errorShape) {{\n\
                             if (isAsync) {{\n\
                                 return Promise.resolve(v(...liftedArgs)).then(function (value) {{\n\
                                     return returnsCallback ? __uniffiStoreCallbackReturn(value) : __uniffiLowerShape(resolveArg(value));\n\
                                 }});\n\
                             }}\n\
                             return __uniffiLowerShape(resolveArg(v(...liftedArgs)));\n\
                         }}\n\
                         if (isAsync) {{\n\
                             return Promise.resolve(v(...liftedArgs)).then(\n\
                                 function (value) {{ return {{ ok: true, value: returnsCallback ? __uniffiStoreCallbackReturn(value) : __uniffiLowerShape(resolveArg(value)) }}; }},\n\
                                 function (error) {{ return {{ ok: false, error: __uniffiCallbackErrorPayload(error, errorShape) }}; }}\n\
                             );\n\
                         }}\n\
                         try {{\n\
                             return {{ ok: true, value: __uniffiLowerShape(resolveArg(v(...liftedArgs))) }};\n\
                         }} catch (error) {{\n\
                             return {{ ok: false, error: __uniffiCallbackErrorPayload(error, errorShape) }};\n\
                         }}\n\
                     }};\n\
                 }} else {{\n\
                     out[k] = v;\n\
                 }}\n\
             }}\n\
             out.__uniffiCallbackDispatcher = __uniffiDispatchReturnedCallback;\n\
             return out;\n\
         }}\n\
         \n\
         function resolveArg(arg) {{\n\
             if (arg && typeof arg === \"object\" && arg.__uniffiHandle === true) {{\n\
                 const h = handles.get(arg.id);\n\
                 if (!h) {{\n\
                     throw new Error(`uniffi handle ${{arg.id}} is not available`);\n\
                 }}\n\
                 return h;\n\
             }}\n\
             if (arg && typeof arg === \"object\" && arg.__uniffiCallback === true) {{\n\
                 return __uniffiNormalizeCallbackObject(arg.object, arg);\n\
             }}\n\
             if (arg && typeof arg === \"object\" && arg.__uniffiInputStream === true) {{\n\
                 return {{ handle: arg.handle, next: arg.next, cancel: arg.cancel }};\n\
             }}\n\
             return arg;\n\
         }}\n\
         \n\
         // Only wrap true opaque napi class instances as handles.\n\
         function wrapResult(value) {{\n\
             if (!value || typeof value !== \"object\") return value;\n\
             if (Array.isArray(value)) return value;\n\
             if (ArrayBuffer.isView(value)) return value;\n\
             if (value instanceof ArrayBuffer) return value;\n\
             if (\n\
                 value instanceof Map ||\n\
                 value instanceof Set ||\n\
                 value instanceof Date ||\n\
                 value instanceof RegExp ||\n\
                 value instanceof Error ||\n\
                 value instanceof Promise\n\
             ) {{\n\
                 return value;\n\
             }}\n\
             if (__uniffiIsHostPlainObject(value)) {{\n\
                 return value;\n\
             }}\n\
             return {{ __uniffiHandle: true, id: storeHandle(value) }};\n\
         }}\n\
         \n\
         // N-API represents optional object fields according to the host's
         // property rules. Normalize only output-stream pulls at this trust
         // boundary so common/api.ts always receives the exact tagged v2
         // shape: Item owns value (including null), Done owns no payload, and
         // Error owns error only.
         function __uniffiNormalizeStreamStep(value) {{\n\
             if (value === null || typeof value !== \"object\") return value;\n\
             const raw = value;\n\
             if (raw.kind === \"item\" && Object.prototype.hasOwnProperty.call(raw, \"value\")) {{\n\
                 return {{ kind: \"item\", value: raw.value }};\n\
             }}\n\
             if (raw.kind === \"done\") {{\n\
                 return {{ kind: \"done\" }};\n\
             }}\n\
             if (raw.kind === \"error\" && Object.prototype.hasOwnProperty.call(raw, \"error\")) {{\n\
                 return {{ kind: \"error\", error: raw.error }};\n\
             }}\n\
             return value;\n\
         }}\n\
         \n\
         function __uniffiLiftResult(method, value) {{\n\
             const lifted = __uniffiLiftShape(value);\n\
             return method.endsWith(\"_stream_next\")\n\
                 ? __uniffiNormalizeStreamStep(lifted)\n\
                 : lifted;\n\
         }}\n\
         \n\
         function dispatchSync(msg) {{\n\
             try {{\n\
                 switch (msg.kind) {{\n\
                     case \"drop\": {{\n\
                         handles.delete(msg.id);\n\
                         return {{ kind: \"ok\", id: msg.id, value: undefined }};\n\
                     }}\n\
                     case \"call\": {{\n\
                         const fn = resolveMethod(msg.method);\n\
                         const resolved = (msg.args || []).map(function (a) {{\n\
                             return __uniffiLowerShape(resolveArg(a));\n\
                         }});\n\
                         const raw = fn.apply(addon, resolved);\n\
                         return {{ kind: \"ok\", id: msg.id, value: wrapResult(__uniffiLiftResult(msg.method, raw)) }};\n\
                     }}\n\
                     default:\n\
                         throw new Error(`unknown bridge message kind: ${{msg.kind}}`);\n\
                 }}\n\
             }} catch (error) {{\n\
                 return {{ kind: \"err\", id: msg.id, error: serializeError(__uniffiLiftShape(error)) }};\n\
             }}\n\
         }}\n\
         \n\
         async function dispatchAsync(msg) {{\n\
             try {{\n\
                 if (msg.kind !== \"call\") {{\n\
                     return dispatchSync(msg);\n\
                 }}\n\
                 const fn = resolveMethod(msg.method);\n\
                 const resolved = (msg.args || []).map(function (a) {{\n\
                     return __uniffiLowerShape(resolveArg(a));\n\
                 }});\n\
                 const raw = await fn.apply(addon, resolved);\n\
                 return {{ kind: \"ok\", id: msg.id, value: wrapResult(__uniffiLiftResult(msg.method, raw)) }};\n\
             }} catch (error) {{\n\
                 return {{ kind: \"err\", id: msg.id, error: serializeError(__uniffiLiftShape(error)) }};\n\
             }}\n\
         }}\n\
         \n\
         module.exports = Object.freeze({{\n\
             namespace: \"{namespace}\",\n\
             __uniffiJsRuntimeAbiVersion: {JS_RUNTIME_ABI_VERSION},\n\
             dispatchSync,\n\
             dispatchAsync,\n\
         }});\n"
    )
}

fn render_renderer(namespace: &str, async_keys: &[String]) -> String {
    let async_set_literal = if async_keys.is_empty() {
        "new Set<string>()".to_string()
    } else {
        let joined = async_keys
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!("new Set<string>([{joined}])")
    };
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (electron renderer).\n\
         //\n\
         // Renderer-side facade for namespace `{namespace}`. Installs a\n\
         // backend proxy that forwards every call through the preload\n\
         // bridge, then re-exports the high-level API from\n\
         // `../common/api`. Applications import from this file directly.\n\
         //\n\
         // CRITICAL: sync Rust exports must stay synchronous on the\n\
         // renderer side. The generator bakes in the set of async\n\
         // dispatch keys below; everything outside that set is bound to\n\
         // `dispatchSync`, which preserves `common/api.ts`'s `__call<T>`\n\
         // contract (React render code must not see a Promise when it\n\
         // calls e.g. `core.greet(name)`).\n\
         \n\
         import {{ __installBackend, UniffiError }} from \"../common/runtime.ts\";\n\
         export * from \"../common/api.ts\";\n\
         \n\
         type BridgeMessage =\n\
             | {{ kind: \"call\"; id: number; method: string; args: unknown[] }}\n\
             | {{ kind: \"drop\"; id: number }};\n\
         type BridgeResponse =\n\
             | {{ kind: \"ok\"; id: number; value: unknown }}\n\
             | {{ kind: \"err\"; id: number; error: {{ errorName: string; variant: string | null; data: unknown; message: string; stack?: string }} }};\n\
         type ComponentBridge = {{\n\
             namespace: string;\n\
             __uniffiJsRuntimeAbiVersion: {JS_RUNTIME_ABI_VERSION};\n\
             dispatchSync: (msg: BridgeMessage) => BridgeResponse;\n\
             dispatchAsync: (msg: BridgeMessage) => Promise<BridgeResponse>;\n\
         }};\n\
         declare global {{\n\
             interface Window {{\n\
                 __uniffi__: {{ components: Record<string, ComponentBridge> }};\n\
             }}\n\
         }}\n\
         const __uniffiBridge = window.__uniffi__.components[\"{namespace}\"];\n\
         if (!__uniffiBridge) {{\n\
             throw new Error(\"missing Electron UniFFI bridge for namespace `{namespace}`\");\n\
         }}\n\
         \n\
         /** Generator-computed: dispatch keys flagged `async` in the IR. */\n\
         const ASYNC_METHODS: Set<string> = {async_set_literal};\n\
         \n\
         let nextCallId = 1;\n\
         \n\
         function unwrap(response: BridgeResponse): unknown {{\n\
             if (response.kind === \"ok\") return response.value;\n\
             throw new UniffiError({{\n\
                 errorName: response.error.errorName,\n\
                 variant: response.error.variant,\n\
                 data: response.error.data,\n\
                 message: response.error.message,\n\
                 stack: response.error.stack,\n\
             }});\n\
         }}\n\
         \n\
         function callSync(method: string, ...args: unknown[]): unknown {{\n\
             const id = nextCallId++;\n\
             return unwrap(\n\
                 __uniffiBridge.dispatchSync({{ kind: \"call\", id, method, args }}),\n\
             );\n\
         }}\n\
         \n\
         function dropSync(handle: unknown): void {{\n\
             if (\n\
                 handle !== null &&\n\
                 typeof handle === \"object\" &&\n\
                 (handle as {{ __uniffiHandle?: boolean }}).__uniffiHandle === true\n\
             ) {{\n\
                 unwrap(__uniffiBridge.dispatchSync({{ kind: \"drop\", id: (handle as {{ id: number }}).id }}));\n\
             }}\n\
         }}\n\
         \n\
         async function callAsync(method: string, ...args: unknown[]): Promise<unknown> {{\n\
             const id = nextCallId++;\n\
             return unwrap(\n\
                 await __uniffiBridge.dispatchAsync({{ kind: \"call\", id, method, args }}),\n\
             );\n\
         }}\n\
         \n\
         const backend = new Proxy({{}}, {{\n\
             get(_t, method: string) {{\n\
                 if (method === \"__uniffiJsRuntimeAbiVersion\") {{\n\
                     return __uniffiBridge.__uniffiJsRuntimeAbiVersion;\n\
                 }}\n\
                 if (method.startsWith(\"__uniffi_\") && method.endsWith(\"_object_free\")) {{\n\
                     // `common/objects.ts` calls the wasm-style destructor\n\
                     // key for all flavors. In Electron, opaque handles live\n\
                     // in preload, so translate the destructor into the\n\
                     // existing synchronous drop bridge message.\n\
                     return (handle: unknown) => dropSync(handle);\n\
                 }}\n\
                 if (ASYNC_METHODS.has(method)) {{\n\
                     return (...args: unknown[]) => callAsync(method, ...args);\n\
                 }}\n\
                 return (...args: unknown[]) => callSync(method, ...args);\n\
             }},\n\
         }});\n\
         __installBackend(backend);\n"
    )
}
