/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Electron preload + renderer facade emitter.
//!
//! The templates below implement the contract pinned in
//! `docs/manual/src/javascript/contract.md` under the
//! "Electron preload ↔ renderer message shape" section:
//!
//! - preload.cjs loads the `.node` addon, owns a handle registry, and
//!   exposes a single `(msg) => Promise<response>` bridge function via
//!   `contextBridge.exposeInMainWorld("__uniffi__", ...)`.
//! - renderer.ts installs an `__uniffiBackend` Proxy that forwards every
//!   call through the bridge, so `common/api.ts` runs unchanged inside
//!   the renderer.
//!
//! Because the preload is generic (it just forwards named calls through
//! to the addon), it does not need to enumerate the namespace's
//! functions. That said, the addon path and namespace are still baked
//! in so the file is self-contained and requires no extra wiring in
//! `BrowserWindow`.
//!
//! This backend grew out of earlier application-level prototypes, but
//! the generator now treats it as a generic Electron integration for
//! any uniffi namespace.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;
use heck::ToSnakeCase;
use uniffi_bindgen::interface::AsType;
use uniffi_bindgen::{Component, ComponentInterface};
use uniffi_meta::Type;

use crate::JsConfig;

pub fn emit(dir: &Utf8Path, component: &Component<JsConfig>) -> Result<()> {
    let ci = &component.ci;
    let ns = ci.namespace();
    let async_keys = collect_async_keys(ci);
    let name_pairs = crate::name_map::collect(ci);
    let name_map_literal = crate::name_map::render_name_map_js_literal(&name_pairs);
    let int64_arg_map = render_int64_arg_map_js_literal(ci);
    let int64_ret_map = render_int64_return_map_js_literal(ci);
    let enum_shape_helpers = crate::enum_shape::helper_js();
    fs::write(
        dir.join("preload.cjs"),
        render_preload(ns, &name_map_literal, &int64_arg_map, &int64_ret_map, enum_shape_helpers),
    )?;
    fs::write(dir.join("renderer.ts"), render_renderer(ns, &async_keys))?;
    Ok(())
}

/// Walk the component interface and compute the set of backend dispatch
/// keys that are async. The naming must stay in lockstep with
/// `api_module/mod.rs`: free functions use the raw Rust name,
/// constructors/methods use `{obj_snake}_{member_snake}`.
fn collect_async_keys(ci: &ComponentInterface) -> Vec<String> {
    let mut keys = Vec::new();
    for f in ci.function_definitions() {
        if f.is_async() {
            keys.push(f.name().to_string());
        }
    }
    for obj in ci.object_definitions() {
        let snake = obj.name().to_snake_case();
        for c in obj.constructors() {
            if c.is_async() {
                keys.push(format!("{snake}_{}", c.name().to_snake_case()));
            }
        }
        for m in obj.methods() {
            if m.is_async() {
                keys.push(format!("{snake}_{}", m.name().to_snake_case()));
            }
        }
    }
    keys.sort();
    keys.dedup();
    keys
}

fn render_preload(
    namespace: &str,
    name_map_literal: &str,
    int64_arg_map: &str,
    int64_ret_map: &str,
    enum_shape_helpers: &str,
) -> String {
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (electron preload).\n\
         //\n\
         // Generic preload for namespace `{namespace}`. Loads the compiled\n\
         // napi addon, owns the handle registry, serialises errors, and\n\
         // exposes a single bridge function via contextBridge. The shape\n\
         // is pinned in docs/manual/src/javascript/contract.md.\n\
         \n\
         const path = require(\"node:path\");\n\
         const {{ contextBridge }} = require(\"electron\");\n\
         \n\
         const addonPath = path.resolve(__dirname, \"{namespace}.node\");\n\
         const addon = require(addonPath);\n\
         \n\
         // Generator-computed map from the low-level snake_case keys used\n\
         // by `common/api.ts` to the `lowerCamelCase` names napi-rs\n\
         // actually puts on the addon. Same source of truth as\n\
         // `node/backend-napi.ts` — see\n\
         // `uniffi_bindgen_javascript/src/name_map.rs`.\n\
         const __uniffiNameMap = {name_map_literal};\n\
         const __uniffiInt64ArgKinds = {int64_arg_map};\n\
         const __uniffiInt64ReturnKinds = {int64_ret_map};\n\
         \n\
         {enum_shape_helpers}\n\
         const __uniffiMaxSafeBigInt = BigInt(Number.MAX_SAFE_INTEGER);\n\
         const __uniffiMinSafeBigInt = BigInt(Number.MIN_SAFE_INTEGER);\n\
         \n\
         function __uniffiLowerInt64ForNapi(value, kind) {{\n\
             if (kind === null || kind === undefined) return value;\n\
             if (typeof value === \"bigint\") {{\n\
                 if (kind === \"u64\" && value < 0n) {{\n\
                     throw new RangeError(`negative bigint value ${{value}} cannot be converted to u64`);\n\
                 }}\n\
                 if (value < __uniffiMinSafeBigInt || value > __uniffiMaxSafeBigInt) {{\n\
                     throw new RangeError(`bigint value ${{value}} exceeds the JS safe integer range supported by the current napi bridge`);\n\
                 }}\n\
                 return Number(value);\n\
             }}\n\
             if (typeof value === \"number\") {{\n\
                 if (!Number.isInteger(value) || !Number.isSafeInteger(value)) {{\n\
                     throw new RangeError(`number value ${{value}} is not a safe integer for ${{kind}}`);\n\
                 }}\n\
                 if (kind === \"u64\" && value < 0) {{\n\
                     throw new RangeError(`negative number value ${{value}} cannot be converted to u64`);\n\
                 }}\n\
                 return value;\n\
             }}\n\
             if (typeof value === \"string\") {{\n\
                 return __uniffiLowerInt64ForNapi(BigInt(value), kind);\n\
             }}\n\
             return value;\n\
         }}\n\
         \n\
         function __uniffiLiftInt64FromNapi(value, kind) {{\n\
             if (kind === null || kind === undefined) return value;\n\
             if (typeof value === \"bigint\") return value;\n\
             if (typeof value === \"number\") {{\n\
                 if (!Number.isInteger(value) || !Number.isSafeInteger(value)) {{\n\
                     throw new RangeError(`number value ${{value}} is not a safe integer result for ${{kind}}`);\n\
                 }}\n\
                 if (kind === \"u64\" && value < 0) {{\n\
                     throw new RangeError(`negative number result ${{value}} cannot be lifted as u64`);\n\
                 }}\n\
                 return BigInt(value);\n\
             }}\n\
             return value;\n\
         }}\n\
         function resolveMethod(method) {{\n\
             const exportName = Object.prototype.hasOwnProperty.call(__uniffiNameMap, method)\n\
                 ? __uniffiNameMap[method]\n\
                 : method;\n\
             const fn = addon[exportName];\n\
             if (typeof fn !== \"function\") {{\n\
                 throw new Error(\n\
                     \"unknown uniffi method: \" + method +\n\
                     \" (addon export \\\"\" + exportName + \"\\\" missing)\",\n\
                 );\n\
             }}\n\
             return fn;\n\
         }}\n\
         \n\
         const handles = new Map();\n\
         let nextHandleId = 1;\n\
         \n\
         function serializeError(raw) {{\n\
             if (raw && typeof raw === \"object\") {{\n\
                 return {{\n\
                     errorName: typeof raw.errorName === \"string\" ? raw.errorName : \"UniffiUnknownError\",\n\
                     variant: typeof raw.variant === \"string\" ? raw.variant : null,\n\
                     data: raw.data ?? null,\n\
                     message: typeof raw.message === \"string\" ? raw.message : String(raw),\n\
                     stack: typeof raw.stack === \"string\" ? raw.stack : undefined,\n\
                 }};\n\
             }}\n\
             return {{ errorName: \"UniffiUnknownError\", variant: null, data: null, message: String(raw) }};\n\
         }}\n\
         \n\
         function storeHandle(value) {{\n\
             const id = nextHandleId++;\n\
             handles.set(id, value);\n\
             return id;\n\
         }}\n\
         \n\
         function __uniffiIsHostPlainObject(v) {{\n\
             if (v === null || typeof v !== \"object\") return false;\n\
             if (Array.isArray(v)) return false;\n\
             const proto = Object.getPrototypeOf(v);\n\
             return proto === Object.prototype || proto === null;\n\
         }}\n\
         \n\
         function __uniffiNormalizeCallbackObject(obj) {{\n\
             if (obj === null || typeof obj !== \"object\") return obj;\n\
             const out = {{}};\n\
             const keys = Object.keys(obj);\n\
             for (let i = 0; i < keys.length; i++) {{\n\
                 const k = keys[i];\n\
                 const v = obj[k];\n\
                 if (typeof v === \"function\") {{\n\
                     out[k] = (...args) => {{\n\
                         const callArgs = args.length >= 2 && (args[0] === null || args[0] === undefined || args[0] instanceof Error)\n\
                             ? args.slice(1)\n\
                             : args;\n\
                         return v(...callArgs);\n\
                     }};\n\
                 }} else {{\n\
                     out[k] = v;\n\
                 }}\n\
             }}\n\
             return out;\n\
         }}\n\
         \n\
         function resolveArg(arg) {{\n\
             if (arg && typeof arg === \"object\" && arg.__uniffiHandle === true) {{\n\
                 const h = handles.get(arg.id);\n\
                 if (!h) {{\n\
                     throw new Error(`uniffi handle ${{arg.id}} is not available`);\n\
                 }}\n\
                 return h;\n\
             }}\n\
             if (arg && typeof arg === \"object\" && arg.__uniffiCallback === true) {{\n\
                 // Callback-trait marker from common/api.ts. The napi addon\n\
                 // expects the plain JS object with callable fields (see\n\
                 // uniffi_bindgen_javascript/src/flavors/napi/codegen.rs).\n\
                 // Electron preload runs in Node context so functions on\n\
                 // `arg.object` are directly callable by the addon's\n\
                 // ThreadsafeFunction.\n\
                 return __uniffiNormalizeCallbackObject(arg.object);\n\
             }}\n\
             return arg;\n\
         }}\n\
         \n\
         // Only wrap true opaque napi class instances as handles. The\n\
         // previous `constructor.name !== \"Object\"` heuristic swept up\n\
         // `Array`, `Uint8Array`, `Date`, `Map`, `Error`, etc., so\n\
         // `sampleEvents()` returned a handle stub and the renderer's\n\
         // `.map(...)` crashed. Anything that is a plain object, an\n\
         // array, a typed array, or a known builtin passes through\n\
         // untouched. Non-plain, non-builtin objects are treated as\n\
         // napi class instances and get registered in the handle map.\n\
         function wrapResult(value) {{\n\
             if (!value || typeof value !== \"object\") return value;\n\
             if (Array.isArray(value)) return value;\n\
             if (ArrayBuffer.isView(value)) return value;\n\
             if (value instanceof ArrayBuffer) return value;\n\
             if (\n\
                 value instanceof Map ||\n\
                 value instanceof Set ||\n\
                 value instanceof Date ||\n\
                 value instanceof RegExp ||\n\
                 value instanceof Error ||\n\
                 value instanceof Promise\n\
             ) {{\n\
                 return value;\n\
             }}\n\
             const proto = Object.getPrototypeOf(value);\n\
             if (__uniffiIsHostPlainObject(value)) {{\n\
                 return value;\n\
             }}\n\
             // Non-plain, non-builtin: opaque napi class instance.\n\
             return {{ __uniffiHandle: true, id: storeHandle(value) }};\n\
         }}\n\
         \n\
         function dispatchSync(msg) {{\n\
             // Synchronous path: used for sync Rust exports and for handle\n\
             // drops. Returns a plain response object (never a Promise) so\n\
             // renderer code can consume the value directly during React\n\
             // render without racing a microtask.\n\
             try {{\n\
                 switch (msg.kind) {{\n\
                     case \"drop\": {{\n\
                         handles.delete(msg.id);\n\
                         return {{ kind: \"ok\", id: msg.id, value: undefined }};\n\
                     }}\n\
                     case \"call\": {{\n\
                         const fn = resolveMethod(msg.method);\n\
                         const argKinds = __uniffiInt64ArgKinds[msg.method] || [];\n\
                         const retKind = __uniffiInt64ReturnKinds[msg.method] || null;\n\
                         const resolved = (msg.args || []).map(function (a, i) {{\n\
                             return __uniffiLowerShape(__uniffiLowerInt64ForNapi(resolveArg(a), argKinds[i] || null));\n\
                         }});\n\
                         const raw = fn.apply(addon, resolved);\n\
                         return {{ kind: \"ok\", id: msg.id, value: wrapResult(__uniffiLiftInt64FromNapi(__uniffiLiftShape(raw), retKind)) }};\n\
                     }}\n\
                     default:\n\
                         throw new Error(`unknown bridge message kind: ${{msg.kind}}`);\n\
                 }}\n\
             }} catch (error) {{\n\
                 return {{ kind: \"err\", id: msg.id, error: serializeError(__uniffiLiftShape(error)) }};\n\
             }}\n\
         }}\n\
         \n\
         async function dispatchAsync(msg) {{\n\
             // Async path: awaits the addon return value. Only used for\n\
             // methods the generator flagged as async.\n\
             try {{\n\
                 if (msg.kind !== \"call\") {{\n\
                     return dispatchSync(msg);\n\
                 }}\n\
                 const fn = resolveMethod(msg.method);\n\
                 const argKinds = __uniffiInt64ArgKinds[msg.method] || [];\n\
                 const retKind = __uniffiInt64ReturnKinds[msg.method] || null;\n\
                 const resolved = (msg.args || []).map(function (a, i) {{\n\
                     return __uniffiLowerShape(__uniffiLowerInt64ForNapi(resolveArg(a), argKinds[i] || null));\n\
                 }});\n\
                 const raw = await fn.apply(addon, resolved);\n\
                 return {{ kind: \"ok\", id: msg.id, value: wrapResult(__uniffiLiftInt64FromNapi(__uniffiLiftShape(raw), retKind)) }};\n\
             }} catch (error) {{\n\
                 return {{ kind: \"err\", id: msg.id, error: serializeError(__uniffiLiftShape(error)) }};\n\
             }}\n\
         }}\n\
         \n\
         contextBridge.exposeInMainWorld(\"__uniffi__\", {{\n\
             namespace: \"{namespace}\",\n\
             dispatchSync,\n\
             dispatchAsync,\n\
         }});\n"
    )
}

fn int64_kind(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::Int64 => Some("i64"),
        Type::UInt64 => Some("u64"),
        _ => None,
    }
}

fn collect_int64_arg_kinds(ci: &ComponentInterface) -> Vec<(String, Vec<Option<&'static str>>)> {
    let mut out = Vec::new();

    for f in ci.function_definitions() {
        let kinds: Vec<_> = f
            .arguments()
            .iter()
            .map(|a| int64_kind(&a.as_type()))
            .collect();
        if kinds.iter().any(Option::is_some) {
            out.push((f.name().to_string(), kinds));
        }
    }

    for obj in ci.object_definitions() {
        let obj_snake = obj.name().to_snake_case();
        for c in obj.constructors() {
            let key = format!("{obj_snake}_{}", c.name().to_snake_case());
            let kinds: Vec<_> = c
                .arguments()
                .iter()
                .map(|a| int64_kind(&a.as_type()))
                .collect();
            if kinds.iter().any(Option::is_some) {
                out.push((key, kinds));
            }
        }
        for m in obj.methods() {
            let key = format!("{obj_snake}_{}", m.name().to_snake_case());
            let kinds: Vec<_> = m
                .arguments()
                .iter()
                .map(|a| int64_kind(&a.as_type()))
                .collect();
            if kinds.iter().any(Option::is_some) {
                out.push((key, kinds));
            }
        }
    }

    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn collect_int64_return_kinds(ci: &ComponentInterface) -> Vec<(String, &'static str)> {
    let mut out = Vec::new();

    for f in ci.function_definitions() {
        if let Some(kind) = f.return_type().and_then(int64_kind) {
            out.push((f.name().to_string(), kind));
        }
    }

    for obj in ci.object_definitions() {
        let obj_snake = obj.name().to_snake_case();
        for m in obj.methods() {
            if let Some(kind) = m.return_type().and_then(int64_kind) {
                out.push((format!("{obj_snake}_{}", m.name().to_snake_case()), kind));
            }
        }
    }

    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn render_int64_arg_map_js_literal(ci: &ComponentInterface) -> String {
    let pairs = collect_int64_arg_kinds(ci);
    if pairs.is_empty() {
        return "{}".to_string();
    }
    let mut out = String::from("{\n");
    for (key, kinds) in pairs {
        let items = kinds
            .into_iter()
            .map(|kind| match kind {
                Some(kind) => format!("\"{kind}\""),
                None => "null".to_string(),
            })
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    \"{key}\": [{items}],\n"));
    }
    out.push('}');
    out
}

fn render_int64_return_map_js_literal(ci: &ComponentInterface) -> String {
    let pairs = collect_int64_return_kinds(ci);
    if pairs.is_empty() {
        return "{}".to_string();
    }
    let mut out = String::from("{\n");
    for (key, kind) in pairs {
        out.push_str(&format!("    \"{key}\": \"{kind}\",\n"));
    }
    out.push('}');
    out
}

fn render_renderer(namespace: &str, async_keys: &[String]) -> String {
    // Emit the generator-computed set of dispatch keys that are async.
    // Everything else must stay synchronous so that React render code
    // calling `core.greet(name)` does not receive a Promise.
    let async_set_literal = if async_keys.is_empty() {
        "new Set<string>()".to_string()
    } else {
        let joined = async_keys
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!("new Set<string>([{joined}])")
    };
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (electron renderer).\n\
         //\n\
         // Renderer-side facade for namespace `{namespace}`. Installs a\n\
         // backend proxy that forwards every call through the preload\n\
         // bridge, then re-exports the high-level API from\n\
         // `../common/api`. Applications import from this file directly.\n\
         //\n\
         // CRITICAL: sync Rust exports must stay synchronous on the\n\
         // renderer side. The generator bakes in the set of async\n\
         // dispatch keys below; everything outside that set is bound to\n\
         // `dispatchSync`, which preserves `common/api.ts`'s `__call<T>`\n\
         // contract (React render code must not see a Promise when it\n\
         // calls e.g. `core.greet(name)`).\n\
         \n\
         import {{ __installBackend, UniffiError }} from \"../common/runtime.ts\";\n\
         export * from \"../common/api.ts\";\n\
         \n\
         declare global {{\n\
             interface Window {{\n\
                 __uniffi__: {{\n\
                     namespace: string;\n\
                     dispatchSync: (msg: BridgeMessage) => BridgeResponse;\n\
                     dispatchAsync: (msg: BridgeMessage) => Promise<BridgeResponse>;\n\
                 }};\n\
             }}\n\
         }}\n\
         \n\
         type BridgeMessage =\n\
             | {{ kind: \"call\"; id: number; method: string; args: unknown[] }}\n\
             | {{ kind: \"drop\"; id: number }};\n\
         type BridgeResponse =\n\
             | {{ kind: \"ok\"; id: number; value: unknown }}\n\
             | {{ kind: \"err\"; id: number; error: {{ errorName: string; variant: string | null; data: unknown; message: string; stack?: string }} }};\n\
         \n\
         /** Generator-computed: dispatch keys flagged `async` in the IR. */\n\
         const ASYNC_METHODS: Set<string> = {async_set_literal};\n\
         \n\
         let nextCallId = 1;\n\
         \n\
         function unwrap(response: BridgeResponse): unknown {{\n\
             if (response.kind === \"ok\") return response.value;\n\
             throw new UniffiError({{\n\
                 errorName: response.error.errorName,\n\
                 variant: response.error.variant,\n\
                 data: response.error.data,\n\
                 message: response.error.message,\n\
                 stack: response.error.stack,\n\
             }});\n\
         }}\n\
         \n\
         function callSync(method: string, ...args: unknown[]): unknown {{\n\
             const id = nextCallId++;\n\
             return unwrap(\n\
                 window.__uniffi__.dispatchSync({{ kind: \"call\", id, method, args }}),\n\
             );\n\
         }}\n\
         \n\
         async function callAsync(method: string, ...args: unknown[]): Promise<unknown> {{\n\
             const id = nextCallId++;\n\
             return unwrap(\n\
                 await window.__uniffi__.dispatchAsync({{ kind: \"call\", id, method, args }}),\n\
             );\n\
         }}\n\
         \n\
         const backend = new Proxy({{}}, {{\n\
             get(_t, method: string) {{\n\
                 if (ASYNC_METHODS.has(method)) {{\n\
                     return (...args: unknown[]) => callAsync(method, ...args);\n\
                 }}\n\
                 return (...args: unknown[]) => callSync(method, ...args);\n\
             }},\n\
         }});\n\
         __installBackend(backend);\n"
    )
}
