use super::*;

fn def(kind: &str, name: &str, definition: &str) -> TypeDefLine {
    def_with_type_parameters(kind, name, definition, &[])
}

fn def_with_type_parameters(
    kind: &str,
    name: &str,
    definition: &str,
    type_parameters: &[&str],
) -> TypeDefLine {
    TypeDefLine {
        kind: kind.to_string(),
        name: name.to_string(),
        def: definition.to_string(),
        type_parameters: type_parameters
            .iter()
            .map(|parameter| (*parameter).to_string())
            .collect(),
    }
}

fn assert_component_stream_declarations_are_arkts_safe(
    exports: &FacadeExports,
    module: &FacadeComponentModule,
) {
    assert!(
        !module.declarations.contains("typeof "),
        "component declarations must not use ArkTS-incompatible type queries:\n{}",
        module.declarations
    );
    let owned = exports
        .owned_defs
        .iter()
        .find(|owned| owned.projection.namespace == module.namespace)
        .expect("component module must have an owned projection");
    let stream_projection = exports
        .component_stream_projection(&owned.projection, true)
        .expect("stream projection must render");
    for binding in stream_projection
        .values
        .iter()
        .filter(|binding| !binding.is_class)
    {
        let callable_type = stream_projection
            .explicit_value_declarations
            .get(&binding.public)
            .expect("every stream callable must carry its explicit source type");
        let source_alias = format!("export const {}: {} = ", binding.public, callable_type);
        assert_eq!(
            module.source.matches(&source_alias).count(),
            1,
            "stream callable `{}` must have exactly one explicitly typed source alias:\n{}",
            binding.public,
            module.source
        );
        let declaration = format!("export declare function {}(", binding.public);
        assert_eq!(
            module.declarations.matches(&declaration).count(),
            1,
            "stream callable `{}` must have exactly one explicit component declaration:\n{}",
            binding.public,
            module.declarations
        );
    }
}

fn assert_arkts_safe_component_class_projection(
    source: &str,
    declarations: &str,
    internal: &str,
    public: &str,
) {
    let imported = if internal == public {
        format!("  {internal},\n")
    } else {
        format!("  {internal} as {public},\n")
    };
    assert!(
        source.contains(&imported) && source.contains(&format!("export {{ {public} }};")),
        "component source must create and export a local ArkTS class binding `{public}`:\n{source}"
    );
    assert!(
        declarations.contains(&imported) && declarations.contains(&format!("export {{ {public} }};")),
        "component declaration must create and export a local ArkTS class binding `{public}`:\n{declarations}"
    );
    for surface in [source, declarations] {
        assert!(
            !surface.contains(&format!("export const {public} ="))
                && !surface.contains(&format!("export type {public} =")),
            "class `{public}` must not be modeled as a const/type alias:\n{surface}"
        );
    }
}

#[test]
fn package_entry_reexports_raw_types_without_duplicating_value_classes() {
    let defs = vec![
        def("interface", "RecordPayload", "value: number"),
        def("string_enum", "Status", "Ready = 'Ready'"),
        def("struct", "Worker", "constructor();"),
        def("fn", "run", "function run(value: RecordPayload): Status"),
    ];
    let exports = FacadeExports::from_type_defs(&defs).unwrap();

    let native = exports.render_native_facade("libfixture.so");
    assert!(
        native.contains("import type {\n  RecordPayload,\n  Status,\n} from \"libfixture.so\";\n")
    );
    assert!(
        native.contains("export type {\n  RecordPayload,\n  Status,\n} from \"libfixture.so\";\n")
    );

    let package = exports.render_package_index();
    assert!(package.starts_with(
        "// AUTOGENERATED by UniFFI (Harmony package entry).\n\
         export {\n  Worker,\n  run,\n} from \"./src/main/ets/native-facade\";\n"
    ));
    assert!(package.ends_with(
        "export type {\n  RecordPayload,\n  Status,\n} from \"./src/main/ets/native-facade\";\n"
    ));
    assert!(!package.contains("export type {\n  RecordPayload,\n  Status,\n  Worker,"));
}

#[test]
fn package_entry_reexports_public_harmony_stream_interfaces() {
    let streams = HarmonyStreamFacade {
        contracts: vec![HarmonyFacadeContract {
            facade_contract_schema_version: FACADE_CONTRACT_SCHEMA_VERSION,
            component: "fixture".to_string(),
            namespace: "fixture".to_string(),
            native_export_prefix: uniffi_bindgen::interface::native_export_prefix_for_component(
                "fixture",
            ),
            output_streams: vec![HarmonyOutputStreamContract {
                function: "items".to_string(),
                next_function: "itemsStreamNext".to_string(),
                cancel_function: "itemsStreamCancel".to_string(),
                stream_factory: "itemsStream".to_string(),
                pull_class: "ItemsPullStream".to_string(),
                step_type: "OutputStep".to_string(),
                item_type: HarmonyTypeDescriptor::Number,
                error_type: HarmonyTypeDescriptor::String,
                arguments: Vec::new(),
            }],
            input_streams: Vec::new(),
        }],
        native_types: vec!["OutputStep".to_string()],
        package_hidden_next_envelopes: Vec::new(),
        host_composite_identity: String::new(),
        component_identities: Vec::new(),
        owner_native_export_prefixes: BTreeMap::from([(
            "fixture".to_string(),
            uniffi_bindgen::interface::native_export_prefix_for_component("fixture"),
        )]),
        canonical_raw_stream_names: false,
    };
    let exports = FacadeExports {
        callables: vec!["items".to_string()],
        callable_types: BTreeMap::from([("items".to_string(), "() => bigint".to_string())]),
        classes: Vec::new(),
        streams,
        owned_defs: Vec::new(),
    };

    assert_eq!(
        exports.type_exports(),
        vec!["UniFfiStream", "UniFfiStreamResult"]
    );
    let package = exports.render_package_index();
    assert!(package.contains("export {\n  UniFfiStreamFailure,\n"));
    for name in ["UniFfiStream", "UniFfiStreamResult"] {
        assert!(
            package.contains(&format!("  {name},\n")),
            "missing package-root type export for {name}:\n{package}"
        );
    }
    for raw in [
        "items",
        "itemsStreamNext",
        "itemsStreamCancel",
        "OutputStep",
    ] {
        assert!(
            !package.contains(&format!("  {raw},\n")),
            "package root must hide output raw `{raw}`:\n{package}"
        );
    }
    assert!(package.contains("  itemsStream,\n"));
    assert!(!package.contains("ItemsPullStream"));
}

#[test]
fn no_stream_package_uses_only_raw_type_exports() {
    let exports =
        FacadeExports::from_type_defs(&[def("interface", "RecordPayload", "value: number")])
            .unwrap();
    assert_eq!(exports.type_exports(), vec!["RecordPayload"]);
    let package = exports.render_package_index();
    assert!(!package.contains("UniFfiStream"));
    assert_eq!(package.matches("export type {").count(), 1);
}

#[test]
fn single_owned_component_projects_public_bindings_through_its_namespace() {
    let component = "fixture-core";
    let native_export_prefix =
        uniffi_bindgen::interface::native_export_prefix_for_component(component);
    let identity = HostFacadeComponentIdentity {
        component: component.to_string(),
        namespace: "fixture".to_string(),
        native_export_prefix: native_export_prefix.clone(),
        contract_file: "fixture-core.ohos-facade.json".to_string(),
        contract_sha256: "a".repeat(64),
        identity_export: bridge_identity_export(&native_export_prefix, &"a".repeat(64)),
    };
    let raw_payload = format!("{native_export_prefix}_Payload");
    let raw_ping = format!("{native_export_prefix}_ping");
    let raw_worker = format!("{native_export_prefix}_Worker");
    let owned = OwnedFacadeTypeDefs::new(
        &identity,
        vec![
            def("interface", &raw_payload, "value: string"),
            def("struct", &raw_worker, "constructor();"),
            def(
                "fn",
                &raw_ping,
                &format!("function {raw_ping}(): {raw_payload}"),
            ),
        ],
    )
    .unwrap();
    let exports =
        FacadeExports::from_owned_type_defs_and_contracts(vec![owned], Vec::new()).unwrap();
    let index = exports.render_package_index();
    let declarations = render_harmony_declaration_surfaces(&[], &exports).package_public;
    let modules = exports.component_modules().unwrap();
    let module = modules
        .iter()
        .find(|module| module.namespace == "fixture")
        .unwrap();

    assert_component_stream_declarations_are_arkts_safe(&exports, module);

    assert!(
        module
            .source
            .contains(&format!("export const ping: () => Payload = {raw_ping};")),
        "ordinary callable aliases must also carry an explicit public type:\n{}",
        module.source
    );

    for surface in [&index, &declarations] {
        assert!(
            surface.contains("import * as fixture from \"./src/main/ets/components/fixture\";"),
            "{surface}"
        );
        assert!(surface.contains("export {\n  fixture,\n};"), "{surface}");
        assert!(
            !surface.contains(&raw_ping) && !surface.contains(&raw_payload),
            "single-component package root must not leak flat raw bindings:\n{surface}"
        );
    }
    for surface in [&module.source, &module.declarations] {
        assert!(surface.contains(&raw_ping), "{surface}");
        assert!(surface.contains(&raw_payload), "{surface}");
        assert!(surface.contains(&raw_worker), "{surface}");
        assert!(surface.contains("ping"), "{surface}");
        assert!(surface.contains("Payload"), "{surface}");
        assert!(surface.contains("Worker"), "{surface}");
    }
    assert_arkts_safe_component_class_projection(
        &module.source,
        &module.declarations,
        &raw_worker,
        "Worker",
    );
}

#[test]
fn composite_stream_components_project_internal_helpers_and_cross_owner_types() {
    let identity = |component: &str, namespace: &str| {
        let native_export_prefix =
            uniffi_bindgen::interface::native_export_prefix_for_component(component);
        HostFacadeComponentIdentity {
            component: component.to_string(),
            namespace: namespace.to_string(),
            native_export_prefix: native_export_prefix.clone(),
            contract_file: format!("{component}.ohos-facade.json"),
            contract_sha256: "b".repeat(64),
            identity_export: bridge_identity_export(&native_export_prefix, &"b".repeat(64)),
        }
    };
    let alpha_identity = identity("alpha-core", "alpha");
    let beta_identity = identity("beta-core", "beta");
    let alpha_prefix = &alpha_identity.native_export_prefix;
    let beta_prefix = &beta_identity.native_export_prefix;
    let alpha_shared = format!("{alpha_prefix}_Shared");
    let beta_output =
        uniffi_bindgen_javascript::flavors::napi::ohos_raw_output_stream_names_for_prefix(
            beta_prefix,
            "events",
        );
    let input_suffix = "SharedPayload";
    let beta_input_stream =
        uniffi_bindgen_javascript::flavors::napi::ohos_raw_input_stream_type_for_prefix(
            beta_prefix,
        );
    let beta_input_next =
        uniffi_bindgen_javascript::flavors::napi::ohos_raw_input_next_type_for_prefix(
            beta_prefix,
            input_suffix,
        );
    let alpha_owned = OwnedFacadeTypeDefs::new(
        &alpha_identity,
        vec![def("interface", &alpha_shared, "value: string")],
    )
    .unwrap();
    let beta_owned = OwnedFacadeTypeDefs::new(
        &beta_identity,
        vec![
            def_with_type_parameters(
                "interface",
                &beta_input_stream,
                "handle: number\nnext(error: Error | null, handle: number): Promise<T>\ncancel(error: Error | null, handle: number): void",
                &["T"],
            ),
            def(
                "interface",
                &beta_input_next,
                &format!(
                    "ok: boolean\ndone?: boolean\nvalue?: {alpha_shared}\nerror?: string"
                ),
            ),
            def(
                "interface",
                &beta_output.step_type,
                &format!(
                    "kind: string\nvalue?: {alpha_shared}\nerror?: string"
                ),
            ),
            def(
                "fn",
                &beta_output.function,
                &format!(
                    "function {}(input: {}<{}>): bigint",
                    beta_output.function, beta_input_stream, beta_input_next
                ),
            ),
            def(
                "fn",
                &beta_output.next_function,
                &format!(
                    "function {}(handle: bigint): Promise<{}>",
                    beta_output.next_function, beta_output.step_type
                ),
            ),
            def(
                "fn",
                &beta_output.cancel_function,
                &format!("function {}(handle: bigint): void", beta_output.cancel_function),
            ),
        ],
    )
    .unwrap();
    let alpha_contract = HarmonyFacadeContract {
        facade_contract_schema_version: FACADE_CONTRACT_SCHEMA_VERSION,
        component: alpha_identity.component.clone(),
        namespace: alpha_identity.namespace.clone(),
        native_export_prefix: alpha_prefix.clone(),
        output_streams: Vec::new(),
        input_streams: Vec::new(),
    };
    let shared_owner = HarmonyNamedTypeOwner {
        component: alpha_identity.component.clone(),
        namespace: alpha_identity.namespace.clone(),
    };
    let shared_type = || HarmonyTypeDescriptor::Named {
        owner: shared_owner.clone(),
        name: "Shared".to_string(),
    };
    let beta_contract = HarmonyFacadeContract {
        facade_contract_schema_version: FACADE_CONTRACT_SCHEMA_VERSION,
        component: beta_identity.component.clone(),
        namespace: beta_identity.namespace.clone(),
        native_export_prefix: beta_prefix.clone(),
        output_streams: vec![HarmonyOutputStreamContract {
            function: beta_output.function.clone(),
            next_function: beta_output.next_function.clone(),
            cancel_function: beta_output.cancel_function.clone(),
            stream_factory: "eventsStream".to_string(),
            pull_class: "EventsPullStream".to_string(),
            step_type: beta_output.step_type.clone(),
            item_type: shared_type(),
            error_type: HarmonyTypeDescriptor::String,
            arguments: vec![HarmonyFacadeArgument {
                name: "input".to_string(),
                r#type: HarmonyTypeDescriptor::InputSource {
                    suffix: input_suffix.to_string(),
                    next_type: beta_input_next.clone(),
                },
            }],
        }],
        input_streams: vec![HarmonyInputStreamContract {
            suffix: input_suffix.to_string(),
            canonical: "shared-payload".to_string(),
            fingerprint: "c".repeat(64),
            item_type: shared_type(),
            error_type: HarmonyTypeDescriptor::String,
            next_type: beta_input_next.clone(),
            writer_class: "SharedPayloadInputWriter".to_string(),
            source_class: "SharedPayloadInputSource".to_string(),
            channel_class: "SharedPayloadInputChannel".to_string(),
            factory: "createSharedPayloadInputChannel".to_string(),
        }],
    };
    let exports = FacadeExports::from_owned_type_defs_and_contracts(
        vec![alpha_owned, beta_owned],
        vec![alpha_contract, beta_contract],
    )
    .unwrap();
    let native = exports.render_native_facade("libfixture.so");
    let modules = exports.component_modules().unwrap();
    let beta = modules
        .iter()
        .find(|module| module.namespace == "beta")
        .unwrap();
    let root = exports.render_package_index();
    let declarations = render_harmony_declaration_surfaces(&[], &exports).package_public;

    for module in &modules {
        assert_component_stream_declarations_are_arkts_safe(&exports, module);
    }

    for internal in [
        "__uniffi_beta_eventsStream",
        "__uniffi_beta_EventsPullStream",
        "__uniffi_beta_SharedPayloadInputWriter",
        "__uniffi_beta_SharedPayloadInputSource",
        "__uniffi_beta_SharedPayloadInputChannel",
        "__uniffi_beta_createSharedPayloadInputChannel",
    ] {
        assert!(
            native.contains(internal),
            "missing native stream helper `{internal}`:\n{native}"
        );
        assert!(
            beta.source.contains(internal),
            "missing component alias `{internal}`:\n{}",
            beta.source
        );
    }
    for public in ["eventsStream", "createSharedPayloadInputChannel"] {
        assert!(
            beta.source.contains(&format!("export const {public}: ")),
            "missing explicitly typed component public stream alias `{public}`:\n{}",
            beta.source
        );
    }
    for (internal, public) in [
        ("__uniffi_beta_EventsPullStream", "EventsPullStream"),
        (
            "__uniffi_beta_SharedPayloadInputWriter",
            "SharedPayloadInputWriter",
        ),
        (
            "__uniffi_beta_SharedPayloadInputSource",
            "SharedPayloadInputSource",
        ),
        (
            "__uniffi_beta_SharedPayloadInputChannel",
            "SharedPayloadInputChannel",
        ),
        ("UniFfiInputFailure", "UniFfiInputFailure"),
        ("UniFfiStreamFailure", "UniFfiStreamFailure"),
    ] {
        assert_arkts_safe_component_class_projection(
            &beta.source,
            &beta.declarations,
            internal,
            public,
        );
    }
    for surface in [&beta.source, &beta.declarations] {
        assert!(
            surface.contains(&format!(
                "export type UniffiInputStream<T> = {beta_input_stream}<T>;"
            )),
            "generic raw type parameters must be preserved exactly:\n{surface}"
        );
    }
    assert!(
        beta.declarations.contains(
            "export declare function eventsStream(input: SharedPayloadInputSource): UniFfiStream<alpha.Shared>;"
        ),
        "cross-owner stream declaration must use the visible owner namespace:\n{}",
        beta.declarations
    );
    assert!(
        !beta.declarations.contains(&alpha_shared),
        "component declaration leaked an invisible raw owner type:\n{}",
        beta.declarations
    );
    assert!(beta
        .declarations
        .contains("import type * as alpha from \"./alpha\";"));
    assert!(root.contains("export {\n  alpha,\n  beta,\n};"), "{root}");
    assert!(
        declarations.contains("import * as beta from \"./src/main/ets/components/beta\""),
        "{declarations}"
    );
}

#[test]
fn single_owned_stream_component_keeps_a_namespace_only_pull_surface() {
    let component = "fixture-core";
    let native_export_prefix =
        uniffi_bindgen::interface::native_export_prefix_for_component(component);
    let identity = HostFacadeComponentIdentity {
        component: component.to_string(),
        namespace: "fixture".to_string(),
        native_export_prefix: native_export_prefix.clone(),
        contract_file: "fixture-core.ohos-facade.json".to_string(),
        contract_sha256: "d".repeat(64),
        identity_export: bridge_identity_export(&native_export_prefix, &"d".repeat(64)),
    };
    let payload = format!("{native_export_prefix}_Payload");
    let raw_output =
        uniffi_bindgen_javascript::flavors::napi::ohos_raw_output_stream_names_for_prefix(
            &native_export_prefix,
            "events",
        );
    let owned = OwnedFacadeTypeDefs::new(
        &identity,
        vec![
            def("interface", &payload, "value: string"),
            def(
                "interface",
                &raw_output.step_type,
                &format!("kind: string\nvalue?: {payload}\nerror?: string"),
            ),
            def(
                "fn",
                &raw_output.function,
                &format!("function {}(): bigint", raw_output.function),
            ),
            def(
                "fn",
                &raw_output.next_function,
                &format!(
                    "function {}(handle: bigint): Promise<{}>",
                    raw_output.next_function, raw_output.step_type
                ),
            ),
            def(
                "fn",
                &raw_output.cancel_function,
                &format!(
                    "function {}(handle: bigint): void",
                    raw_output.cancel_function
                ),
            ),
        ],
    )
    .unwrap();
    let contract = HarmonyFacadeContract {
        facade_contract_schema_version: FACADE_CONTRACT_SCHEMA_VERSION,
        component: component.to_string(),
        namespace: "fixture".to_string(),
        native_export_prefix: native_export_prefix.clone(),
        output_streams: vec![HarmonyOutputStreamContract {
            function: raw_output.function.clone(),
            next_function: raw_output.next_function.clone(),
            cancel_function: raw_output.cancel_function.clone(),
            stream_factory: "eventsStream".to_string(),
            pull_class: "EventsPullStream".to_string(),
            step_type: raw_output.step_type.clone(),
            item_type: HarmonyTypeDescriptor::Named {
                owner: HarmonyNamedTypeOwner {
                    component: component.to_string(),
                    namespace: "fixture".to_string(),
                },
                name: "Payload".to_string(),
            },
            error_type: HarmonyTypeDescriptor::String,
            arguments: Vec::new(),
        }],
        input_streams: Vec::new(),
    };
    let exports =
        FacadeExports::from_owned_type_defs_and_contracts(vec![owned], vec![contract]).unwrap();
    let native = exports.render_native_facade("libfixture.so");
    let index = exports.render_package_index();
    let declarations = render_harmony_declaration_surfaces(&[], &exports).package_public;
    let modules = exports.component_modules().unwrap();
    let module = modules
        .iter()
        .find(|module| module.namespace == "fixture")
        .unwrap();

    assert_component_stream_declarations_are_arkts_safe(&exports, module);

    assert!(
        native.contains(&format!("UniFfiStream<{payload}>")),
        "{native}"
    );
    assert!(
        native.contains("export class EventsPullStream extends __UniFfiPullStream"),
        "owned component Pull implementation must be exported for its namespace facade:\n{native}"
    );
    for surface in [&index, &declarations] {
        assert!(
            surface.contains("import * as fixture from \"./src/main/ets/components/fixture\";"),
            "{surface}"
        );
        assert!(surface.contains("export {\n  fixture,\n};"), "{surface}");
        for private in [
            raw_output.function.as_str(),
            raw_output.next_function.as_str(),
            raw_output.cancel_function.as_str(),
            raw_output.step_type.as_str(),
            "eventsStream",
            "EventsPullStream",
            "Payload",
        ] {
            assert!(
                !surface.contains(private),
                "single-component root leaked `{private}` instead of only the namespace:\n{surface}"
            );
        }
    }
    for surface in [&module.source, &module.declarations] {
        assert!(surface.contains("eventsStream"), "{surface}");
        assert!(surface.contains("EventsPullStream"), "{surface}");
        assert!(surface.contains("Payload"), "{surface}");
        for private in [
            raw_output.function.as_str(),
            raw_output.next_function.as_str(),
            raw_output.cancel_function.as_str(),
            raw_output.step_type.as_str(),
        ] {
            assert!(
                !surface.contains(private),
                "component public pull facade leaked raw output `{private}`:\n{surface}"
            );
        }
    }
    assert_arkts_safe_component_class_projection(
        &module.source,
        &module.declarations,
        "EventsPullStream",
        "EventsPullStream",
    );
}
