/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

use anyhow::{bail, Context, Result};
use camino::{Utf8Path, Utf8PathBuf};
use cargo_metadata::{BuildScript, Message, MetadataCommand, Package};
use flate2::write::GzEncoder;
use flate2::Compression;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::env;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};
use tar::Builder;

const TYPE_ROOT: &str = "uniffi-ohos";
const TYPE_HEADER: &str = "/* auto-generated by UniFFI OHOS builder */\n/* eslint-disable */\n\n";
const DEFAULT_OH_PACKAGE_VERSION: &str = "0.0.1";

pub(crate) struct BuildOptions {
    pub cargo_bin: String,
    pub manifest_path: Utf8PathBuf,
    pub dist_dir: Utf8PathBuf,
    pub package_name: Option<String>,
    pub har_out: Option<Utf8PathBuf>,
    pub no_har: bool,
    pub arches: Vec<String>,
    pub target_dir: Option<Utf8PathBuf>,
    pub release: bool,
    pub cargo_args: Vec<String>,
    pub copy_static: bool,
    pub skip_libs: bool,
    pub dts_cache: bool,
    pub skip_check: bool,
    pub zigbuild: bool,
    pub bisheng: bool,
    pub package: Option<String>,
    pub skip_napi_check: bool,
    pub soname: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Arch {
    Arm64,
    Arm32,
    X86_64,
    LoongArch64,
}

impl Arch {
    fn parse(input: &str) -> Result<Self> {
        match input.to_ascii_lowercase().as_str() {
            "aarch" | "arm64" | "aarch64-linux-ohos" | "aarch64-unknown-linux-ohos" => {
                Ok(Self::Arm64)
            }
            "arm" | "arm32" | "arm-linux-ohos" | "armv7-unknown-linux-ohos" => {
                Ok(Self::Arm32)
            }
            "x86_64" | "x64" | "x86_64-linux-ohos" | "x86_64-unknown-linux-ohos" => {
                Ok(Self::X86_64)
            }
            "loongarch64" | "loongarch64-linux-ohos" | "loongarch64-unknown-linux-ohos" => {
                Ok(Self::LoongArch64)
            }
            _ => bail!(
                "unsupported OHOS arch `{input}`; expected aarch/arm64, arm/arm32, x86_64/x64, or loongarch64"
            ),
        }
    }

    fn dist_dir(self) -> &'static str {
        match self {
            Self::Arm64 => "arm64-v8a",
            Self::Arm32 => "armeabi-v7a",
            Self::X86_64 => "x86_64",
            Self::LoongArch64 => "loongarch64",
        }
    }

    fn c_target(self) -> &'static str {
        match self {
            Self::Arm64 => "aarch64-linux-ohos",
            Self::Arm32 => "arm-linux-ohos",
            Self::X86_64 => "x86_64-linux-ohos",
            Self::LoongArch64 => "loongarch64-linux-ohos",
        }
    }

    fn rust_target(self) -> &'static str {
        match self {
            Self::Arm64 => "aarch64-unknown-linux-ohos",
            Self::Arm32 => "armv7-unknown-linux-ohos",
            Self::X86_64 => "x86_64-unknown-linux-ohos",
            Self::LoongArch64 => "loongarch64-unknown-linux-ohos",
        }
    }

    fn rust_link_target(self) -> &'static str {
        match self {
            Self::Arm64 => "AARCH64_UNKNOWN_LINUX_OHOS",
            Self::Arm32 => "ARMV7_UNKNOWN_LINUX_OHOS",
            Self::X86_64 => "X86_64_UNKNOWN_LINUX_OHOS",
            Self::LoongArch64 => "LOONGARCH64_UNKNOWN_LINUX_OHOS",
        }
    }
}

#[derive(Debug, Clone)]
struct HostPackage {
    name: String,
    version: String,
    manifest_path: Utf8PathBuf,
    lib_target_name: String,
}

#[derive(Debug)]
struct HostPlan {
    target_directory: Utf8PathBuf,
    packages: Vec<HostPackage>,
    explicit_package_arg: bool,
}

#[derive(Debug)]
struct ToolchainPaths {
    ranlib: String,
    ar: String,
    cc: String,
    cxx: String,
    llvm_as: String,
    ld: String,
    strip: String,
    objdump: String,
    objcopy: String,
    nm: String,
    bin_dir: String,
    lib_dir: String,
}

#[derive(Debug)]
struct BuiltArtifacts {
    paths: BTreeSet<Utf8PathBuf>,
}

pub(crate) fn build(options: BuildOptions) -> Result<()> {
    let ohos_ndk = env::var("OHOS_NDK_HOME").context(
        "OHOS_NDK_HOME is required for the built-in OHOS builder; configure the OHOS SDK/NDK before building Harmony artifacts",
    )?;
    if !Path::new(&ohos_ndk).exists() {
        bail!("OHOS_NDK_HOME does not exist: {ohos_ndk}");
    }

    let arches = parse_arches(&options.arches)?;
    let manifest_path = options
        .manifest_path
        .canonicalize_utf8()
        .unwrap_or_else(|_| options.manifest_path.clone());
    let manifest_dir = manifest_path
        .parent()
        .with_context(|| format!("OHOS manifest has no parent: {manifest_path}"))?;
    let plan = host_plan(&options.cargo_bin, &manifest_path, &options)?;
    if plan.packages.len() > 1 {
        if let Some(package_name) = &options.package_name {
            bail!(
                "--package-name `{package_name}` is ambiguous when multiple OHOS packages are selected; pass --package <name> to build a single package"
            );
        }
        if let Some(har_out) = &options.har_out {
            bail!(
                "--har-out `{har_out}` is ambiguous when multiple OHOS packages are selected; pass --package <name> to build a single package"
            );
        }
    }
    let target_dir = options
        .target_dir
        .clone()
        .map(|p| {
            if p.is_absolute() {
                p
            } else {
                manifest_dir.join(p)
            }
        })
        .unwrap_or_else(|| plan.target_directory.clone());
    std::fs::create_dir_all(&options.dist_dir)
        .with_context(|| format!("creating OHOS dist dir {}", options.dist_dir))?;

    for package in &plan.packages {
        let package_dist_dir = package_dist_dir(&options.dist_dir, package, plan.packages.len());
        std::fs::create_dir_all(&package_dist_dir)
            .with_context(|| format!("creating OHOS package dist dir {package_dist_dir}"))?;
        let type_dir = package_type_dir(&target_dir, package, options.dts_cache)?;
        for arch in &arches {
            build_arch(
                &options,
                package,
                &ohos_ndk,
                &target_dir,
                &package_dist_dir,
                &type_dir,
                *arch,
                plan.explicit_package_arg,
            )
            .with_context(|| {
                format!(
                    "building OHOS package {} arch {}",
                    package.name,
                    arch.dist_dir()
                )
            })?;
        }
        emit_index_d_ts(&package_dist_dir, &type_dir)?;
        if !options.no_har {
            package_har(&options, package, &package_dist_dir, plan.packages.len())?;
        }
    }
    Ok(())
}

fn parse_arches(arches: &[String]) -> Result<Vec<Arch>> {
    if arches.is_empty() {
        Ok(vec![Arch::Arm64, Arch::X86_64])
    } else {
        arches.iter().map(|arch| Arch::parse(arch)).collect()
    }
}

fn host_plan(
    cargo_bin: &str,
    manifest_path: &Utf8Path,
    options: &BuildOptions,
) -> Result<HostPlan> {
    let metadata = MetadataCommand::new()
        .cargo_path(cargo_bin)
        .manifest_path(manifest_path.as_std_path())
        .no_deps()
        .exec()
        .with_context(|| format!("running cargo metadata for OHOS host crate {manifest_path}"))?;

    let explicit_package = resolve_package_filter(options.package.as_deref(), &options.cargo_args)?;
    let explicit_package_arg = explicit_package.is_some();
    let mut packages = Vec::new();
    let workspace_members = metadata
        .workspace_members
        .iter()
        .filter_map(|member_id| metadata.packages.iter().find(|p| &p.id == member_id))
        .collect::<Vec<_>>();
    let candidates = if workspace_members.is_empty() {
        metadata.packages.iter().collect::<Vec<_>>()
    } else {
        workspace_members
    };

    for package in candidates {
        if let Some(filter) = &explicit_package {
            let package_spec = format!("{}@{}", package.name, package.version);
            if &package.name != filter && &package_spec != filter {
                continue;
            }
        }
        if !options.skip_napi_check && !has_napi_ohos_dependency(package) {
            continue;
        }
        packages.push(host_package(package)?);
    }

    if packages.is_empty() {
        if let Some(filter) = explicit_package {
            bail!("no OHOS-capable package matched `{filter}`");
        }
        bail!(
            "no OHOS-capable package found; add napi-derive-ohos or pass --skip-napi-check if this is intentional"
        );
    }

    if !options.skip_check {
        check_napi_versions(cargo_bin, manifest_path)?;
    }

    Ok(HostPlan {
        target_directory: Utf8PathBuf::from_path_buf(
            metadata.target_directory.clone().into_std_path_buf(),
        )
        .map_err(|p| anyhow::anyhow!("cargo metadata target dir is not utf8: {}", p.display()))?,
        packages,
        explicit_package_arg,
    })
}

fn has_napi_ohos_dependency(package: &Package) -> bool {
    package
        .dependencies
        .iter()
        .any(|dep| dep.name == "napi-derive-ohos")
}

fn host_package(package: &Package) -> Result<HostPackage> {
    let lib_target = package
        .targets
        .iter()
        .find(|target| target.kind.iter().any(|kind| kind.to_string() == "cdylib"))
        .or_else(|| {
            package
                .targets
                .iter()
                .find(|target| target.kind.iter().any(|kind| kind.to_string() == "lib"))
        })
        .with_context(|| format!("OHOS package {} has no lib target", package.name))?;
    let manifest_path =
        Utf8PathBuf::from_path_buf(package.manifest_path.clone().into_std_path_buf())
            .map_err(|p| anyhow::anyhow!("package manifest path is not utf8: {}", p.display()))?;
    Ok(HostPackage {
        name: package.name.to_string(),
        version: package.version.to_string(),
        manifest_path,
        lib_target_name: lib_target.name.clone(),
    })
}

fn check_napi_versions(cargo_bin: &str, manifest_path: &Utf8Path) -> Result<()> {
    let metadata = MetadataCommand::new()
        .cargo_path(cargo_bin)
        .manifest_path(manifest_path.as_std_path())
        .exec()
        .with_context(|| {
            format!("running full cargo metadata for OHOS version checks: {manifest_path}")
        })?;
    for name in ["napi-ohos", "napi-derive-ohos"] {
        let package = metadata
            .packages
            .iter()
            .find(|package| package.name.as_str() == name)
            .with_context(|| {
                format!("failed to find {name}; pass --skip-check to bypass this check")
            })?;
        let min = cargo_metadata::semver::Version::parse("1.1.0")?;
        if package.version < min {
            bail!(
                "{name} must be >= 1.1.0 for OHOS builds; found {}. Pass --skip-check to bypass this check",
                package.version
            );
        }
    }
    Ok(())
}

fn package_arg_from_cargo_args(args: &[String]) -> Option<String> {
    args.iter()
        .position(|arg| arg == "-p" || arg == "--package")
        .and_then(|idx| args.get(idx + 1).cloned())
        .or_else(|| {
            args.iter()
                .find_map(|arg| {
                    arg.strip_prefix("-p=")
                        .or_else(|| arg.strip_prefix("--package="))
                })
                .map(str::to_string)
        })
}

fn resolve_package_filter(
    option_package: Option<&str>,
    cargo_args: &[String],
) -> Result<Option<String>> {
    let cargo_package = package_arg_from_cargo_args(cargo_args);
    match (option_package, cargo_package) {
        (Some(option_package), Some(cargo_package)) if option_package != cargo_package => {
            bail!(
                "conflicting OHOS package filters: --package {option_package} and trailing cargo args package {cargo_package}"
            )
        }
        (Some(option_package), _) => Ok(Some(option_package.to_string())),
        (_, Some(cargo_package)) => Ok(Some(cargo_package)),
        _ => Ok(None),
    }
}

fn has_package_arg(args: &[String]) -> bool {
    package_arg_from_cargo_args(args).is_some()
}

fn package_type_dir(
    target_dir: &Utf8Path,
    package: &HostPackage,
    dts_cache: bool,
) -> Result<Utf8PathBuf> {
    let mut base = target_dir.join(TYPE_ROOT).join(format!(
        "{}-{}",
        package.name,
        short_manifest_hash(&package.manifest_path)
    ));
    if !dts_cache {
        if base.exists() {
            std::fs::remove_dir_all(&base)
                .with_context(|| format!("removing stale OHOS type dir {base}"))?;
        }
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_millis())
            .unwrap_or_default();
        base = Utf8PathBuf::from(format!("{base}_{stamp}"));
    }
    std::fs::create_dir_all(&base).with_context(|| format!("creating OHOS type dir {base}"))?;
    Ok(base)
}

fn package_dist_dir(root: &Utf8Path, package: &HostPackage, package_count: usize) -> Utf8PathBuf {
    if package_count <= 1 {
        root.to_path_buf()
    } else {
        root.join(&package.name)
    }
}

fn package_har(
    options: &BuildOptions,
    package: &HostPackage,
    package_dist_dir: &Utf8Path,
    package_count: usize,
) -> Result<()> {
    let artifact_root = options
        .dist_dir
        .parent()
        .unwrap_or(options.dist_dir.as_path())
        .to_path_buf();
    let package_dir = package_stage_dir(&artifact_root, package, package_count);
    stage_har_package(
        package_dist_dir,
        &package_dir,
        &package.lib_target_name,
        &resolve_oh_package_name(options.package_name.as_deref(), package)?,
        resolve_oh_package_version(package),
        options.skip_libs,
    )?;
    let har_out = resolve_har_out(
        options.har_out.as_deref(),
        &artifact_root,
        package,
        package_count,
    );
    generate_har_archive(&har_out, &package_dir)?;
    Ok(())
}

fn resolve_oh_package_name(override_name: Option<&str>, package: &HostPackage) -> Result<String> {
    let name = override_name.unwrap_or(&package.name);
    if name.trim().is_empty() {
        bail!("OHOS package name must not be empty");
    }
    Ok(name.to_string())
}

fn resolve_oh_package_version(package: &HostPackage) -> String {
    if package.version.trim().is_empty() {
        DEFAULT_OH_PACKAGE_VERSION.to_string()
    } else {
        package.version.clone()
    }
}

fn resolve_har_out(
    override_path: Option<&Utf8Path>,
    artifact_root: &Utf8Path,
    package: &HostPackage,
    package_count: usize,
) -> Utf8PathBuf {
    if let Some(path) = override_path {
        return path.to_path_buf();
    }
    if package_count <= 1 {
        artifact_root.join(format!("{}.har", package.name))
    } else {
        artifact_root.join(format!("{}-{}.har", package.name, package.lib_target_name))
    }
}

fn package_stage_dir(
    artifact_root: &Utf8Path,
    package: &HostPackage,
    package_count: usize,
) -> Utf8PathBuf {
    let base = artifact_root.join("package");
    if package_count <= 1 {
        base
    } else {
        base.join(&package.name)
    }
}

fn stage_har_package(
    package_dist_dir: &Utf8Path,
    package_dir: &Utf8Path,
    lib_target_name: &str,
    package_name: &str,
    version: String,
    skip_libs: bool,
) -> Result<()> {
    if package_dir.exists() {
        std::fs::remove_dir_all(package_dir)
            .with_context(|| format!("removing stale OHOS package staging dir {package_dir}"))?;
    }
    std::fs::create_dir_all(package_dir.join("src/main"))
        .with_context(|| format!("creating OHOS package staging src/main in {package_dir}"))?;
    std::fs::write(
        package_dir.join("oh-package.json5"),
        render_oh_package_json5(package_name, &version),
    )
    .with_context(|| format!("writing OHOS package metadata in {package_dir}"))?;
    std::fs::write(
        package_dir.join("index.ets"),
        render_index_ets(lib_target_name),
    )
    .with_context(|| format!("writing OHOS package index.ets in {package_dir}"))?;
    std::fs::write(
        package_dir.join("src/main/module.json5"),
        render_module_json5(package_name),
    )
    .with_context(|| format!("writing OHOS package module.json5 in {package_dir}"))?;
    copy_dist_to_package_libs(package_dist_dir, &package_dir.join("libs"), skip_libs)?;
    Ok(())
}

fn render_oh_package_json5(package_name: &str, version: &str) -> String {
    format!(
        "{{\n  \"license\": \"MIT\",\n  \"author\": \"\",\n  \"name\": \"{package_name}\",\n  \"description\": \"\",\n  \"main\": \"index.ets\",\n  \"version\": \"{version}\",\n  \"types\": \"libs/index.d.ts\",\n  \"dependencies\": {{}}\n}}\n"
    )
}

fn render_index_ets(lib_target_name: &str) -> String {
    let native = native_lib_filename(lib_target_name);
    format!(
        "import * as api from \"{native}\";\n\nexport * from \"{native}\";\nexport default api;\n"
    )
}

fn render_module_json5(package_name: &str) -> String {
    format!(
        "{{\n  \"module\": {{\n    \"name\": \"{package_name}\",\n    \"type\": \"har\",\n    \"deviceTypes\": [\"default\", \"tablet\", \"2in1\"]\n  }}\n}}\n"
    )
}

fn copy_dist_to_package_libs(
    package_dist_dir: &Utf8Path,
    libs_dir: &Utf8Path,
    skip_libs: bool,
) -> Result<()> {
    if !package_dist_dir.exists() {
        bail!("OHOS dist dir does not exist: {package_dist_dir}");
    }
    if libs_dir.exists() {
        std::fs::remove_dir_all(libs_dir)
            .with_context(|| format!("removing stale OHOS package libs dir {libs_dir}"))?;
    }
    std::fs::create_dir_all(libs_dir)
        .with_context(|| format!("creating OHOS package libs dir {libs_dir}"))?;
    let dts_src = package_dist_dir.join("index.d.ts");
    if !dts_src.exists() {
        bail!("OHOS dist missing index.d.ts: {dts_src}");
    }
    std::fs::copy(&dts_src, libs_dir.join("index.d.ts"))
        .with_context(|| format!("copying OHOS types {dts_src} -> {libs_dir}/index.d.ts"))?;
    if skip_libs {
        return Ok(());
    }
    for entry in std::fs::read_dir(package_dist_dir)
        .with_context(|| format!("reading OHOS dist dir {package_dist_dir}"))?
    {
        let entry = entry?;
        let source = Utf8PathBuf::from_path_buf(entry.path())
            .map_err(|p| anyhow::anyhow!("OHOS dist entry is not utf8: {}", p.display()))?;
        let Some(name) = source.file_name() else {
            continue;
        };
        if name == "index.d.ts" {
            continue;
        }
        if source.is_dir() {
            copy_dir_recursive(&source, &libs_dir.join(name))?;
        }
    }
    Ok(())
}

fn copy_dir_recursive(src: &Utf8Path, dst: &Utf8Path) -> Result<()> {
    std::fs::create_dir_all(dst).with_context(|| format!("creating directory {dst}"))?;
    for entry in std::fs::read_dir(src).with_context(|| format!("reading directory {src}"))? {
        let entry = entry?;
        let source = Utf8PathBuf::from_path_buf(entry.path())
            .map_err(|p| anyhow::anyhow!("path is not utf8: {}", p.display()))?;
        let Some(name) = source.file_name() else {
            continue;
        };
        let target = dst.join(name);
        if source.is_dir() {
            copy_dir_recursive(&source, &target)?;
        } else {
            std::fs::copy(&source, &target)
                .with_context(|| format!("copying file {source} -> {target}"))?;
        }
    }
    Ok(())
}

fn generate_har_archive(har_out: &Utf8Path, package_dir: &Utf8Path) -> Result<()> {
    let Some(parent) = har_out.parent() else {
        bail!("HAR output path has no parent: {har_out}");
    };
    std::fs::create_dir_all(parent).with_context(|| format!("creating HAR output dir {parent}"))?;
    let file = std::fs::File::create(har_out)
        .with_context(|| format!("creating HAR output file {har_out}"))?;
    let encoder = GzEncoder::new(file, Compression::default());
    let mut tar = Builder::new(encoder);
    tar.append_dir_all("package", package_dir)
        .with_context(|| format!("packing HAR package dir {package_dir}"))?;
    tar.finish()
        .with_context(|| format!("finishing HAR archive {har_out}"))?;
    Ok(())
}

fn short_manifest_hash(path: &Utf8Path) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in path.as_str().bytes() {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{:08x}", hash as u32)
}

fn build_arch(
    options: &BuildOptions,
    package: &HostPackage,
    ohos_ndk: &str,
    target_dir: &Utf8Path,
    dist_dir: &Utf8Path,
    type_dir: &Utf8Path,
    arch: Arch,
    explicit_package_arg: bool,
) -> Result<()> {
    let mut command = Command::new(&options.cargo_bin);
    command
        .args(cargo_args_for_arch(
            options,
            package,
            arch,
            explicit_package_arg,
        ))
        .env("CARGO_TARGET_DIR", target_dir.as_str())
        .envs(ohos_env(
            ohos_ndk,
            arch,
            type_dir,
            &package.lib_target_name,
            options.bisheng,
            options.soname.as_deref(),
        )?)
        .stdout(Stdio::piped());

    let rendered = format!("{command:?}");
    let mut child = command
        .spawn()
        .with_context(|| format!("spawning OHOS cargo build: {rendered}"))?;
    let artifacts = collect_build_messages(child.stdout.take(), ohos_ndk)?;
    let status = child.wait()?;
    if !status.success() {
        bail!("OHOS cargo build failed: {rendered}");
    }

    if should_skip_artifact_copy(options.skip_libs) {
        return Ok(());
    }
    let profile = if options.release { "release" } else { "debug" };
    let expected = target_dir
        .join(arch.rust_target())
        .join(profile)
        .join(native_lib_filename(&package.lib_target_name));
    copy_artifacts(
        &filter_artifacts(artifacts, options.copy_static, Some(expected)),
        &dist_dir.join(arch.dist_dir()),
    )
}

fn cargo_args_for_arch(
    options: &BuildOptions,
    package: &HostPackage,
    arch: Arch,
    explicit_package_arg: bool,
) -> Vec<String> {
    let mut args = Vec::new();
    if arch == Arch::LoongArch64 {
        args.push("+nightly".to_string());
    }
    args.push(
        if options.zigbuild {
            "zigbuild"
        } else {
            "build"
        }
        .to_string(),
    );
    if arch == Arch::LoongArch64 {
        args.extend(["-Z".to_string(), "build-std".to_string()]);
    }
    args.extend([
        "--manifest-path".to_string(),
        package.manifest_path.to_string(),
        "--target".to_string(),
        arch.rust_target().to_string(),
        "--message-format=json-render-diagnostics".to_string(),
    ]);
    if options.release && !options.cargo_args.iter().any(|arg| arg == "--release") {
        args.push("--release".to_string());
    }
    if explicit_package_arg && !has_package_arg(&options.cargo_args) {
        args.push("-p".to_string());
        args.push(format!("{}@{}", package.name, package.version));
    }
    args.extend(options.cargo_args.iter().cloned());
    args
}

fn collect_build_messages(
    stdout: Option<std::process::ChildStdout>,
    ohos_ndk: &str,
) -> Result<BuiltArtifacts> {
    let mut artifacts = BTreeSet::new();
    let Some(stdout) = stdout else {
        return Ok(BuiltArtifacts { paths: artifacts });
    };
    for message in Message::parse_stream(BufReader::new(stdout)) {
        match message? {
            Message::CompilerArtifact(artifact) => {
                for filename in artifact.filenames {
                    let path =
                        Utf8PathBuf::from_path_buf(filename.into_std_path_buf()).map_err(|p| {
                            anyhow::anyhow!("artifact path is not utf8: {}", p.display())
                        })?;
                    if artifact_extension_is_native(&path) && !is_rust_intermediate_lib(&path) {
                        artifacts.insert(path);
                    }
                }
            }
            Message::BuildScriptExecuted(script) => {
                for path in resolve_dependency_libraries(&script, ohos_ndk)? {
                    artifacts.insert(path);
                }
            }
            Message::CompilerMessage(message) => {
                if let Some(rendered) = message.message.rendered {
                    eprint!("{rendered}");
                }
            }
            _ => {}
        }
    }
    Ok(BuiltArtifacts { paths: artifacts })
}

fn artifact_extension_is_native(path: &Utf8Path) -> bool {
    matches!(path.extension(), Some("so") | Some("a"))
}

fn is_rust_intermediate_lib(path: &Utf8Path) -> bool {
    let path = path.as_str();
    path.contains("/target/") && path.contains("/deps/")
}

fn resolve_dependency_libraries(script: &BuildScript, ohos_ndk: &str) -> Result<Vec<Utf8PathBuf>> {
    if script.linked_libs.is_empty() || script.linked_paths.is_empty() {
        return Ok(Vec::new());
    }
    let ohos_sysroot = Path::new(ohos_ndk)
        .join("native")
        .join("sysroot")
        .join("usr")
        .join("lib");
    let hos_sysroot =
        resolve_hos_ndk(ohos_ndk).map(|p| p.join("native").join("sysroot").join("usr").join("lib"));
    let lib_names = script
        .linked_libs
        .iter()
        .map(|lib| {
            lib.strip_prefix("dylib=")
                .map(|name| format!("lib{name}.so"))
                .unwrap_or_else(|_| format!("lib{lib}.so"))
        })
        .collect::<Vec<_>>();
    let mut out = Vec::new();
    for path in &script.linked_paths {
        let raw = path.as_str();
        let native = raw.strip_prefix("native=").unwrap_or(raw);
        let base = Utf8Path::new(native);
        if base.starts_with(&ohos_sysroot) {
            continue;
        }
        if let Some(hos_sysroot) = &hos_sysroot {
            if base.starts_with(hos_sysroot) {
                continue;
            }
        }
        if is_rust_intermediate_lib(base) || (!base.is_dir() && !base.is_file()) {
            continue;
        }
        let base = base
            .canonicalize_utf8()
            .unwrap_or_else(|_| base.to_path_buf());
        if base.is_file() {
            out.push(base);
        } else {
            for lib_name in &lib_names {
                let lib = base.join(lib_name);
                if lib.exists() {
                    out.push(lib);
                }
            }
        }
    }
    Ok(out)
}

fn filter_artifacts(
    mut artifacts: BuiltArtifacts,
    copy_static: bool,
    expected: Option<Utf8PathBuf>,
) -> BuiltArtifacts {
    if let Some(expected) = expected {
        if expected.exists() {
            artifacts.paths.insert(expected);
        }
    }
    let paths = artifacts
        .paths
        .into_iter()
        .filter(|path| copy_static || path.extension() != Some("a"))
        .collect();
    BuiltArtifacts { paths }
}

fn should_skip_artifact_copy(skip_libs: bool) -> bool {
    skip_libs
}

fn copy_artifacts(artifacts: &BuiltArtifacts, arch_dist: &Utf8Path) -> Result<()> {
    if artifacts.paths.is_empty() {
        bail!("OHOS build produced no native artifacts");
    }
    if arch_dist.exists() {
        std::fs::remove_dir_all(arch_dist)
            .with_context(|| format!("removing stale OHOS dist dir {arch_dist}"))?;
    }
    std::fs::create_dir_all(arch_dist)
        .with_context(|| format!("creating OHOS arch dist dir {arch_dist}"))?;
    for artifact in &artifacts.paths {
        let Some(file_name) = artifact.file_name() else {
            continue;
        };
        std::fs::copy(artifact, arch_dist.join(file_name))
            .with_context(|| format!("copying OHOS artifact {artifact}"))?;
    }
    Ok(())
}

fn ohos_env(
    ohos_ndk: &str,
    arch: Arch,
    type_dir: &Utf8Path,
    build_target_name: &str,
    bisheng: bool,
    soname: Option<&str>,
) -> Result<HashMap<String, String>> {
    let hos_ndk = resolve_hos_ndk(ohos_ndk);
    let toolchain_root = if bisheng {
        let hos_ndk = hos_ndk
            .as_ref()
            .context("HOS_NDK_HOME or sibling hms SDK is required when --bisheng is enabled")?;
        hos_ndk.join("native").join("BiSheng")
    } else {
        Path::new(ohos_ndk).join("native").join("llvm")
    };
    let toolchain = resolve_toolchain_paths(&toolchain_root);
    let sysroot = Path::new(ohos_ndk).join("native").join("sysroot");
    let mut link_flags = vec![
        format!("--target={}", arch.c_target()),
        format!("--sysroot={}", sysroot.to_string_lossy()),
        "-D__MUSL__".to_string(),
    ];
    if arch == Arch::Arm32 {
        link_flags.extend([
            "-march=armv7-a".to_string(),
            "-mfloat-abi=softfp".to_string(),
            "-mtune=generic-armv7-a".to_string(),
            "-mthumb".to_string(),
        ]);
    }
    if let Some(hos_ndk) = &hos_ndk {
        append_hms_link_flags(&mut link_flags, hos_ndk, arch);
    }
    if let Some(soname) = soname {
        link_flags.push(format!("-Wl,-soname,{}", normalize_soname(soname)?));
    }

    let rustflags = merge_encoded_rustflags(&link_flags, current_rustflags().as_deref());

    let mut path = env::var("PATH").unwrap_or_default();
    let separator = if cfg!(target_os = "windows") {
        ";"
    } else {
        ":"
    };
    path = format!("{}{}{}", toolchain.bin_dir, separator, path);

    let mut envs = HashMap::from([
        (
            format!("CARGO_TARGET_{}_LINKER", arch.rust_link_target()),
            toolchain.cc.clone(),
        ),
        ("LIBCLANG_PATH".to_string(), toolchain.lib_dir.clone()),
        ("CLANG_PATH".to_string(), toolchain.cxx.clone()),
        (
            format!("CXXSTDLIB_{}", arch.rust_link_target()),
            "c++".to_string(),
        ),
        ("TARGET_CC".to_string(), toolchain.cc.clone()),
        ("TARGET_CXX".to_string(), toolchain.cxx.clone()),
        ("TARGET_RANLIB".to_string(), toolchain.ranlib.clone()),
        ("TARGET_AR".to_string(), toolchain.ar.clone()),
        ("TARGET_AS".to_string(), toolchain.llvm_as.clone()),
        ("TARGET_LD".to_string(), toolchain.ld.clone()),
        ("TARGET_STRIP".to_string(), toolchain.strip.clone()),
        ("TARGET_OBJDUMP".to_string(), toolchain.objdump.clone()),
        ("TARGET_OBJCOPY".to_string(), toolchain.objcopy.clone()),
        ("TARGET_NM".to_string(), toolchain.nm.clone()),
        ("CARGO_ENCODED_RUSTFLAGS".to_string(), rustflags),
        ("PATH".to_string(), path),
        ("TYPE_DEF_TMP_PATH".to_string(), type_dir.to_string()),
        ("NAPI_TYPE_DEF_TMP_FOLDER".to_string(), type_dir.to_string()),
        (
            "NAPI_BUILD_TARGET_NAME".to_string(),
            build_target_name.to_string(),
        ),
        ("OPENCV_CLANG_ARGS".to_string(), link_flags.join(" ")),
        ("DEP_ATOMIC".to_string(), "clang_rt.builtins".to_string()),
    ]);

    if let Some(hos_ndk) = &hos_ndk {
        apply_hms_include_env(&mut envs, hos_ndk, arch);
    }
    Ok(envs)
}

fn current_rustflags() -> Option<String> {
    [
        "CARGO_RUSTFLAGS",
        "CARGO_ENCODED_RUSTFLAGS",
        "RUSTFLAGS",
        "ENCODED_RUSTFLAGS",
    ]
    .iter()
    .find_map(|key| env::var(key).ok().filter(|value| !value.is_empty()))
}

fn merge_encoded_rustflags(link_flags: &[String], existing: Option<&str>) -> String {
    let mut rustflags = link_flags
        .iter()
        .map(|flag| format!("-Clink-arg={flag}"))
        .collect::<Vec<_>>()
        .join("\x1f");
    if let Some(existing) = existing.filter(|value| !value.is_empty()) {
        rustflags = format!("{rustflags}\x1f{existing}");
    }
    rustflags
}

fn normalize_soname(soname: &str) -> Result<String> {
    if soname.contains(".so.")
        && soname
            .split(".so.")
            .nth(1)
            .is_some_and(|s| s.chars().next().is_some_and(|ch| ch.is_ascii_digit()))
    {
        bail!("SONAME with version number is not supported: {soname}");
    }
    if soname.starts_with("lib") && soname.contains(".so") {
        Ok(soname.to_string())
    } else if soname.ends_with(".so") {
        Ok(format!("lib{soname}"))
    } else {
        Ok(format!("lib{soname}.so"))
    }
}

fn resolve_toolchain_paths(root: &Path) -> ToolchainPaths {
    let bin_dir = root.join("bin");
    let lib_dir = root.join("lib");
    let to_string = |path: PathBuf| path.to_string_lossy().to_string();
    let tool = |name: &str| to_string(bin_dir.join(name));
    ToolchainPaths {
        ranlib: tool("llvm-ranlib"),
        ar: tool("llvm-ar"),
        cc: tool("clang"),
        cxx: tool("clang++"),
        llvm_as: tool("llvm-as"),
        ld: tool("ld.lld"),
        strip: tool("llvm-strip"),
        objdump: tool("llvm-objdump"),
        objcopy: tool("llvm-objcopy"),
        nm: tool("llvm-nm"),
        bin_dir: to_string(bin_dir),
        lib_dir: to_string(lib_dir),
    }
}

fn resolve_hos_ndk(ohos_ndk: &str) -> Option<PathBuf> {
    let sibling = Path::new(ohos_ndk).parent()?.join("hms");
    if sibling.exists() {
        Some(sibling)
    } else {
        env::var_os("HOS_NDK_HOME").map(PathBuf::from)
    }
}

fn append_hms_link_flags(flags: &mut Vec<String>, hos_ndk: &Path, arch: Arch) {
    let lib = hos_ndk
        .join("native")
        .join("sysroot")
        .join("usr")
        .join("lib")
        .join(arch.c_target());
    if lib.exists() {
        flags.push(format!("-L{}", lib.to_string_lossy()));
        flags.push(format!("-Wl,-rpath-link,{}", lib.to_string_lossy()));
    }
}

fn apply_hms_include_env(envs: &mut HashMap<String, String>, hos_ndk: &Path, arch: Arch) {
    let include = hos_ndk
        .join("native")
        .join("sysroot")
        .join("usr")
        .join("include");
    if !include.exists() {
        return;
    }
    let include_flag = format!("-I{}", include.to_string_lossy());
    append_env_with_flag(envs, "TARGET_CFLAGS", &include_flag);
    append_env_with_flag(envs, "TARGET_CXXFLAGS", &include_flag);
    let bindgen_target = arch.rust_target().replace('-', "_");
    append_env_with_flag(
        envs,
        &format!("BINDGEN_EXTRA_CLANG_ARGS_{bindgen_target}"),
        &include_flag,
    );
    append_env_with_flag(
        envs,
        &format!(
            "BINDGEN_EXTRA_CLANG_ARGS_{}",
            bindgen_target.to_ascii_uppercase()
        ),
        &include_flag,
    );
}

fn append_env_with_flag(envs: &mut HashMap<String, String>, key: &str, append: &str) {
    let current = env::var(key).unwrap_or_default();
    let merged = if current.is_empty() {
        append.to_string()
    } else {
        format!("{current} {append}")
    };
    envs.insert(key.to_string(), merged);
}

fn native_lib_filename(lib_target_name: &str) -> String {
    format!("lib{lib_target_name}.so")
}

fn emit_index_d_ts(dist_dir: &Utf8Path, type_dir: &Utf8Path) -> Result<()> {
    let mut defs = Vec::new();
    collect_type_defs(type_dir, &mut defs)?;
    let output = render_index_d_ts(defs);
    std::fs::write(dist_dir.join("index.d.ts"), output)
        .with_context(|| format!("writing OHOS index.d.ts in {dist_dir}"))?;
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct TypeDefLine {
    kind: String,
    name: String,
    original_name: Option<String>,
    def: String,
    js_doc: Option<String>,
    js_mod: Option<String>,
    extends: Option<String>,
}

fn collect_type_defs(path: &Utf8Path, defs: &mut Vec<TypeDefLine>) -> Result<()> {
    if !path.exists() {
        return Ok(());
    }
    if path.is_dir() {
        for entry in std::fs::read_dir(path).with_context(|| format!("reading {path}"))? {
            let entry = entry?;
            let child = Utf8PathBuf::from_path_buf(entry.path())
                .map_err(|p| anyhow::anyhow!("OHOS type path is not utf8: {}", p.display()))?;
            collect_type_defs(&child, defs)?;
        }
        return Ok(());
    }
    let Some(ext) = path.extension() else {
        return Ok(());
    };
    if ext != "d.ts" && ext != "ts" {
        return Ok(());
    }
    let file = std::fs::File::open(path).with_context(|| format!("opening {path}"))?;
    for line in BufReader::new(file).lines() {
        let line = line?;
        if let Some(def) = parse_type_def_line(&line)? {
            defs.push(def);
        } else if !line.trim().is_empty() {
            defs.push(TypeDefLine {
                kind: "raw".to_string(),
                name: String::new(),
                original_name: None,
                def: line.to_string(),
                js_doc: None,
                js_mod: None,
                extends: None,
            });
        }
    }
    Ok(())
}

fn parse_type_def_line(line: &str) -> Result<Option<TypeDefLine>> {
    let mut trimmed = line.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }
    if !trimmed.starts_with('{') {
        let Some((_, suffix)) = trimmed.split_once(':') else {
            return Ok(None);
        };
        trimmed = suffix.trim();
    }
    if !trimmed.starts_with('{') {
        return Ok(None);
    }
    let value: Value = serde_json::from_str(trimmed)
        .with_context(|| format!("parsing OHOS type definition JSON line: {trimmed}"))?;
    Ok(Some(TypeDefLine {
        kind: value
            .get("kind")
            .and_then(Value::as_str)
            .unwrap_or("raw")
            .to_string(),
        name: value
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
        original_name: value
            .get("original_name")
            .and_then(Value::as_str)
            .map(str::to_string),
        def: value
            .get("def")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .replace("\\n", "\n"),
        js_doc: value
            .get("js_doc")
            .and_then(Value::as_str)
            .map(|doc| doc.replace("\\n", "\n")),
        js_mod: value
            .get("js_mod")
            .and_then(Value::as_str)
            .map(str::to_string),
        extends: value
            .get("extends")
            .and_then(Value::as_str)
            .map(str::to_string),
    }))
}

fn render_index_d_ts(defs: Vec<TypeDefLine>) -> String {
    if defs.is_empty() {
        return TYPE_HEADER.to_string();
    }
    let mut grouped: BTreeMap<String, Vec<TypeDefLine>> = BTreeMap::new();
    let mut class_defs: BTreeMap<(String, String), TypeDefLine> = BTreeMap::new();
    for def in defs {
        let namespace = def
            .js_mod
            .clone()
            .unwrap_or_else(|| "__TOP_LEVEL_MODULE__".to_string());
        match def.kind.as_str() {
            "struct" => {
                class_defs.insert((namespace, def.name.clone()), def);
            }
            "extends" => {
                if let Some(class_def) = class_defs.get_mut(&(namespace, def.name.clone())) {
                    class_def.extends = Some(def.def);
                }
            }
            "impl" => {
                if let Some(class_def) = class_defs.get_mut(&(namespace, def.name.clone())) {
                    if !class_def.def.is_empty() {
                        class_def.def.push('\n');
                    }
                    class_def.def.push_str(&def.def);
                }
            }
            _ => grouped.entry(namespace).or_default().push(def),
        }
    }
    for ((namespace, _), def) in class_defs {
        grouped.entry(namespace).or_default().push(def);
    }

    let mut out = TYPE_HEADER.to_string();
    for (namespace, mut defs) in grouped {
        defs.sort_by(|a, b| a.name.cmp(&b.name));
        if namespace == "__TOP_LEVEL_MODULE__" {
            for def in defs {
                out.push_str(&pretty_type_def(&def, false));
                out.push('\n');
            }
        } else {
            out.push_str(&format!("export namespace {namespace} {{\n"));
            for def in defs {
                out.push_str(&indent(&pretty_type_def(&def, true), 2));
                out.push('\n');
            }
            out.push_str("}\n");
        }
    }
    out.replace("Buffer", "ArrayBuffer")
        .replace("ExternalObject<", "ExternalObject<")
}

fn pretty_type_def(def: &TypeDefLine, ambient: bool) -> String {
    let mut out = def.js_doc.clone().unwrap_or_default();
    let declare = if ambient { "export" } else { "export declare" };
    match def.kind.as_str() {
        "interface" => out.push_str(&format!(
            "export interface {} {{\n{}\n}}",
            def.name, def.def
        )),
        "enum" => out.push_str(&format!(
            "{declare} const enum {} {{\n{}\n}}",
            def.name, def.def
        )),
        "string_enum" => {
            let values = def
                .def
                .split_once('=')
                .map(|(_, rhs)| {
                    rhs.split(',')
                        .map(str::trim)
                        .filter(|s| !s.is_empty())
                        .collect::<Vec<_>>()
                        .join(" | ")
                })
                .unwrap_or_else(|| def.def.clone());
            out.push_str(&format!("export type {} = {};", def.name, values));
        }
        "type" => out.push_str(&format!("export type {} = \n{}", def.name, def.def)),
        "struct" => {
            let extends = def
                .extends
                .as_ref()
                .map(|extends| format!(" extends {extends}"))
                .unwrap_or_default();
            out.push_str(&format!(
                "{declare} class {}{} {{\n{}\n}}",
                def.name, extends, def.def
            ));
            if let Some(original_name) = &def.original_name {
                if original_name != &def.name {
                    out.push_str(&format!("\nexport type {original_name} = {}", def.name));
                }
            }
        }
        "fn" => out.push_str(&format!("{declare} {}", def.def)),
        "raw" => out.push_str(&def.def),
        _ => out.push_str(&def.def),
    }
    out
}

fn indent(src: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    src.lines()
        .map(|line| {
            if line.is_empty() {
                String::new()
            } else {
                format!("{prefix}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_ohos_arch_aliases() {
        assert_eq!(Arch::parse("aarch").unwrap(), Arch::Arm64);
        assert_eq!(
            Arch::parse("arm64").unwrap().rust_target(),
            "aarch64-unknown-linux-ohos"
        );
        assert_eq!(Arch::parse("x64").unwrap().dist_dir(), "x86_64");
        assert_eq!(Arch::parse("arm32").unwrap().c_target(), "arm-linux-ohos");
        assert_eq!(
            Arch::parse("loongarch64").unwrap().rust_target(),
            "loongarch64-unknown-linux-ohos"
        );
        assert!(Arch::parse("mips").is_err());
    }

    #[test]
    fn native_lib_filename_matches_harmony_import_name() {
        assert_eq!(native_lib_filename("uni_core_ohos"), "libuni_core_ohos.so");
    }

    #[test]
    fn cargo_args_include_release_package_soname_and_loongarch() {
        let opts = BuildOptions {
            cargo_bin: "cargo".into(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            dist_dir: Utf8PathBuf::from("/tmp/dist"),
            package_name: None,
            har_out: None,
            no_har: false,
            arches: vec![],
            target_dir: None,
            release: true,
            cargo_args: vec![
                "--no-default-features".into(),
                "--features".into(),
                "ohos".into(),
            ],
            copy_static: false,
            skip_libs: false,
            dts_cache: false,
            skip_check: true,
            zigbuild: true,
            bisheng: false,
            package: Some("uni-core-ohos".into()),
            skip_napi_check: true,
            soname: Some("uni_core_ohos".into()),
        };
        let package = HostPackage {
            name: "uni-core-ohos".into(),
            version: "0.0.0".into(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            lib_target_name: "uni_core_ohos".into(),
        };
        let args = cargo_args_for_arch(&opts, &package, Arch::LoongArch64, true);
        assert_eq!(args[0], "+nightly");
        assert_eq!(args[1], "zigbuild");
        assert!(args.contains(&"-Z".into()));
        assert!(args.contains(&"build-std".into()));
        assert!(args.contains(&"--release".into()));
        assert!(args.windows(2).any(|w| w == ["-p", "uni-core-ohos@0.0.0"]));
        assert!(args
            .windows(3)
            .any(|w| w == ["--no-default-features", "--features", "ohos"]));
        assert_eq!(
            normalize_soname("uni_core_ohos").unwrap(),
            "libuni_core_ohos.so"
        );
    }

    #[test]
    fn ohos_env_supports_bisheng_hms_soname_and_rustflag_merge() {
        let root = std::env::temp_dir().join(format!(
            "uniffi-ohos-env-{}",
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let ohos = root.join("ohos");
        let hms = root.join("hms");
        std::fs::create_dir_all(ohos.join("native/sysroot")).unwrap();
        std::fs::create_dir_all(hms.join("native/BiSheng/bin")).unwrap();
        std::fs::create_dir_all(hms.join("native/BiSheng/lib")).unwrap();
        std::fs::create_dir_all(hms.join("native/sysroot/usr/include")).unwrap();
        std::fs::create_dir_all(hms.join("native/sysroot/usr/lib/aarch64-linux-ohos")).unwrap();

        let ohos = ohos.to_string_lossy().to_string();
        let type_dir = Utf8Path::new("/tmp/uniffi-ohos-types");
        let envs = ohos_env(
            &ohos,
            Arch::Arm64,
            type_dir,
            "demo_ohos",
            true,
            Some("demo_ohos"),
        )
        .unwrap();
        assert!(envs["CARGO_TARGET_AARCH64_UNKNOWN_LINUX_OHOS_LINKER"]
            .contains("hms/native/BiSheng/bin/clang"));
        assert!(envs["CARGO_ENCODED_RUSTFLAGS"].contains("-Clink-arg=-Wl,-soname,libdemo_ohos.so"));
        assert!(envs["TARGET_CFLAGS"].contains("native/sysroot/usr/include"));
        assert!(envs["OPENCV_CLANG_ARGS"].contains("native/sysroot/usr/lib/aarch64-linux-ohos"));

        let merged = merge_encoded_rustflags(&["-D__MUSL__".into()], Some("-Cdebuginfo=1"));
        assert_eq!(merged, "-Clink-arg=-D__MUSL__\x1f-Cdebuginfo=1");

        std::fs::remove_dir_all(root).ok();
    }

    #[test]
    fn cargo_args_do_not_duplicate_existing_package_filter() {
        let opts = BuildOptions {
            cargo_bin: "cargo".into(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            dist_dir: Utf8PathBuf::from("/tmp/dist"),
            package_name: None,
            har_out: None,
            no_har: false,
            arches: vec![],
            target_dir: None,
            release: false,
            cargo_args: vec!["--package".into(), "from-cli".into()],
            copy_static: false,
            skip_libs: false,
            dts_cache: false,
            skip_check: true,
            zigbuild: false,
            bisheng: false,
            package: None,
            skip_napi_check: true,
            soname: None,
        };
        let package = HostPackage {
            name: "uni-core-ohos".into(),
            version: "0.0.0".into(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            lib_target_name: "uni_core_ohos".into(),
        };
        let args = cargo_args_for_arch(&opts, &package, Arch::Arm64, true);
        assert_eq!(
            args.iter()
                .filter(|arg| arg.as_str() == "-p" || arg.as_str() == "--package")
                .count(),
            1
        );
        assert!(args.windows(2).any(|w| w == ["--package", "from-cli"]));
    }

    #[test]
    fn package_arg_detection_supports_short_long_and_equals() {
        assert_eq!(
            package_arg_from_cargo_args(&["-p".into(), "core".into()]),
            Some("core".into())
        );
        assert_eq!(
            package_arg_from_cargo_args(&["--package=core".into()]),
            Some("core".into())
        );
        assert!(package_arg_from_cargo_args(&["--features".into(), "ohos".into()]).is_none());
    }

    #[test]
    fn package_filter_rejects_conflicting_cli_and_cargo_args() {
        assert_eq!(
            resolve_package_filter(Some("core"), &["--package".into(), "core".into()]).unwrap(),
            Some("core".into())
        );
        assert!(
            resolve_package_filter(Some("core"), &["--package".into(), "other".into()]).is_err()
        );
    }

    #[test]
    fn package_dist_dir_only_splits_multi_package_builds() {
        let package = HostPackage {
            name: "uni-core-ohos".into(),
            version: "0.0.0".into(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            lib_target_name: "uni_core_ohos".into(),
        };
        assert_eq!(
            package_dist_dir(Utf8Path::new("/tmp/dist"), &package, 1),
            Utf8PathBuf::from("/tmp/dist")
        );
        assert_eq!(
            package_dist_dir(Utf8Path::new("/tmp/dist"), &package, 2),
            Utf8PathBuf::from("/tmp/dist/uni-core-ohos")
        );
    }

    #[test]
    fn artifact_filter_dedupes_and_respects_static_flag() {
        let mut paths = BTreeSet::new();
        paths.insert(Utf8PathBuf::from("/tmp/liba.so"));
        paths.insert(Utf8PathBuf::from("/tmp/liba.so"));
        paths.insert(Utf8PathBuf::from("/tmp/liba.a"));
        let filtered = filter_artifacts(
            BuiltArtifacts {
                paths: paths.clone(),
            },
            false,
            None,
        );
        assert_eq!(filtered.paths.len(), 1);
        assert!(filtered.paths.contains(Utf8Path::new("/tmp/liba.so")));

        let filtered = filter_artifacts(BuiltArtifacts { paths }, true, None);
        assert_eq!(filtered.paths.len(), 2);
        assert!(filtered.paths.contains(Utf8Path::new("/tmp/liba.a")));
    }

    #[test]
    fn skip_libs_disables_artifact_copy() {
        assert!(should_skip_artifact_copy(true));
        assert!(!should_skip_artifact_copy(false));
    }

    #[test]
    fn renders_type_defs_from_ohos_json_lines() {
        let json = r#"type_def:{"kind":"fn","name":"add","def":"function add(a: number): number;","js_doc":null,"js_mod":null}"#;
        let def = parse_type_def_line(json).unwrap().unwrap();
        let rendered = render_index_d_ts(vec![def]);
        assert!(rendered.contains("export declare function add(a: number): number;"));
        assert!(!rendered.contains("typeof import"));
    }

    #[test]
    fn renders_har_package_metadata_and_entry_templates() {
        let package_json = render_oh_package_json5("@ohos-rs/ada", "0.1.2");
        assert!(package_json.contains("\"name\": \"@ohos-rs/ada\""));
        assert!(package_json.contains("\"main\": \"index.ets\""));
        assert!(package_json.contains("\"types\": \"libs/index.d.ts\""));

        let index = render_index_ets("uni_core_ohos");
        assert!(index.contains("import * as api from \"libuni_core_ohos.so\";"));
        assert!(index.contains("export * from \"libuni_core_ohos.so\";"));

        let module = render_module_json5("@ohos-rs/ada");
        assert!(module.contains("\"type\": \"har\""));
        assert!(module.contains("\"name\": \"@ohos-rs/ada\""));
    }

    #[test]
    fn copies_fake_dist_into_package_libs() {
        let root = temp_test_dir("uniffi-ohos-copy-dist");
        let dist = root.join("dist");
        let libs = root.join("package/libs");
        std::fs::create_dir_all(dist.join("arm64-v8a")).unwrap();
        std::fs::create_dir_all(dist.join("x86_64")).unwrap();
        std::fs::write(
            dist.join("index.d.ts"),
            "export declare const add: (a: number, b: number) => number;\n",
        )
        .unwrap();
        std::fs::write(dist.join("arm64-v8a/libuni_core_ohos.so"), "arm").unwrap();
        std::fs::write(dist.join("x86_64/libuni_core_ohos.so"), "x64").unwrap();

        copy_dist_to_package_libs(&dist, &libs, false).unwrap();
        assert!(libs.join("index.d.ts").exists());
        assert!(libs.join("arm64-v8a/libuni_core_ohos.so").exists());
        assert!(libs.join("x86_64/libuni_core_ohos.so").exists());

        std::fs::remove_dir_all(root).ok();
    }

    #[test]
    fn generates_har_with_package_root_and_no_absolute_paths() {
        let root = temp_test_dir("uniffi-ohos-har");
        let package_dir = root.join("package");
        std::fs::create_dir_all(package_dir.join("src/main")).unwrap();
        std::fs::create_dir_all(package_dir.join("libs/arm64-v8a")).unwrap();
        std::fs::write(
            package_dir.join("oh-package.json5"),
            render_oh_package_json5("@scope/demo", "0.0.1"),
        )
        .unwrap();
        std::fs::write(package_dir.join("index.ets"), render_index_ets("demo_ohos")).unwrap();
        std::fs::write(
            package_dir.join("src/main/module.json5"),
            render_module_json5("@scope/demo"),
        )
        .unwrap();
        std::fs::write(package_dir.join("libs/index.d.ts"), "export {}\n").unwrap();
        std::fs::write(package_dir.join("libs/arm64-v8a/libdemo_ohos.so"), "fake").unwrap();

        let har = root.join("demo.har");
        generate_har_archive(&har, &package_dir).unwrap();

        let file = std::fs::File::open(&har).unwrap();
        let decoder = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(decoder);
        let mut saw_required = false;
        for entry in archive.entries().unwrap() {
            let entry = entry.unwrap();
            let path = entry.path().unwrap().to_string_lossy().to_string();
            assert!(!path.starts_with('/'), "entry must not be absolute: {path}");
            assert!(
                !path.contains(":\\"),
                "entry must not include windows absolute path: {path}"
            );
            assert!(
                path == "package" || path.starts_with("package/"),
                "entry must be rooted at package/: {path}"
            );
            if path == "package/oh-package.json5" {
                saw_required = true;
            }
        }
        assert!(saw_required, "HAR must contain package/oh-package.json5");
        std::fs::remove_dir_all(root).ok();
    }

    #[test]
    fn multi_package_har_out_and_package_name_require_explicit_package_filter() {
        let options = BuildOptions {
            cargo_bin: "cargo".to_string(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            dist_dir: Utf8PathBuf::from("/tmp/out/ohos/dist"),
            package_name: Some("@scope/pkg".to_string()),
            har_out: None,
            no_har: false,
            arches: vec!["aarch".to_string()],
            target_dir: None,
            release: false,
            cargo_args: vec![],
            copy_static: false,
            skip_libs: false,
            dts_cache: false,
            skip_check: false,
            zigbuild: false,
            bisheng: false,
            package: None,
            skip_napi_check: false,
            soname: None,
        };
        let package = HostPackage {
            name: "demo-ohos".to_string(),
            version: "0.1.0".to_string(),
            manifest_path: Utf8PathBuf::from("/tmp/host/Cargo.toml"),
            lib_target_name: "demo_ohos".to_string(),
        };
        let root = Utf8Path::new("/tmp/out/ohos");
        assert_eq!(
            package_stage_dir(root, &package, 2),
            Utf8PathBuf::from("/tmp/out/ohos/package/demo-ohos")
        );
        assert_eq!(
            resolve_har_out(None, root, &package, 2),
            Utf8PathBuf::from("/tmp/out/ohos/demo-ohos-demo_ohos.har")
        );
        assert_eq!(
            resolve_oh_package_name(options.package_name.as_deref(), &package).unwrap(),
            "@scope/pkg"
        );
    }

    fn temp_test_dir(prefix: &str) -> Utf8PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("{prefix}-{nanos}"));
        std::fs::create_dir_all(&dir).unwrap();
        Utf8PathBuf::from_path_buf(dir).unwrap()
    }
}
