//! Rust code generator for the napi flavor.
//!
//! This module renders a single Rust bridge file per component. The
//! surrounding `mod.rs` owns output layout and the tiny JavaScript
//! adapter; this file owns type lowering/lifting, callback handling,
//! async exports, and napi-specific surface generation.

use anyhow::{bail, ensure, Result};
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::parse2;
use uniffi_bindgen::interface::{
    Argument, AsType, Callable, ComponentInterface, Constructor, Enum, Field, Function, Method,
    Object, ObjectImpl, Record, Type, Variant,
};

pub fn render_napi_rust(ci: &ComponentInterface) -> Result<String> {
    let generator = Generator::new(ci);
    generator.validate()?;
    let tokens = generator.render()?;
    let file = parse2::<syn::File>(tokens)?;
    Ok(prettyplease::unparse(&file))
}

pub(crate) struct Generator<'a> {
    ci: &'a ComponentInterface,
}

impl<'a> Generator<'a> {
    fn new(ci: &'a ComponentInterface) -> Self {
        Self { ci }
    }

    fn render(&self) -> Result<TokenStream> {
        let records = self
            .ci
            .record_definitions()
            .iter()
            .map(|record| self.render_record(record))
            .collect::<Result<Vec<_>>>()?;
        let enums = self
            .ci
            .enum_definitions()
            .iter()
            .map(|enum_| self.render_enum(enum_))
            .collect::<Result<Vec<_>>>()?;
        let objects = self
            .ci
            .object_definitions()
            .iter()
            .map(|object| self.render_object(object))
            .collect::<Result<Vec<_>>>()?;
        let functions = self
            .ci
            .function_definitions()
            .iter()
            .map(|function| self.render_function(function))
            .collect::<Result<Vec<_>>>()?;

        Ok(quote! {
            // Generated by uniffi-bindgen-napi.
            #[allow(unused_imports)]
            use napi::bindgen_prelude::*;
            use napi::threadsafe_function::{ThreadsafeFunction, ThreadsafeFunctionCallMode};
            use napi_derive::napi;

            fn into_napi_error<E: std::fmt::Display>(err: E) -> Error {
                Error::new(Status::GenericFailure, err.to_string())
            }

            #[derive(Clone, Debug, PartialEq, Eq, Hash)]
            struct __UniffiTimestamp(pub ::std::time::SystemTime);

            #[derive(Clone, Debug, PartialEq, Eq, Hash)]
            struct __UniffiDuration(pub ::std::time::Duration);

            impl TypeName for __UniffiTimestamp {
                fn type_name() -> &'static str {
                    "Date"
                }

                fn value_type() -> ValueType {
                    ValueType::Object
                }
            }

            impl ValidateNapiValue for __UniffiTimestamp {}

            impl FromNapiValue for __UniffiTimestamp {
                unsafe fn from_napi_value(env: napi::sys::napi_env, napi_val: napi::sys::napi_value) -> Result<Self> {
                    let mut ms = 0.0;
                    napi::check_status!(unsafe { napi::sys::napi_get_date_value(env, napi_val, &mut ms) })?;
                    if !ms.is_finite() {
                        return Err(Error::new(Status::InvalidArg, "invalid Date"));
                    }
                    if ms.abs() > 8.64e15 {
                        return Err(Error::new(Status::InvalidArg, "timestamp exceeds JS Date range"));
                    }
                    let ms_i = ms.trunc() as i64;
                    let ts = if ms_i >= 0 {
                        ::std::time::UNIX_EPOCH
                            .checked_add(::std::time::Duration::from_millis(ms_i as u64))
                            .ok_or_else(|| Error::new(Status::InvalidArg, "timestamp overflow"))?
                    } else {
                        ::std::time::UNIX_EPOCH
                            .checked_sub(::std::time::Duration::from_millis((-ms_i) as u64))
                            .ok_or_else(|| Error::new(Status::InvalidArg, "timestamp overflow"))?
                    };
                    Ok(Self(ts))
                }
            }

            impl ToNapiValue for __UniffiTimestamp {
                unsafe fn to_napi_value(env: napi::sys::napi_env, val: Self) -> Result<napi::sys::napi_value> {
                    let ms = match val.0.duration_since(::std::time::UNIX_EPOCH) {
                        Ok(delta) => (delta.as_secs() as f64) * 1000.0 + (delta.subsec_nanos() as f64) / 1_000_000.0,
                        Err(err) => {
                            let delta = err.duration();
                            -((delta.as_secs() as f64) * 1000.0 + (delta.subsec_nanos() as f64) / 1_000_000.0)
                        }
                    };
                    if !ms.is_finite() || ms.abs() > 8.64e15 {
                        return Err(Error::new(Status::InvalidArg, "timestamp exceeds JS Date range"));
                    }
                    let mut js_value = std::ptr::null_mut();
                    napi::check_status!(unsafe { napi::sys::napi_create_date(env, ms, &mut js_value) })?;
                    Ok(js_value)
                }
            }

            impl TypeName for __UniffiDuration {
                fn type_name() -> &'static str {
                    "number"
                }

                fn value_type() -> ValueType {
                    ValueType::Number
                }
            }

            impl ValidateNapiValue for __UniffiDuration {}

            impl FromNapiValue for __UniffiDuration {
                unsafe fn from_napi_value(env: napi::sys::napi_env, napi_val: napi::sys::napi_value) -> Result<Self> {
                    let ms = f64::from_napi_value(env, napi_val)?;
                    if !ms.is_finite() {
                        return Err(Error::new(Status::InvalidArg, "duration must be finite"));
                    }
                    if ms < 0.0 {
                        return Err(Error::new(Status::InvalidArg, "duration must be non-negative"));
                    }
                    let secs_f = (ms / 1000.0).trunc();
                    if secs_f > u64::MAX as f64 {
                        return Err(Error::new(Status::InvalidArg, "duration exceeds Rust range"));
                    }
                    let mut secs = secs_f as u64;
                    let mut nanos = ((ms % 1000.0) * 1_000_000.0).round() as u32;
                    if nanos == 1_000_000_000 {
                        nanos = 0;
                        secs = secs
                            .checked_add(1)
                            .ok_or_else(|| Error::new(Status::InvalidArg, "duration exceeds Rust range"))?;
                    }
                    Ok(Self(::std::time::Duration::new(secs, nanos)))
                }
            }

            impl ToNapiValue for __UniffiDuration {
                unsafe fn to_napi_value(env: napi::sys::napi_env, val: Self) -> Result<napi::sys::napi_value> {
                    let ms = (val.0.as_secs() as f64) * 1000.0 + (val.0.subsec_nanos() as f64) / 1_000_000.0;
                    if !ms.is_finite() || ms > 9_007_199_254_740_991.0 {
                        return Err(Error::new(Status::InvalidArg, "duration exceeds JS number range"));
                    }
                    f64::to_napi_value(env, ms)
                }
            }

            #(#records)*
            #(#enums)*
            #(#objects)*
            #(#functions)*
        })
    }

    fn validate(&self) -> Result<()> {
        let callback_trait_names = self
            .ci
            .object_definitions()
            .iter()
            .filter(|object| object.has_callback_interface())
            .map(|object| object.name().to_string())
            .collect::<std::collections::HashSet<_>>();

        for callback in self.ci.callback_interface_definitions() {
            if !callback_trait_names.contains(callback.name()) {
                bail!(
                    "callback interface `{}` is not supported unless it is exported via `with_foreign` on an object trait",
                    callback.name()
                );
            }
        }

        for record in self.ci.record_definitions() {
            ensure!(
                record.constructors().is_empty() && record.methods().is_empty(),
                "record `{}` methods/constructors are not supported in the napi bridge yet",
                record.name()
            );
            for field in record.fields() {
                self.ensure_type_supported(&field.as_type(), TypeUsage::Value, "record field")?;
            }
        }

        for enum_ in self.ci.enum_definitions() {
            ensure!(
                enum_.constructors().is_empty() && enum_.methods().is_empty(),
                "enum `{}` methods/constructors are not supported in the napi bridge yet",
                enum_.name()
            );
            for variant in enum_.variants() {
                for field in variant.fields() {
                    self.ensure_type_supported(&field.as_type(), TypeUsage::Value, "enum field")?;
                }
            }
        }

        for object in self.ci.object_definitions() {
            if object.remote() {
                bail!("remote object `{}` is not supported", object.name());
            }
            match object.imp() {
                ObjectImpl::Struct | ObjectImpl::Trait => {
                    for constructor in object.constructors() {
                        self.validate_callable(constructor, "constructor")?;
                    }
                    for method in object.methods() {
                        self.validate_callable(method, "method")?;
                    }
                }
                ObjectImpl::CallbackTrait => {
                    ensure!(
                        object.constructors().is_empty(),
                        "callback trait `{}` constructors are not supported",
                        object.name()
                    );
                    for method in object.methods() {
                        ensure!(
                            !method.is_async(),
                            "callback trait method `{}`.{} async callbacks are not supported",
                            object.name(),
                            method.name()
                        );
                        ensure!(
                            method.return_type().is_none(),
                            "callback trait method `{}`.{} must return `()`",
                            object.name(),
                            method.name()
                        );
                        ensure!(
                            method.throws_type().is_none(),
                            "callback trait method `{}`.{} must not throw",
                            object.name(),
                            method.name()
                        );
                        for arg in method.arguments() {
                            self.ensure_type_supported(
                                &arg.as_type(),
                                TypeUsage::CallbackArg,
                                "callback argument",
                            )?;
                        }
                    }
                }
            }
        }

        for function in self.ci.function_definitions() {
            self.validate_callable(function, "function")?;
        }

        Ok(())
    }

    fn validate_callable(&self, callable: &dyn Callable, label: &str) -> Result<()> {
        for arg in callable.arguments() {
            self.ensure_type_supported(&arg.as_type(), TypeUsage::Arg, label)?;
        }
        if let Some(return_type) = callable.return_type() {
            self.ensure_type_supported(return_type, TypeUsage::Return, label)?;
        }
        if let Some(throws_type) = callable.throws_type() {
            self.ensure_type_supported(throws_type, TypeUsage::Error, label)?;
        }
        Ok(())
    }

    fn ensure_type_supported(&self, ty: &Type, usage: TypeUsage, label: &str) -> Result<()> {
        match ty {
            Type::UInt8
            | Type::Int8
            | Type::UInt16
            | Type::Int16
            | Type::UInt32
            | Type::Int32
            | Type::UInt64
            | Type::Int64
            | Type::Float32
            | Type::Float64
            | Type::Boolean
            | Type::String
            | Type::Bytes => Ok(()),
            Type::Record { name, .. } | Type::Enum { name, .. } => {
                ensure!(
                    self.ci.get_type(name).is_some(),
                    "{label} type `{name}` is unresolved"
                );
                Ok(())
            }
            Type::Object { name, imp, .. } => match imp {
                ObjectImpl::Struct | ObjectImpl::Trait => {
                    if matches!(usage, TypeUsage::Value | TypeUsage::CallbackArg) {
                        bail!("{label} type `{name}` is not supported in nested/value contexts");
                    }
                    Ok(())
                }
                ObjectImpl::CallbackTrait => {
                    ensure!(
                        matches!(usage, TypeUsage::Arg),
                        "{label} type `{name}` is only supported as a direct function/method argument"
                    );
                    Ok(())
                }
            },
            Type::Optional { inner_type } | Type::Sequence { inner_type } => {
                self.ensure_type_supported(inner_type, usage, label)
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                self.ensure_type_supported(key_type, TypeUsage::Value, label)?;
                self.ensure_type_supported(value_type, TypeUsage::Value, label)
            }
            Type::Timestamp | Type::Duration => Ok(()),
            Type::CallbackInterface { name, .. } => {
                bail!("callback interface type `{name}` is not supported directly")
            }
            Type::Custom { builtin, .. } => self.ensure_type_supported(builtin, usage, label),
        }
    }

    fn render_record(&self, record: &Record) -> Result<TokenStream> {
        let ident = rust_ident(record.name());
        let fields = record
            .fields()
            .iter()
            .map(|field| self.render_record_field(field))
            .collect::<Result<Vec<_>>>()?;
        let into_core_fields = record
            .fields()
            .iter()
            .map(|field| {
                let field_ident = rust_ident(field.name());
                let expr = self.lower_value_expr(quote!(value.#field_ident), &field.as_type())?;
                Ok(quote!(#field_ident: #expr))
            })
            .collect::<Result<Vec<_>>>()?;
        let from_core_fields = record
            .fields()
            .iter()
            .map(|field| {
                let field_ident = rust_ident(field.name());
                let expr = self.lift_value_expr(quote!(value.#field_ident), &field.as_type())?;
                Ok(quote!(#field_ident: #expr))
            })
            .collect::<Result<Vec<_>>>()?;
        let core_path = self.core_type_path(record.as_type());

        Ok(quote! {
            #[napi(object)]
            #[derive(Clone, Debug)]
            pub struct #ident {
                #(#fields,)*
            }

            impl From<#ident> for #core_path {
                fn from(value: #ident) -> Self {
                    Self {
                        #(#into_core_fields,)*
                    }
                }
            }

            impl From<#core_path> for #ident {
                fn from(value: #core_path) -> Self {
                    Self {
                        #(#from_core_fields,)*
                    }
                }
            }
        })
    }

    fn render_record_field(&self, field: &Field) -> Result<TokenStream> {
        let ident = rust_ident(field.name());
        let ty = self.bridge_value_type(&field.as_type())?;
        Ok(quote!(pub #ident: #ty))
    }

    fn render_enum(&self, enum_: &Enum) -> Result<TokenStream> {
        let ident = rust_ident(enum_.name());
        let variants = enum_
            .variants()
            .iter()
            .map(|variant| self.render_enum_variant(variant))
            .collect::<Result<Vec<_>>>()?;
        let into_variants = enum_
            .variants()
            .iter()
            .map(|variant| self.render_into_core_variant(enum_, variant))
            .collect::<Result<Vec<_>>>()?;
        let from_variants = enum_
            .variants()
            .iter()
            .map(|variant| self.render_from_core_variant(enum_, variant))
            .collect::<Result<Vec<_>>>()?;
        let core_path = self.core_type_path(enum_.as_type());

        // `discriminant = "type"` is only valid for tagged unions in
        // napi-rs 3.x (variants carrying payload). For C-style enums
        // (all unit variants), emit a plain `#[napi]` — otherwise the
        // macro rejects the attribute with "unused #[napi] attribute"
        // and the enum type is dropped from the expansion.
        let has_payload = enum_.variants().iter().any(|v| !v.fields().is_empty());
        let napi_attr = if has_payload {
            quote!(#[napi(discriminant = "type")])
        } else {
            quote!(#[napi])
        };

        Ok(quote! {
            #napi_attr
            #[derive(Clone, Debug)]
            pub enum #ident {
                #(#variants,)*
            }

            impl From<#ident> for #core_path {
                fn from(value: #ident) -> Self {
                    match value {
                        #(#into_variants,)*
                    }
                }
            }

            impl From<#core_path> for #ident {
                fn from(value: #core_path) -> Self {
                    match value {
                        #(#from_variants,)*
                    }
                }
            }
        })
    }

    fn render_enum_variant(&self, variant: &Variant) -> Result<TokenStream> {
        let ident = rust_ident(variant.name());
        if variant.fields().is_empty() {
            return Ok(quote!(#ident));
        }
        let fields = variant
            .fields()
            .iter()
            .map(|field| {
                let field_ident = rust_ident(field.name());
                let field_ty = self.bridge_value_type(&field.as_type())?;
                Ok(quote!(#field_ident: #field_ty))
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(quote!(#ident { #(#fields),* }))
    }

    fn render_into_core_variant(&self, enum_: &Enum, variant: &Variant) -> Result<TokenStream> {
        let bridge_enum = rust_ident(enum_.name());
        let core_enum = self.core_type_path(enum_.as_type());
        let variant_ident = rust_ident(variant.name());
        if variant.fields().is_empty() {
            return Ok(quote!(#bridge_enum::#variant_ident => #core_enum::#variant_ident));
        }
        let bindings = variant
            .fields()
            .iter()
            .map(|field| rust_ident(field.name()))
            .collect::<Vec<_>>();
        let lowers = variant
            .fields()
            .iter()
            .map(|field| {
                let field_ident = rust_ident(field.name());
                let expr = self.lower_value_expr(quote!(#field_ident), &field.as_type())?;
                Ok(quote!(#field_ident: #expr))
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(quote!(
            #bridge_enum::#variant_ident { #(#bindings),* } => #core_enum::#variant_ident {
                #(#lowers),*
            }
        ))
    }

    fn render_from_core_variant(&self, enum_: &Enum, variant: &Variant) -> Result<TokenStream> {
        let bridge_enum = rust_ident(enum_.name());
        let core_enum = self.core_type_path(enum_.as_type());
        let variant_ident = rust_ident(variant.name());
        if variant.fields().is_empty() {
            return Ok(quote!(#core_enum::#variant_ident => #bridge_enum::#variant_ident));
        }
        let bindings = variant
            .fields()
            .iter()
            .map(|field| rust_ident(field.name()))
            .collect::<Vec<_>>();
        let lifts = variant
            .fields()
            .iter()
            .map(|field| {
                let field_ident = rust_ident(field.name());
                let expr = self.lift_value_expr(quote!(#field_ident), &field.as_type())?;
                Ok(quote!(#field_ident: #expr))
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(quote!(
            #core_enum::#variant_ident { #(#bindings),* } => #bridge_enum::#variant_ident {
                #(#lifts),*
            }
        ))
    }

    fn render_object(&self, object: &Object) -> Result<TokenStream> {
        match object.imp() {
            ObjectImpl::Struct | ObjectImpl::Trait => self.render_object_class(object),
            ObjectImpl::CallbackTrait => self.render_callback_trait(object),
        }
    }

    fn render_object_class(&self, object: &Object) -> Result<TokenStream> {
        let ident = rust_ident(object.name());
        let inner_type = self.core_object_inner_type(object);
        let constructors = object
            .constructors()
            .into_iter()
            .map(|constructor| self.render_constructor(object, constructor))
            .collect::<Result<Vec<_>>>()?;
        let methods = object
            .methods()
            .into_iter()
            .map(|method| self.render_object_method(method))
            .collect::<Result<Vec<_>>>()?;

        Ok(quote! {
            #[napi]
            pub struct #ident(#inner_type);

            #(#constructors)*
            #(#methods)*
        })
    }

    fn render_callback_trait(&self, object: &Object) -> Result<TokenStream> {
        let ident = rust_ident(object.name());
        let fields = object
            .methods()
            .into_iter()
            .map(|method| self.render_callback_field(method))
            .collect::<Result<Vec<_>>>()?;
        let impl_methods = object
            .methods()
            .into_iter()
            .map(|method| self.render_callback_impl_method(method))
            .collect::<Result<Vec<_>>>()?;
        let core_path = self.core_type_path(object.as_type());

        Ok(quote! {
            #[napi(object, object_to_js = false)]
            pub struct #ident {
                #(#fields,)*
            }

            impl #core_path for #ident {
                #(#impl_methods)*
            }
        })
    }

    fn render_callback_field(&self, method: &Method) -> Result<TokenStream> {
        let field_ident = rust_ident(method.name());
        let tsfn_args = self.callback_tsfn_args(method)?;
        let ts_type = self.callback_ts_type(method)?;
        Ok(quote! {
            #[napi(ts_type = #ts_type)]
            pub #field_ident: ThreadsafeFunction<#tsfn_args>
        })
    }

    fn render_callback_impl_method(&self, method: &Method) -> Result<TokenStream> {
        let method_ident = rust_ident(method.name());
        let args = method
            .arguments()
            .into_iter()
            .map(|arg| {
                let arg_ident = rust_ident(arg.name());
                let arg_ty = self.bridge_value_type(&arg.as_type())?;
                Ok(quote!(#arg_ident: #arg_ty))
            })
            .collect::<Result<Vec<_>>>()?;

        let call_value = self.callback_call_value(method)?;
        Ok(quote! {
            fn #method_ident(&self, #(#args),*) {
                let _ = self.#method_ident.call(Ok(#call_value), ThreadsafeFunctionCallMode::NonBlocking);
            }
        })
    }

    fn render_constructor(
        &self,
        object: &Object,
        constructor: &Constructor,
    ) -> Result<TokenStream> {
        let function_name = format!(
            "{}_{}",
            object.name().to_snake_case(),
            constructor.name().to_snake_case()
        );
        let fn_ident = rust_ident(&function_name);
        let object_ident = rust_ident(object.name());
        let object_ty = object.as_type();
        let core_path = self.core_type_path(object.as_type());
        let args = constructor
            .arguments()
            .into_iter()
            .map(|arg| self.render_signature_arg(arg))
            .collect::<Result<Vec<_>>>()?;
        let lowered = constructor
            .arguments()
            .into_iter()
            .map(|arg| {
                let arg_ident = rust_ident(arg.name());
                self.lower_arg_expr(arg_ident, &arg.as_type())
            })
            .collect::<Result<Vec<_>>>()?;
        let core_fn_ident = rust_ident(constructor.name());

        let call = quote!(#core_path::#core_fn_ident(#(#lowered),*));
        let call = if constructor.is_async() {
            quote!(#call.await)
        } else {
            call
        };
        let body = self.render_result_body(call, Some(&object_ty), constructor.throws_type())?;

        if constructor.is_async() {
            Ok(quote! {
                #[napi]
                pub async fn #fn_ident(#(#args),*) -> Result<#object_ident> {
                    #body
                }
            })
        } else {
            Ok(quote! {
                #[napi]
                pub fn #fn_ident(#(#args),*) -> Result<#object_ident> {
                    #body
                }
            })
        }
    }

    fn render_object_method(&self, method: &Method) -> Result<TokenStream> {
        let object_ident = rust_ident(method.object_name());
        let function_name = format!(
            "{}_{}",
            method.object_name().to_snake_case(),
            method.name().to_snake_case()
        );
        let fn_ident = rust_ident(&function_name);
        let method_ident = rust_ident(method.name());
        let receiver_ident = rust_ident("handle");
        let args = method
            .arguments()
            .into_iter()
            .map(|arg| self.render_signature_arg(arg))
            .collect::<Result<Vec<_>>>()?;
        let lowered = method
            .arguments()
            .into_iter()
            .map(|arg| {
                let arg_ident = rust_ident(arg.name());
                self.lower_arg_expr(arg_ident, &arg.as_type())
            })
            .collect::<Result<Vec<_>>>()?;
        let receiver = if method.takes_self_by_arc() {
            quote!((*(#receiver_ident)).0.clone())
        } else {
            quote!((*(#receiver_ident)).0.as_ref())
        };
        let call = quote!(#receiver.#method_ident(#(#lowered),*));
        let call = if method.is_async() {
            quote!(#call.await)
        } else {
            call
        };
        let output_ty = match method.return_type() {
            Some(return_type) => self.bridge_return_type(return_type)?,
            None => quote!(()),
        };
        let body = self.render_result_body(call, method.return_type(), method.throws_type())?;

        if method.is_async() {
            Ok(quote! {
                #[napi]
                pub async fn #fn_ident(#receiver_ident: ClassInstance<#object_ident>, #(#args),*) -> Result<#output_ty> {
                    #body
                }
            })
        } else {
            Ok(quote! {
                #[napi]
                pub fn #fn_ident(#receiver_ident: ClassInstance<#object_ident>, #(#args),*) -> Result<#output_ty> {
                    #body
                }
            })
        }
    }

    fn render_function(&self, function: &Function) -> Result<TokenStream> {
        let fn_ident = rust_ident(function.name());
        let fn_path = self.core_item_path(self.ci.crate_name(), function.name());
        let args = function
            .arguments()
            .into_iter()
            .map(|arg| self.render_signature_arg(arg))
            .collect::<Result<Vec<_>>>()?;
        let lowered = function
            .arguments()
            .into_iter()
            .map(|arg| {
                let arg_ident = rust_ident(arg.name());
                self.lower_arg_expr(arg_ident, &arg.as_type())
            })
            .collect::<Result<Vec<_>>>()?;
        let call = quote!(#fn_path(#(#lowered),*));
        let call = if function.is_async() {
            quote!(#call.await)
        } else {
            call
        };
        let output_ty = match function.return_type() {
            Some(return_type) => self.bridge_return_type(return_type)?,
            None => quote!(()),
        };
        let body = self.render_result_body(call, function.return_type(), function.throws_type())?;

        if function.is_async() {
            Ok(quote! {
                #[napi]
                pub async fn #fn_ident(#(#args),*) -> Result<#output_ty> {
                    #body
                }
            })
        } else {
            Ok(quote! {
                #[napi]
                pub fn #fn_ident(#(#args),*) -> Result<#output_ty> {
                    #body
                }
            })
        }
    }

    fn render_signature_arg(&self, arg: &Argument) -> Result<TokenStream> {
        let ident = rust_ident(arg.name());
        let ty = self.bridge_arg_type(&arg.as_type())?;
        Ok(quote!(#ident: #ty))
    }

    fn render_result_body(
        &self,
        call: TokenStream,
        return_type: Option<&Type>,
        throws_type: Option<&Type>,
    ) -> Result<TokenStream> {
        match (return_type, throws_type) {
            (Some(return_type), Some(_)) => {
                let lifted = self.lift_value_expr(quote!(value), return_type)?;
                Ok(quote! {
                    match #call {
                        Ok(value) => Ok(#lifted),
                        Err(err) => Err(into_napi_error(err)),
                    }
                })
            }
            (Some(return_type), None) => {
                let lifted = self.lift_value_expr(call, return_type)?;
                Ok(quote!(Ok(#lifted)))
            }
            (None, Some(_)) => Ok(quote!(#call.map_err(into_napi_error))),
            (None, None) => Ok(quote!(Ok(#call))),
        }
    }

    fn bridge_arg_type(&self, ty: &Type) -> Result<TokenStream> {
        match ty {
            Type::Object { name, imp, .. } => {
                let ident = rust_ident(name);
                match imp {
                    ObjectImpl::Struct | ObjectImpl::Trait => Ok(quote!(ClassInstance<#ident>)),
                    ObjectImpl::CallbackTrait => Ok(quote!(#ident)),
                }
            }
            Type::Optional { inner_type } => {
                let inner = self.bridge_arg_type(inner_type)?;
                Ok(quote!(Option<#inner>))
            }
            Type::Sequence { inner_type } => {
                let inner = self.bridge_arg_type(inner_type)?;
                Ok(quote!(Vec<#inner>))
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                let key = self.bridge_value_type(key_type)?;
                let value = self.bridge_value_type(value_type)?;
                Ok(quote!(std::collections::HashMap<#key, #value>))
            }
            _ => self.bridge_value_type(ty),
        }
    }

    fn bridge_return_type(&self, ty: &Type) -> Result<TokenStream> {
        match ty {
            Type::Optional { inner_type } => {
                let inner = self.bridge_return_type(inner_type)?;
                Ok(quote!(Option<#inner>))
            }
            Type::Sequence { inner_type } => {
                let inner = self.bridge_return_type(inner_type)?;
                Ok(quote!(Vec<#inner>))
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                let key = self.bridge_value_type(key_type)?;
                let value = self.bridge_return_type(value_type)?;
                Ok(quote!(std::collections::HashMap<#key, #value>))
            }
            _ => self.bridge_value_type(ty),
        }
    }

    fn bridge_value_type(&self, ty: &Type) -> Result<TokenStream> {
        match ty {
            Type::UInt8 => Ok(quote!(u8)),
            Type::Int8 => Ok(quote!(i8)),
            Type::UInt16 => Ok(quote!(u16)),
            Type::Int16 => Ok(quote!(i16)),
            Type::UInt32 => Ok(quote!(u32)),
            Type::Int32 => Ok(quote!(i32)),
            Type::UInt64 | Type::Int64 => Ok(quote!(napi::bindgen_prelude::BigInt)),
            Type::Float32 => Ok(quote!(f32)),
            Type::Float64 => Ok(quote!(f64)),
            Type::Boolean => Ok(quote!(bool)),
            Type::String => Ok(quote!(String)),
            Type::Bytes => Ok(quote!(Buffer)),
            Type::Record { name, .. } | Type::Enum { name, .. } => {
                let ident = rust_ident(name);
                Ok(quote!(#ident))
            }
            Type::Object { name, imp, .. } => match imp {
                ObjectImpl::Struct | ObjectImpl::Trait => {
                    let ident = rust_ident(name);
                    Ok(quote!(#ident))
                }
                ObjectImpl::CallbackTrait => {
                    bail!("callback trait `{name}` is not supported as a nested or return value")
                }
            },
            Type::Optional { inner_type } => {
                let inner = self.bridge_value_type(inner_type)?;
                Ok(quote!(Option<#inner>))
            }
            Type::Sequence { inner_type } => {
                let inner = self.bridge_value_type(inner_type)?;
                Ok(quote!(Vec<#inner>))
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                let key = self.bridge_value_type(key_type)?;
                let value = self.bridge_value_type(value_type)?;
                Ok(quote!(std::collections::HashMap<#key, #value>))
            }
            Type::Timestamp => Ok(quote!(__UniffiTimestamp)),
            Type::Duration => Ok(quote!(__UniffiDuration)),
            Type::CallbackInterface { name, .. } => {
                bail!("callback interface `{name}` is not supported directly")
            }
            Type::Custom { builtin, .. } => self.bridge_value_type(builtin),
        }
    }

    fn lower_arg_expr(&self, ident: syn::Ident, ty: &Type) -> Result<TokenStream> {
        match ty {
            // u64/i64 cross the napi boundary as BigInt (JS `bigint`).
            // napi-rs does not impl FromNapiValue for u64, and i64 maps
            // to JS `number` which loses precision. BigInt keeps the raw
            // addon surface aligned with the public bigint-first contract.
            Type::UInt64 => Ok(quote!({
                let (__sign, __val, __lossless) = #ident.get_u64();
                if __sign && __val != 0 {
                    return Err(napi::Error::new(napi::Status::InvalidArg, "negative value cannot be converted to u64"));
                }
                if !__lossless {
                    return Err(napi::Error::new(napi::Status::InvalidArg, "BigInt value does not fit into u64"));
                }
                __val
            })),
            Type::Int64 => {
                let lowered = self.lower_value_expr(quote!(#ident), &Type::Int64)?;
                Ok(lowered)
            }
            Type::Object { imp, .. } => match imp {
                ObjectImpl::Struct | ObjectImpl::Trait => Ok(quote!((*(#ident)).0.clone())),
                ObjectImpl::CallbackTrait => {
                    let trait_path = self.core_type_path(ty.clone());
                    Ok(quote!(std::sync::Arc::new(#ident) as std::sync::Arc<dyn #trait_path>))
                }
            },
            _ => self.lower_value_expr(quote!(#ident), ty),
        }
    }

    fn lower_value_expr(&self, expr: TokenStream, ty: &Type) -> Result<TokenStream> {
        match ty {
            Type::UInt8
            | Type::Int8
            | Type::UInt16
            | Type::Int16
            | Type::UInt32
            | Type::Int32
            | Type::Float32
            | Type::Float64
            | Type::Boolean
            | Type::String => Ok(expr),
            // BigInt → u64: reject negative and out-of-range values.
            Type::UInt64 => Ok(quote!({
                let __big = #expr;
                let (__sign, __val, __lossless) = __big.get_u64();
                if __sign && __val != 0 {
                    return Err(napi::Error::new(napi::Status::InvalidArg, "negative value cannot be converted to u64"));
                }
                if !__lossless {
                    return Err(napi::Error::new(napi::Status::InvalidArg, "BigInt value does not fit into u64"));
                }
                __val
            })),
            // BigInt → i64: reject values outside the i64 range.
            Type::Int64 => Ok(quote!({
                let __big = #expr;
                let (__val, __lossless) = __big.get_i64();
                if !__lossless {
                    return Err(napi::Error::new(napi::Status::InvalidArg, "BigInt value does not fit into i64"));
                }
                __val
            })),
            Type::Bytes => Ok(quote!(#expr.into())),
            Type::Record { .. } | Type::Enum { .. } => Ok(quote!(#expr.into())),
            Type::Object { imp, .. } => match imp {
                ObjectImpl::Struct | ObjectImpl::Trait => Ok(quote!(#expr.0.clone())),
                ObjectImpl::CallbackTrait => bail!("callback traits are not supported here"),
            },
            Type::Optional { inner_type } => {
                let inner = self.lower_value_expr(quote!(value), inner_type)?;
                Ok(quote!(#expr.map(|value| { #inner })))
            }
            Type::Sequence { inner_type } => {
                let inner = self.lower_value_expr(quote!(value), inner_type)?;
                Ok(quote!(#expr.into_iter().map(|value| { #inner }).collect()))
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                let key = self.lower_value_expr(quote!(key), key_type)?;
                let value = self.lower_value_expr(quote!(value), value_type)?;
                Ok(quote!(
                    #expr
                        .into_iter()
                        .map(|(key, value)| ({ #key }, { #value }))
                        .collect()
                ))
            }
            Type::Timestamp => Ok(quote!(#expr.0)),
            Type::Duration => Ok(quote!(#expr.0)),
            Type::CallbackInterface { name, .. } => {
                bail!("callback interface `{name}` is not supported directly")
            }
            Type::Custom {
                module_path,
                builtin,
                ..
            } => {
                let builtin_lower = self.lower_value_expr(expr, builtin)?;
                let builtin_ty = self.bridge_value_type(builtin)?;
                let custom_ty = self.core_type_path(ty.clone());
                let tag_ty = self.core_tag_path(module_path);
                Ok(quote!({
                    let __builtin = { #builtin_lower };
                    let __ffi = <#builtin_ty as ::uniffi::Lower<#tag_ty>>::lower(__builtin);
                    <#custom_ty as ::uniffi::Lift<#tag_ty>>::try_lift(__ffi)
                        .expect("uniffi napi custom type lift failed")
                }))
            }
        }
    }

    fn lift_value_expr(&self, expr: TokenStream, ty: &Type) -> Result<TokenStream> {
        match ty {
            Type::UInt8
            | Type::Int8
            | Type::UInt16
            | Type::Int16
            | Type::UInt32
            | Type::Int32
            | Type::Float32
            | Type::Float64
            | Type::Boolean
            | Type::String => Ok(expr),
            // u64/i64 → BigInt for JS `bigint`.
            Type::UInt64 | Type::Int64 => Ok(quote!(napi::bindgen_prelude::BigInt::from(#expr))),
            Type::Bytes => Ok(quote!(#expr.into())),
            Type::Record { .. } | Type::Enum { .. } => Ok(quote!(#expr.into())),
            Type::Object { name, imp, .. } => match imp {
                ObjectImpl::Struct | ObjectImpl::Trait => {
                    let ident = rust_ident(name);
                    Ok(quote!(#ident(#expr)))
                }
                ObjectImpl::CallbackTrait => bail!(
                    "callback trait `{name}` cannot be returned to JavaScript in the napi bridge"
                ),
            },
            Type::Optional { inner_type } => {
                let inner = self.lift_value_expr(quote!(value), inner_type)?;
                Ok(quote!(#expr.map(|value| { #inner })))
            }
            Type::Sequence { inner_type } => {
                let inner = self.lift_value_expr(quote!(value), inner_type)?;
                Ok(quote!(#expr.into_iter().map(|value| { #inner }).collect()))
            }
            Type::Map {
                key_type,
                value_type,
            } => {
                let key = self.lift_value_expr(quote!(key), key_type)?;
                let value = self.lift_value_expr(quote!(value), value_type)?;
                Ok(quote!(
                    #expr
                        .into_iter()
                        .map(|(key, value)| ({ #key }, { #value }))
                        .collect()
                ))
            }
            Type::Timestamp => Ok(quote!(__UniffiTimestamp(#expr))),
            Type::Duration => Ok(quote!(__UniffiDuration(#expr))),
            Type::CallbackInterface { name, .. } => {
                bail!("callback interface `{name}` cannot be returned directly")
            }
            Type::Custom { module_path, .. } => {
                let custom_ty = self.core_type_path(ty.clone());
                let tag_ty = self.core_tag_path(module_path);
                let builtin = match ty {
                    Type::Custom { builtin, .. } => builtin.as_ref(),
                    _ => unreachable!(),
                };
                let builtin_ty = self.bridge_value_type(builtin)?;
                let builtin_value = quote!({
                    let __builtin = <#builtin_ty as ::uniffi::Lift<#tag_ty>>::try_lift(
                        <#custom_ty as ::uniffi::Lower<#tag_ty>>::lower(#expr),
                    )
                    .expect("uniffi napi custom type lift failed");
                    __builtin
                });
                self.lift_value_expr(builtin_value, builtin)
            }
        }
    }

    fn callback_tsfn_args(&self, method: &Method) -> Result<TokenStream> {
        match method.arguments().as_slice() {
            [] => Ok(quote!(())),
            [arg] => self.bridge_value_type(&arg.as_type()),
            args => {
                let tys = args
                    .iter()
                    .map(|arg| self.bridge_value_type(&arg.as_type()))
                    .collect::<Result<Vec<_>>>()?;
                Ok(quote!(FnArgs<(#(#tys),*)>))
            }
        }
    }

    fn callback_call_value(&self, method: &Method) -> Result<TokenStream> {
        let args = method
            .arguments()
            .into_iter()
            .map(|arg| rust_ident(arg.name()))
            .collect::<Vec<_>>();
        match args.as_slice() {
            [] => Ok(quote!(())),
            [arg] => Ok(quote!(#arg)),
            _ => Ok(quote!((#(#args),*).into())),
        }
    }

    fn callback_ts_type(&self, method: &Method) -> Result<String> {
        let mut parts = Vec::new();
        for arg in method.arguments() {
            let name = arg.name();
            let ty = self.ts_type(&arg.as_type())?;
            parts.push(format!("{name}: {ty}"));
        }
        Ok(format!("({}) => void", parts.join(", ")))
    }

    fn ts_type(&self, ty: &Type) -> Result<String> {
        match ty {
            Type::UInt8
            | Type::Int8
            | Type::UInt16
            | Type::Int16
            | Type::UInt32
            | Type::Int32
            | Type::Float32
            | Type::Float64 => Ok("number".to_string()),
            Type::UInt64 | Type::Int64 => Ok("bigint".to_string()),
            Type::Boolean => Ok("boolean".to_string()),
            Type::String => Ok("string".to_string()),
            Type::Bytes => Ok("Buffer".to_string()),
            Type::Record { name, .. } | Type::Enum { name, .. } | Type::Object { name, .. } => {
                Ok(name.to_string())
            }
            Type::Optional { inner_type } => {
                Ok(format!("{} | null | undefined", self.ts_type(inner_type)?))
            }
            Type::Sequence { inner_type } => Ok(format!("Array<{}>", self.ts_type(inner_type)?)),
            Type::Map {
                key_type,
                value_type,
            } => Ok(format!(
                "Map<{}, {}>",
                self.ts_type(key_type)?,
                self.ts_type(value_type)?
            )),
            Type::Timestamp => Ok("Date".to_string()),
            Type::Duration => Ok("number".to_string()),
            Type::CallbackInterface { name, .. } => {
                bail!("callback interface `{name}` ts type is not supported")
            }
            Type::Custom { name, .. } => Ok(name.to_string()),
        }
    }

    fn core_object_inner_type(&self, object: &Object) -> TokenStream {
        let core_path = self.core_type_path(object.as_type());
        match object.imp() {
            ObjectImpl::Struct => quote!(std::sync::Arc<#core_path>),
            ObjectImpl::Trait | ObjectImpl::CallbackTrait => {
                quote!(std::sync::Arc<dyn #core_path>)
            }
        }
    }

    fn core_item_path(&self, module_path: &str, name: &str) -> TokenStream {
        let module = rust_path(module_path);
        let ident = rust_ident(name);
        quote!(#module::#ident)
    }

    fn core_type_path(&self, ty: Type) -> TokenStream {
        match ty {
            Type::Record { module_path, name }
            | Type::Enum { module_path, name }
            | Type::CallbackInterface { module_path, name }
            | Type::Object {
                module_path, name, ..
            }
            | Type::Custom {
                module_path, name, ..
            } => {
                let module = rust_path(&module_path);
                let ident = rust_ident(&name);
                quote!(#module::#ident)
            }
            _ => unreachable!("core_type_path only supports named types"),
        }
    }

    fn core_tag_path(&self, module_path: &str) -> TokenStream {
        let crate_root = module_path
            .split("::")
            .next()
            .expect("custom type module path should have a crate root");
        let root = rust_ident(crate_root);
        quote!(#root::UniFfiTag)
    }
}

#[derive(Clone, Copy)]
enum TypeUsage {
    Arg,
    Return,
    Value,
    CallbackArg,
    Error,
}

fn rust_ident(name: &str) -> syn::Ident {
    syn::parse_str::<syn::Ident>(name)
        .or_else(|_| syn::parse_str::<syn::Ident>(&format!("r#{name}")))
        .unwrap_or_else(|_| format_ident!("__uniffi_{}", sanitize_ident(name)))
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn rust_path(path: &str) -> TokenStream {
    let segments = path.split("::").map(rust_ident).collect::<Vec<_>>();
    quote!(#(#segments)::*)
}
