/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Napi flavor backend.
//!
//! The heavy lifting (Rust codegen via proc-macro2/quote, type lowering/
//! lifting, callback trait bridging, async handling) lives in
//! `codegen.rs`; this module owns the file layout and the thin JS
//! adapter that satisfies the high-level TS API.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;
use uniffi_bindgen::Component;

use crate::JsConfig;

pub(crate) mod codegen;

pub fn emit(dir: &Utf8Path, component: &Component<JsConfig>) -> Result<()> {
    let ci = &component.ci;

    // 1. Rust napi bridge — one .rs file per component crate, to be included
    //    by the host `.node` crate via `include!` or `mod`.
    let rust_source = codegen::render_napi_rust(ci)?;
    let rust_path = dir.join(format!("{}.rs", ci.crate_name()));
    fs::write(rust_path, rust_source)?;

    // 2. JS adapter that imports the compiled `.node` addon and re-exports
    //    it under the names the high-level common/*.ts layer expects. The
    //    adapter is intentionally thin: every non-trivial conversion lives
    //    in `uniffi_runtime_javascript`.
    let adapter = render_backend_adapter(ci);
    fs::write(dir.join("backend-napi.ts"), adapter)?;

    // 3. Flavor entry point — the only file the application imports.
    //    Re-exports the high-level API from ../common wired through the
    //    backend adapter above.
    let index = render_index(ci);
    fs::write(dir.join("index.ts"), index)?;
    Ok(())
}

fn render_backend_adapter(ci: &uniffi_bindgen::ComponentInterface) -> String {
    let namespace = ci.namespace();
    let env_var = napi_path_env_var(namespace);
    let name_map_literal =
        crate::name_map::render_name_map_js_literal(&crate::name_map::collect(ci));
    let enum_shape_helpers = crate::enum_shape::helper_ts();
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (napi flavor).\n\
         //\n\
         // This file loads the compiled `.node` addon produced from the\n\
         // generated `{namespace}.rs` bridge and exposes its symbols under\n\
         // the low-level FFI contract defined in\n\
         // `uniffi_runtime_javascript`. The high-level API in\n\
         // `../common/api.ts` is identical to every other flavor and\n\
         // imports this adapter only through that contract.\n\
         \n\
         import {{ createRequire }} from \"node:module\";\n\
         import {{ resolve }} from \"node:path\";\n\
         const require = createRequire(import.meta.url);\n\
         const __uniffiNamespace = \"{namespace}\";\n\
         const __uniffiSpecificNapiPathEnv = \"{env_var}\";\n\
         const __uniffiDefaultAddonPath = \"./{namespace}.node\";\n\
         \n\
         function __uniffiResolveEnvAddonPath(path: string): string {{\n\
             return path.startsWith(\"/\") || /^[A-Za-z]:[\\\\/]/.test(path) ? path : resolve(path);\n\
         }}\n\
         \n\
         function __uniffiAddonCandidate(): {{ label: string; specifier: string }} {{\n\
             const specific = process.env[__uniffiSpecificNapiPathEnv];\n\
             if (specific && specific.length > 0) {{\n\
                 return {{ label: __uniffiSpecificNapiPathEnv, specifier: __uniffiResolveEnvAddonPath(specific) }};\n\
             }}\n\
             const generic = process.env.UNIFFI_NAPI_PATH;\n\
             if (generic && generic.length > 0) {{\n\
                 return {{ label: \"UNIFFI_NAPI_PATH\", specifier: __uniffiResolveEnvAddonPath(generic) }};\n\
             }}\n\
             return {{ label: \"default\", specifier: __uniffiDefaultAddonPath }};\n\
         }}\n\
         \n\
         function __uniffiLoadNativeAddon(): Record<string, unknown> {{\n\
             const candidate = __uniffiAddonCandidate();\n\
             try {{\n\
                 return require(candidate.specifier) as Record<string, unknown>;\n\
             }} catch (error) {{\n\
                 const cause = error instanceof Error ? `${{error.name}}: ${{error.message}}` : String(error);\n\
                 throw new Error(\n\
                     `failed to load UniFFI N-API addon for namespace \"${{__uniffiNamespace}}\" from ${{candidate.label}} (${{candidate.specifier}}). ` +\n\
                         `Run \"uniffi-bindgen javascript build-napi --manifest-path <Cargo.toml> --out-dir <generated>\" ` +\n\
                         `so ${{__uniffiDefaultAddonPath}} exists, or set ${{__uniffiSpecificNapiPathEnv}}=/absolute/path/to/${{__uniffiNamespace}}.node ` +\n\
                         `or UNIFFI_NAPI_PATH=/absolute/path/to/addon.node. Cause: ${{cause}}`,\n\
                 );\n\
             }}\n\
         }}\n\
         \n\
         const native = __uniffiLoadNativeAddon();\n\
         \n\
         // Generator-computed map from `common/api.ts` low-level\n\
         // snake_case dispatch keys to the `lowerCamelCase` names that\n\
         // napi-rs actually exports on the `.node` addon. Keeping this\n\
         // as a static literal (not a runtime heuristic) means the two\n\
         // sides can't drift: `name_map::collect` walks the same IR\n\
         // shape `api_module/mod.rs` walks.\n\
         const __uniffiNameMap: Record<string, string> = {name_map_literal} as Record<string, string>;\n\
         \n\
         {enum_shape_helpers}\n\
         \n\
         function __uniffiIsObjectFreeKey(name: string): boolean {{\n\
             return name.startsWith(\"__uniffi_\") && name.endsWith(\"_object_free\");\n\
         }}\n\
         \n\
         function __uniffiCallbackErrorPayload(error: unknown, shape: unknown): unknown {{\n\
             if (error !== null && typeof error === \"object\") {{\n\
                 const raw = error as Record<string, unknown>;\n\
                 if (shape === \"flat\") {{\n\
                     if (typeof raw.variant === \"string\") return raw.variant;\n\
                     if (typeof raw.tag === \"string\") return raw.tag;\n\
                     if (typeof raw.type === \"string\") return raw.type;\n\
                 }}\n\
                 if (typeof raw.tag === \"string\" || typeof raw.type === \"string\") {{\n\
                     return __uniffiLowerShape(raw);\n\
                 }}\n\
                 if (typeof raw.variant === \"string\") {{\n\
                     const data = raw.data;\n\
                     const payload: Record<string, unknown> = {{ tag: raw.variant }};\n\
                     if (data !== null && typeof data === \"object\" && !Array.isArray(data)) {{\n\
                         Object.assign(payload, data as Record<string, unknown>);\n\
                     }}\n\
                     return __uniffiLowerShape(payload);\n\
                 }}\n\
             }}\n\
             throw error;\n\
         }}\n\
         \n\
         const __uniffiReturnedCallbacks = new Map<number, Record<string, unknown>>();\n\
         let __uniffiNextReturnedCallbackId = 1;\n\
         \n\
         function __uniffiDispatchReturnedCallback(...rawArgs: unknown[]): unknown {{\n\
             const args = rawArgs.length >= 3 && (rawArgs[0] === null || rawArgs[0] === undefined || rawArgs[0] instanceof Error)\n\
                 ? rawArgs.slice(1)\n\
                 : rawArgs;\n\
             const id = args[0];\n\
             const method = args[1];\n\
             if (typeof id !== \"number\" || typeof method !== \"string\") {{\n\
                 throw new Error(\"invalid uniffi returned-callback dispatch arguments\");\n\
             }}\n\
             const obj = __uniffiReturnedCallbacks.get(id);\n\
             if (!obj) {{\n\
                 throw new Error(`uniffi returned callback ${{id}} is not available`);\n\
             }}\n\
             const fn = obj[method];\n\
             if (typeof fn !== \"function\") {{\n\
                 throw new Error(`uniffi returned callback ${{id}} has no method ${{method}}`);\n\
             }}\n\
             return (fn as (...a: unknown[]) => unknown)(...args.slice(2));\n\
         }}\n\
         \n\
         function __uniffiStoreCallbackReturn(value: unknown): {{ id: number }} {{\n\
             const marker = value !== null && typeof value === \"object\" && (value as {{ __uniffiCallback?: boolean }}).__uniffiCallback === true\n\
                 ? value as {{ object: unknown, fallibleMethods?: Record<string, string>, asyncMethods?: Record<string, boolean>, callbackReturnMethods?: Record<string, boolean> }}\n\
                 : undefined;\n\
             const obj = marker === undefined\n\
                 ? __uniffiNormalizeCallbackObject(value)\n\
                 : __uniffiNormalizeCallbackObject(marker.object, marker);\n\
             const id = __uniffiNextReturnedCallbackId++;\n\
             __uniffiReturnedCallbacks.set(id, obj as Record<string, unknown>);\n\
             return {{ id }};\n\
         }}\n\
         \n\
         function __uniffiNormalizeCallbackObject(obj: unknown, marker?: {{ fallibleMethods?: Record<string, string>, asyncMethods?: Record<string, boolean>, callbackReturnMethods?: Record<string, boolean> }}): unknown {{\n\
             if (obj === null || typeof obj !== \"object\") return obj;\n\
             const fallibleMethods = marker?.fallibleMethods ?? {{}};\n\
             const asyncMethods = marker?.asyncMethods ?? {{}};\n\
             const callbackReturnMethods = marker?.callbackReturnMethods ?? {{}};\n\
             const out: Record<string, unknown> = {{}};\n\
             for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {{\n\
                 if (typeof v === \"function\") {{\n\
                     out[k] = (...args: unknown[]) => {{\n\
                         const callArgs = args.length >= 2 && (args[0] === null || args[0] === undefined || args[0] instanceof Error)\n\
                             ? args.slice(1)\n\
                             : args;\n\
                         const fn = v as (...a: unknown[]) => unknown;\n\
                         const errorShape = fallibleMethods[k];\n\
                         const isAsync = asyncMethods[k] === true;\n\
                         const returnsCallback = callbackReturnMethods[k] === true;\n\
                         if (!errorShape) {{\n\
                             if (isAsync) {{\n\
                                 return Promise.resolve(fn(...callArgs)).then((value) => returnsCallback ? __uniffiStoreCallbackReturn(value) : __uniffiLowerShape(value));\n\
                             }}\n\
                             return __uniffiLowerShape(fn(...callArgs));\n\
                         }}\n\
                         if (isAsync) {{\n\
                             return Promise.resolve(fn(...callArgs)).then(\n\
                                 (value) => ({{ ok: true, value: returnsCallback ? __uniffiStoreCallbackReturn(value) : __uniffiLowerShape(value) }}),\n\
                                 (error) => ({{ ok: false, error: __uniffiCallbackErrorPayload(error, errorShape) }}),\n\
                             );\n\
                         }}\n\
                         try {{\n\
                             return {{ ok: true, value: __uniffiLowerShape(fn(...callArgs)) }};\n\
                         }} catch (error) {{\n\
                             return {{ ok: false, error: __uniffiCallbackErrorPayload(error, errorShape) }};\n\
                         }}\n\
                     }};\n\
                 }} else {{\n\
                     out[k] = v;\n\
                 }}\n\
             }}\n\
             out.__uniffiCallbackDispatcher = __uniffiDispatchReturnedCallback;\n\
             return out;\n\
         }}\n\
         \n\
         // Unwrap the tagged callback marker emitted by `common/api.ts`.\n\
         // For napi, `#[napi(object)]` structs with `ThreadsafeFunction`\n\
         // fields want the raw JS object (e.g. `{{ log: fn }}`), not a\n\
         // numeric handle. Other backends (wasm) translate the marker\n\
         // differently; see their adapters.\n\
         const __uniffiCoerce = (a: unknown): unknown => {{\n\
             if (\n\
                 a !== null &&\n\
                 typeof a === \"object\" &&\n\
                 (a as {{ __uniffiCallback?: boolean }}).__uniffiCallback === true\n\
             ) {{\n\
                 return __uniffiNormalizeCallbackObject((a as {{ object: unknown }}).object, a as {{ fallibleMethods?: Record<string, string>, asyncMethods?: Record<string, boolean>, callbackReturnMethods?: Record<string, boolean> }});\n\
             }}\n\
             return a;\n\
         }};\n\
         \n\
         const backend: Record<string, unknown> = new Proxy(\n\
             {{}} as Record<string, unknown>,\n\
             {{\n\
                 get(_t, name: string) {{\n\
                     // `common/objects.ts` uses the wasm registry destructor\n\
                     // key for every flavor. N-API object wrappers are native\n\
                     // class instances whose lifetime is owned by napi-rs/V8,\n\
                     // so the generated backend intentionally treats those\n\
                     // destructor calls as idempotent no-ops.\n\
                     if (__uniffiIsObjectFreeKey(name)) return (_handle: unknown): void => {{}};\n\
                     // Translate low-level key → addon export name. Fall\n\
                     // back to the raw name so anything the generator didn't\n\
                     // put in the map still surfaces a clear `undefined`\n\
                     // rather than silently hitting an unrelated member.\n\
                     const exportName = __uniffiNameMap[name] ?? name;\n\
                     const v = (native as Record<string, unknown>)[exportName];\n\
                     if (typeof v !== \"function\") return v;\n\
                     const fn = v as (...args: unknown[]) => unknown;\n\
                     return (...args: unknown[]) => {{\n\
                         // Lower args on the way in: tag -> type for any\n\
                         // plain object (enum, nested in seq/opt/record).\n\
                         // Callback markers are still unwrapped first so\n\
                         // the lowering skips the `object` payload.\n\
                         const lowered = args.map((a) =>\n\
                             __uniffiLowerShape(__uniffiCoerce(a)),\n\
                         );\n\
                         let result: unknown;\n\
                         try {{\n\
                             result = fn.apply(native, lowered);\n\
                         }} catch (err) {{\n\
                             // napi errors carry an enum payload with `type`;\n\
                             // lift it symmetrically so `common/errors.ts`\n\
                             // consumers see `tag`.\n\
                             throw __uniffiLiftShape(err);\n\
                         }}\n\
                         if (\n\
                             result !== null &&\n\
                             typeof result === \"object\" &&\n\
                             typeof (result as {{ then?: unknown }}).then === \"function\"\n\
                         ) {{\n\
                             return (result as Promise<unknown>).then(\n\
                                 (value) => __uniffiLiftShape(value),\n\
                                 (err) => {{\n\
                                     throw __uniffiLiftShape(err);\n\
                                 }},\n\
                             );\n\
                         }}\n\
                         return __uniffiLiftShape(result);\n\
                     }};\n\
                 }},\n\
             }},\n\
         );\n\
         \n\
         export default backend;\n\
         export {{ native as __uniffiNativeAddon }};\n\
         export const __uniffiBackendKind = \"napi\" as const;\n"
    )
}

fn napi_path_env_var(namespace: &str) -> String {
    let mut out = String::from("UNIFFI_");
    let mut last_was_sep = false;
    for ch in namespace.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            last_was_sep = false;
        } else if !last_was_sep {
            out.push('_');
            last_was_sep = true;
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    out.push_str("_NAPI_PATH");
    out
}

fn render_index(ci: &uniffi_bindgen::ComponentInterface) -> String {
    let namespace = ci.namespace();
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (napi flavor).\n\
         //\n\
         // Node/napi entry for namespace `{namespace}`. Applications\n\
         // import from this file and see the same high-level API as the\n\
         // wasm and electron entries. The backend installs itself on\n\
         // first import so callers never have to plumb it through.\n\
         \n\
         import backend from \"./backend-napi.ts\";\n\
         import {{ __installBackend }} from \"../common/runtime.ts\";\n\
         __installBackend(backend);\n\
         export * from \"../common/api.ts\";\n\
         export {{ backend as __uniffiBackend }};\n"
    )
}
