/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Napi flavor backend.
//!
//! The heavy lifting (Rust codegen via proc-macro2/quote, type lowering/
//! lifting, callback trait bridging, async handling) lives in
//! `codegen.rs`; this module owns the file layout and the thin JS
//! adapter that satisfies the high-level TS API.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;
use heck::ToSnakeCase;
use uniffi_bindgen::Component;
use uniffi_bindgen::interface::AsType;
use uniffi_bindgen::ComponentInterface;
use uniffi_meta::Type;

use crate::JsConfig;

pub(crate) mod codegen;

pub fn emit(dir: &Utf8Path, component: &Component<JsConfig>) -> Result<()> {
    let ci = &component.ci;

    // 1. Rust napi bridge — one .rs file per component crate, to be included
    //    by the host `.node` crate via `include!` or `mod`.
    let rust_source = codegen::render_napi_rust(ci)?;
    let rust_path = dir.join(format!("{}.rs", ci.crate_name()));
    fs::write(rust_path, rust_source)?;

    // 2. JS adapter that imports the compiled `.node` addon and re-exports
    //    it under the names the high-level common/*.ts layer expects. The
    //    adapter is intentionally thin: every non-trivial conversion lives
    //    in `uniffi_runtime_javascript`.
    let adapter = render_backend_adapter(ci);
    fs::write(dir.join("backend-napi.ts"), adapter)?;

    // 3. Flavor entry point — the only file the application imports.
    //    Re-exports the high-level API from ../common wired through the
    //    backend adapter above.
    let index = render_index(ci);
    fs::write(dir.join("index.ts"), index)?;
    Ok(())
}

fn render_backend_adapter(ci: &uniffi_bindgen::ComponentInterface) -> String {
    let namespace = ci.namespace();
    let name_map_literal =
        crate::name_map::render_name_map_js_literal(&crate::name_map::collect(ci));
    let int64_arg_map = render_int64_arg_map_js_literal(ci);
    let int64_ret_map = render_int64_return_map_js_literal(ci);
    let enum_shape_helpers = crate::enum_shape::helper_ts();
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (napi flavor).\n\
         //\n\
         // This file loads the compiled `.node` addon produced from the\n\
         // generated `{namespace}.rs` bridge and exposes its symbols under\n\
         // the low-level FFI contract defined in\n\
         // `uniffi_runtime_javascript`. The high-level API in\n\
         // `../common/api.ts` is identical to every other flavor and\n\
         // imports this adapter only through that contract.\n\
         \n\
         // eslint-disable-next-line @typescript-eslint/no-var-requires\n\
         const native = require(\"./{namespace}.node\");\n\
         \n\
         // Generator-computed map from `common/api.ts` low-level\n\
         // snake_case dispatch keys to the `lowerCamelCase` names that\n\
         // napi-rs actually exports on the `.node` addon. Keeping this\n\
         // as a static literal (not a runtime heuristic) means the two\n\
         // sides can't drift: `name_map::collect` walks the same IR\n\
         // shape `api_module/mod.rs` walks.\n\
         const __uniffiNameMap: Record<string, string> = {name_map_literal} as Record<string, string>;\n\
         const __uniffiInt64ArgKinds: Record<string, Array<\"i64\" | \"u64\" | null>> = {int64_arg_map} as Record<string, Array<\"i64\" | \"u64\" | null>>;\n\
         const __uniffiInt64ReturnKinds: Record<string, \"i64\" | \"u64\"> = {int64_ret_map} as Record<string, \"i64\" | \"u64\">;\n\
         \n\
         {enum_shape_helpers}\n\
         \n\
         const __uniffiMaxSafeBigInt = BigInt(Number.MAX_SAFE_INTEGER);\n\
         const __uniffiMinSafeBigInt = BigInt(Number.MIN_SAFE_INTEGER);\n\
         \n\
         function __uniffiLowerInt64ForNapi(value: unknown, kind: \"i64\" | \"u64\" | null): unknown {{\n\
             if (kind === null) return value;\n\
             if (typeof value === \"bigint\") {{\n\
                 if (kind === \"u64\" && value < 0n) {{\n\
                     throw new RangeError(`negative bigint value ${{value}} cannot be converted to u64`);\n\
                 }}\n\
                 if (value < __uniffiMinSafeBigInt || value > __uniffiMaxSafeBigInt) {{\n\
                     throw new RangeError(`bigint value ${{value}} exceeds the JS safe integer range supported by the current napi bridge`);\n\
                 }}\n\
                 return Number(value);\n\
             }}\n\
             if (typeof value === \"number\") {{\n\
                 if (!Number.isInteger(value) || !Number.isSafeInteger(value)) {{\n\
                     throw new RangeError(`number value ${{value}} is not a safe integer for ${{kind}}`);\n\
                 }}\n\
                 if (kind === \"u64\" && value < 0) {{\n\
                     throw new RangeError(`negative number value ${{value}} cannot be converted to u64`);\n\
                 }}\n\
                 return value;\n\
             }}\n\
             if (typeof value === \"string\") {{\n\
                 return __uniffiLowerInt64ForNapi(BigInt(value), kind);\n\
             }}\n\
             return value;\n\
         }}\n\
         \n\
         function __uniffiLiftInt64FromNapi(value: unknown, kind: \"i64\" | \"u64\" | null): unknown {{\n\
             if (kind === null) return value;\n\
             if (typeof value === \"bigint\") return value;\n\
             if (typeof value === \"number\") {{\n\
                 if (!Number.isInteger(value) || !Number.isSafeInteger(value)) {{\n\
                     throw new RangeError(`number value ${{value}} is not a safe integer result for ${{kind}}`);\n\
                 }}\n\
                 if (kind === \"u64\" && value < 0) {{\n\
                     throw new RangeError(`negative number result ${{value}} cannot be lifted as u64`);\n\
                 }}\n\
                 return BigInt(value);\n\
             }}\n\
             return value;\n\
         }}\n\
         \n\
         function __uniffiNormalizeCallbackObject(obj: unknown): unknown {{\n\
             if (obj === null || typeof obj !== \"object\") return obj;\n\
             const out: Record<string, unknown> = {{}};\n\
             for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {{\n\
                 if (typeof v === \"function\") {{\n\
                     out[k] = (...args: unknown[]) => {{\n\
                         const callArgs = args.length >= 2 && (args[0] === null || args[0] === undefined || args[0] instanceof Error)\n\
                             ? args.slice(1)\n\
                             : args;\n\
                         return (v as (...a: unknown[]) => unknown)(...callArgs);\n\
                     }};\n\
                 }} else {{\n\
                     out[k] = v;\n\
                 }}\n\
             }}\n\
             return out;\n\
         }}\n\
         \n\
         // Unwrap the tagged callback marker emitted by `common/api.ts`.\n\
         // For napi, `#[napi(object)]` structs with `ThreadsafeFunction`\n\
         // fields want the raw JS object (e.g. `{{ log: fn }}`), not a\n\
         // numeric handle. Other backends (wasm) translate the marker\n\
         // differently; see their adapters.\n\
         const __uniffiCoerce = (a: unknown): unknown => {{\n\
             if (\n\
                 a !== null &&\n\
                 typeof a === \"object\" &&\n\
                 (a as {{ __uniffiCallback?: boolean }}).__uniffiCallback === true\n\
             ) {{\n\
                 return __uniffiNormalizeCallbackObject((a as {{ object: unknown }}).object);\n\
             }}\n\
             return a;\n\
         }};\n\
         \n\
         const backend: Record<string, unknown> = new Proxy(\n\
             {{}} as Record<string, unknown>,\n\
             {{\n\
                 get(_t, name: string) {{\n\
                     // Translate low-level key → addon export name. Fall\n\
                     // back to the raw name so destructors / anything\n\
                     // the generator didn't put in the map still\n\
                     // surface a clear `undefined` rather than silently\n\
                     // hitting an unrelated member.\n\
                     const exportName = __uniffiNameMap[name] ?? name;\n\
                     const argKinds = __uniffiInt64ArgKinds[name] ?? [];\n\
                     const retKind = __uniffiInt64ReturnKinds[name] ?? null;\n\
                     const v = (native as Record<string, unknown>)[exportName];\n\
                     if (typeof v !== \"function\") return v;\n\
                     const fn = v as (...args: unknown[]) => unknown;\n\
                     return (...args: unknown[]) => {{\n\
                         // Lower args on the way in: tag -> type for any\n\
                         // plain object (enum, nested in seq/opt/record).\n\
                         // Callback markers are still unwrapped first so\n\
                         // the lowering skips the `object` payload.\n\
                         const lowered = args.map((a, i) =>\n\
                             __uniffiLowerShape(__uniffiLowerInt64ForNapi(__uniffiCoerce(a), argKinds[i] ?? null)),\n\
                         );\n\
                         let result: unknown;\n\
                         try {{\n\
                             result = fn.apply(native, lowered);\n\
                         }} catch (err) {{\n\
                             // napi errors carry an enum payload with `type`;\n\
                             // lift it symmetrically so `common/errors.ts`\n\
                             // consumers see `tag`.\n\
                             throw __uniffiLiftShape(err);\n\
                         }}\n\
                         if (\n\
                             result !== null &&\n\
                             typeof result === \"object\" &&\n\
                             typeof (result as {{ then?: unknown }}).then === \"function\"\n\
                         ) {{\n\
                             return (result as Promise<unknown>).then(\n\
                                 (value) => __uniffiLiftInt64FromNapi(__uniffiLiftShape(value), retKind),\n\
                                 (err) => {{\n\
                                     throw __uniffiLiftShape(err);\n\
                                 }},\n\
                             );\n\
                         }}\n\
                         return __uniffiLiftInt64FromNapi(__uniffiLiftShape(result), retKind);\n\
                     }};\n\
                 }},\n\
             }},\n\
         );\n\
         \n\
         export default backend;\n\
         export {{ native as __uniffiNativeAddon }};\n\
         export const __uniffiBackendKind = \"napi\" as const;\n"
    )
}

fn int64_kind(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::Int64 => Some("i64"),
        Type::UInt64 => Some("u64"),
        _ => None,
    }
}

fn collect_int64_arg_kinds(ci: &ComponentInterface) -> Vec<(String, Vec<Option<&'static str>>)> {
    let mut out = Vec::new();

    for f in ci.function_definitions() {
        let kinds: Vec<_> = f
            .arguments()
            .iter()
            .map(|a| int64_kind(&a.as_type()))
            .collect();
        if kinds.iter().any(Option::is_some) {
            out.push((f.name().to_string(), kinds));
        }
    }

    for obj in ci.object_definitions() {
        let obj_snake = obj.name().to_snake_case();
        for c in obj.constructors() {
            let key = format!("{obj_snake}_{}", c.name().to_snake_case());
            let kinds: Vec<_> = c
                .arguments()
                .iter()
                .map(|a| int64_kind(&a.as_type()))
                .collect();
            if kinds.iter().any(Option::is_some) {
                out.push((key, kinds));
            }
        }
        for m in obj.methods() {
            let key = format!("{obj_snake}_{}", m.name().to_snake_case());
            let kinds: Vec<_> = m
                .arguments()
                .iter()
                .map(|a| int64_kind(&a.as_type()))
                .collect();
            if kinds.iter().any(Option::is_some) {
                out.push((key, kinds));
            }
        }
    }

    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn collect_int64_return_kinds(ci: &ComponentInterface) -> Vec<(String, &'static str)> {
    let mut out = Vec::new();

    for f in ci.function_definitions() {
        if let Some(kind) = f.return_type().and_then(int64_kind) {
            out.push((f.name().to_string(), kind));
        }
    }

    for obj in ci.object_definitions() {
        let obj_snake = obj.name().to_snake_case();
        for m in obj.methods() {
            if let Some(kind) = m.return_type().and_then(int64_kind) {
                out.push((format!("{obj_snake}_{}", m.name().to_snake_case()), kind));
            }
        }
    }

    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn render_int64_arg_map_js_literal(ci: &ComponentInterface) -> String {
    let pairs = collect_int64_arg_kinds(ci);
    if pairs.is_empty() {
        return "{}".to_string();
    }
    let mut out = String::from("{\n");
    for (key, kinds) in pairs {
        let items = kinds
            .into_iter()
            .map(|kind| match kind {
                Some(kind) => format!("\"{kind}\""),
                None => "null".to_string(),
            })
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    \"{key}\": [{items}],\n"));
    }
    out.push('}');
    out
}

fn render_int64_return_map_js_literal(ci: &ComponentInterface) -> String {
    let pairs = collect_int64_return_kinds(ci);
    if pairs.is_empty() {
        return "{}".to_string();
    }
    let mut out = String::from("{\n");
    for (key, kind) in pairs {
        out.push_str(&format!("    \"{key}\": \"{kind}\",\n"));
    }
    out.push('}');
    out
}

fn render_index(ci: &uniffi_bindgen::ComponentInterface) -> String {
    let namespace = ci.namespace();
    format!(
        "// AUTOGENERATED by uniffi_bindgen_javascript (napi flavor).\n\
         //\n\
         // Node/napi entry for namespace `{namespace}`. Applications\n\
         // import from this file and see the same high-level API as the\n\
         // wasm and electron entries. The backend installs itself on\n\
         // first import so callers never have to plumb it through.\n\
         \n\
         import backend from \"./backend-napi\";\n\
         import {{ __installBackend }} from \"../common/runtime.ts\";\n\
         __installBackend(backend);\n\
         export * from \"../common/api.ts\";\n\
         export {{ backend as __uniffiBackend }};\n"
    )
}
