// AUTOGENERATED UniFFI JavaScript runtime source.
//
// This is deliberately plain ECMAScript (there are no type annotations and
// no TypeScript transform is required).  The source is embedded by
// the UniFFI runtime crate and delivered from one crate.

export class UniffiError extends Error {
  constructor(init = {}) {
    const message = typeof init.message === "string" ? init.message : String(init);
    super(message);
    this.name = "UniffiError";
    this.errorName = typeof init.errorName === "string" ? init.errorName : "UniffiUnknownError";
    this.variant = typeof init.variant === "string" ? init.variant : null;
    this.data = Object.prototype.hasOwnProperty.call(init, "data") ? init.data : null;
    this.descriptor = init.descriptor ?? null;
    if (typeof init.stack === "string") this.stack = init.stack;
  }
}

export function errorDescriptor(raw) {
  if (raw instanceof UniffiError) {
    return {
      errorName: raw.errorName,
      variant: raw.variant,
      data: raw.data,
      message: raw.message,
      descriptor: raw.descriptor,
      stack: raw.stack,
    };
  }
  if (raw && typeof raw === "object") {
    return {
      errorName: typeof raw.errorName === "string" ? raw.errorName : "UniffiUnknownError",
      variant: typeof raw.variant === "string" ? raw.variant : (typeof raw.tag === "string" ? raw.tag : null),
      data: Object.prototype.hasOwnProperty.call(raw, "data") ? raw.data : raw,
      message: typeof raw.message === "string" ? raw.message : String(raw),
      descriptor: raw.descriptor ?? null,
      stack: typeof raw.stack === "string" ? raw.stack : undefined,
    };
  }
  return { errorName: "UniffiUnknownError", variant: null, data: null, message: String(raw), descriptor: null };
}

export function asUniffiError(raw) {
  return raw instanceof UniffiError ? raw : new UniffiError(errorDescriptor(raw));
}

function unwrapEnvelope(raw) {
  if (raw && typeof raw === "object" && raw.kind === "error" && own(raw, "error")) throw asUniffiError(raw.error);
  if (raw && typeof raw === "object" && raw.kind === "value" && own(raw, "value")) return raw.value;
  return raw;
}

function closedError() {
  return new UniffiError({ errorName: "UniffiSessionClosed", message: "UniFFI backend session is closed" });
}

const DETACHED = Symbol("uniffi-detached");
const SESSION_POLICY_STATE = new WeakMap();

function validateClosePolicy(policy) {
  if (!isObject(policy)) throw new UniffiError({ errorName: "UniffiClosePolicy", message: "close policy must be an object" });
  const graceMs = policy.graceMs;
  if (typeof graceMs !== "number" || !Number.isFinite(graceMs) || !Number.isInteger(graceMs) || graceMs < 0) {
    throw new UniffiError({ errorName: "UniffiClosePolicy", message: "close policy graceMs must be a finite non-negative integer" });
  }
  if (policy.onDeadline !== "detach") {
    throw new UniffiError({ errorName: "UniffiClosePolicy", message: "close policy onDeadline must be detach" });
  }
  return Object.freeze({ graceMs, onDeadline: "detach" });
}

function sameClosePolicy(left, right) {
  return left?.graceMs === right?.graceMs && left?.onDeadline === right?.onDeadline;
}

function sessionClosePolicy(session) {
  const policy = SESSION_POLICY_STATE.get(session)?.policy;
  if (!policy) throw new UniffiError({ errorName: "UniffiClosePolicy", message: "generated facade did not install close policy" });
  return policy;
}

function installClosePolicy(session, policy) {
  const validated = validateClosePolicy(policy);
  const state = SESSION_POLICY_STATE.get(session);
  if (!state) throw new UniffiError({ errorName: "UniffiSessionType", message: "unknown BackendSession" });
  if (!state.open) {
    if (!sameClosePolicy(state.policy, validated)) throw new UniffiError({ errorName: "UniffiClosePolicy", message: "cannot change close policy after session teardown starts" });
    return;
  }
  if (state.installed && !sameClosePolicy(state.policy, validated)) {
    throw new UniffiError({ errorName: "UniffiClosePolicy", message: "session close policy does not match generated facade policy" });
  }
  state.policy = validated;
  state.installed = true;
}

function markPolicyClosed(session) {
  const state = SESSION_POLICY_STATE.get(session);
  if (state) state.open = false;
}

function invalidOperationError(operationId) {
  return new UniffiError({
    errorName: "UniffiOperationId",
    data: { operationId },
    message: `invalid dense UniFFI operation ID ${String(operationId)}`,
  });
}

function assertOperationId(operationId) {
  if (!Number.isInteger(operationId) || operationId < 0) throw invalidOperationError(operationId);
}

function isObject(value) {
  return value !== null && typeof value === "object";
}

function own(value, key) {
  return Object.prototype.hasOwnProperty.call(value, key);
}

function assertCallbackTypeId(callbackTypeId) {
  if (!Number.isInteger(callbackTypeId) || callbackTypeId < 0) {
    throw new UniffiError({
      errorName: "UniffiCallbackType",
      data: { callbackTypeId },
      message: "callback type ID must be a canonical non-negative integer",
    });
  }
  return callbackTypeId;
}

/** A callback registry owned by one session.  Invocation IDs are independent
 * from registration tokens, so overlapping async calls cannot replace one
 * another and a retained callback lease cannot be released by a call. */
export class CallbackRegistry {
  constructor(host = null, session = null) {
    this.host = host;
    this.session = session;
    this.nextToken = new Map();
    this.callbacks = new Map();
  }

  register(callbackTypeId, callback, contract = {}) {
    const typeId = assertCallbackTypeId(callbackTypeId);
    if ((typeof callback !== "function" && !isObject(callback))) {
      throw new UniffiError({ errorName: "UniffiCallbackType", message: "callback must be callable or an object" });
    }
    const methods = contract && isObject(contract.methods) ? contract.methods : null;
    if (!methods || (Object.keys(methods).length === 0 && !(contract && contract.context))) {
      throw new UniffiError({ errorName: "UniffiCallbackMethod", message: "callback method descriptors are required" });
    }
    const next = this.nextToken.get(typeId) || 1;
    this.nextToken.set(typeId, next + 1);
    const key = `${typeId}:${next}`;
    const frameState = this.session ? SESSION_FRAME_STATE.get(this.session) : null;
    const hasActiveFrame = Boolean(frameState && frameState.active.length > 0);
    // A callback without an explicit retention policy remains available until
    // it participates in an explicit lease.  This keeps direct, unleased
    // callbacks useful for small runtime integrations while allowing a lease
    // release (or host release) to deterministically clean up the entry.
    const unleased = contract.retention === undefined && contract.retained !== true;
    const manual = contract.retention === "scoped" && !hasActiveFrame;
    this.callbacks.set(key, {
      typeId,
      id: next,
      callback,
      methods,
      context: contract.context || null,
      retention: contract.retention === "scoped"
        ? "scoped"
        : (contract.retention === "retained" || contract.retained === true ? "retained" : "manual"),
      manual,
      unleased,
      retained: contract.retention === "retained" || contract.retained === true,
      reentrancy: contract.reentrancy === "allowed" ? "allowed" : "forbidden",
      leases: 0,
      hostLeases: 0,
      engineRetained: false,
      frameRefs: 0,
      activeSync: 0,
      activeAsync: new Set(),
      cleaned: false,
    });
    return next;
  }

  _key(typeId, id) { return `${typeId}:${id}`; }

  retain(typeId, id) {
    const key = this._key(typeId, id);
    const entry = this.callbacks.get(key);
    if (!entry) throw new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${typeId}:${id}` });
    entry.leases += 1;
    entry.unleased = false;
    let released = false;
    return Object.freeze({
      token: id,
      typeId,
      id,
      release: () => {
        if (released) return;
        released = true;
        this.release(typeId, id);
      },
    });
  }

  release(typeId, id) {
    const key = this._key(typeId, id);
    const entry = this.callbacks.get(key);
    if (!entry) return;
    if (entry.leases > 0) {
      entry.leases -= 1;
    }
    entry.unleased = false;
    this._maybeCleanup(entry);
  }

  hostRetain(typeId, id) {
    const entry = this.callbacks.get(this._key(typeId, id));
    if (!entry) throw new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${typeId}:${id}` });
    entry.hostLeases += 1;
    entry.engineRetained = true;
    entry.unleased = false;
  }

  hostRelease(typeId, id) {
    const entry = this.callbacks.get(this._key(typeId, id));
    if (!entry) return;
    if (entry.hostLeases > 0) entry.hostLeases -= 1;
    if (entry.hostLeases === 0) entry.engineRetained = false;
    this._maybeCleanup(entry);
  }

  frameRetain(typeId, id) {
    const entry = this.callbacks.get(this._key(typeId, id));
    if (entry) entry.frameRefs += 1;
  }

  frameRelease(typeId, id) {
    const entry = this.callbacks.get(this._key(typeId, id));
    if (!entry) return;
    if (entry.frameRefs > 0) entry.frameRefs -= 1;
    this._maybeCleanup(entry);
  }

  _maybeCleanup(entry) {
    if (entry.cleaned || entry.manual || entry.unleased || entry.frameRefs > 0 || entry.leases > 0 || entry.hostLeases > 0 || entry.engineRetained || entry.activeSync > 0 || entry.activeAsync.size > 0) return;
    entry.cleaned = true;
    this.callbacks.delete(this._key(entry.typeId, entry.id));
  }

  unregister(typeId, id) {
    const key = this._key(typeId, id);
    const entry = this.callbacks.get(key);
    if (!entry) return;
    entry.retained = false;
    entry.manual = false;
    entry.unleased = false;
    entry.retention = "scoped";
    entry.leases = 0;
    entry.frameRefs = 0;
    entry.hostLeases = 0;
    entry.engineRetained = false;
    this._maybeCleanup(entry);
  }

  _entry(typeId, id) {
    const entry = this.callbacks.get(this._key(typeId, id));
    if (!entry) throw new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${typeId}:${id}` });
    return entry;
  }

  _methodSpec(entry, methodId) {
    if (!entry.methods || !Object.prototype.hasOwnProperty.call(entry.methods, methodId)) return null;
    const raw = entry.methods?.[methodId];
    if (raw && typeof raw === "object") return raw;
    if (typeof raw === "string") return { name: raw };
    return null;
  }

  _invokeLocal(entry, methodSpec, args) {
    if (!methodSpec || (methodSpec.name !== null && (typeof methodSpec.name !== "string" || methodSpec.name.length === 0))) {
      throw new UniffiError({ errorName: "UniffiCallbackMethod", message: "unknown callback method ID" });
    }
    if (methodSpec.name === null && typeof entry.callback === "function") return entry.callback(...args);
    if (entry.callback && typeof entry.callback[methodSpec.name] === "function") return entry.callback[methodSpec.name](...args);
    throw new UniffiError({ errorName: "UniffiCallbackMethod", message: `callback object has no method ${methodSpec.name}` });
  }

  invokeSync(callbackType, callbackId, methodId, args = []) {
    if (this.session && this.session.phase !== "open") throw closedError();
    const entry = this._entry(callbackType, callbackId);
    if (entry.reentrancy === "forbidden" && (entry.activeSync || entry.activeAsync.size > 0)) {
      throw new UniffiError({ errorName: "UniffiCallbackReentrancy", data: { callbackType, callbackId, methodId }, message: "forbidden callback reentrancy" });
    }
    const methodSpec = this._methodSpec(entry, methodId);
    if (!methodSpec) throw new UniffiError({ errorName: "UniffiCallbackMethod", message: `unknown callback method ${String(methodId)}` });
    if (methodSpec.async === true) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: "async callback method invoked synchronously" });
    const convertedArgs = methodSpec?.args
      ? methodSpec.args.map((descriptor, index) => liftValue(args[index], descriptor, this.session, entry.context))
      : args;
    entry.activeSync += 1;
    try {
      let result = this._invokeLocal(entry, methodSpec, convertedArgs);
      if (result && typeof result.then === "function") throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: "sync callback returned a Promise" });
      if (methodSpec?.returnType) result = lowerValue(result, methodSpec.returnType, entry.context, this.session, { callbackContracts: methodSpec.callbackContracts || {} }, "return");
      return result;
    } catch (raw) {
      throw lowerCallbackError(raw, methodSpec, entry.context, this.session);
    } finally {
      entry.activeSync -= 1;
      this._maybeCleanup(entry);
    }
  }

  async invokeAsync(callbackType, callbackId, methodId, invocationId, args = []) {
    if (this.session && this.session.phase !== "open") throw closedError();
    const entry = this._entry(callbackType, callbackId);
    if (!Number.isInteger(invocationId) || invocationId < 0) {
      throw new UniffiError({ errorName: "UniffiCallbackInvocation", data: { callbackType, callbackId, invocationId }, message: "async callback invocation ID must be a non-negative integer" });
    }
    if (entry.reentrancy === "forbidden" && (entry.activeSync || entry.activeAsync.size > 0)) {
      throw new UniffiError({ errorName: "UniffiCallbackReentrancy", data: { callbackType, callbackId, methodId, invocationId }, message: "forbidden overlapping callback invocation" });
    }
    const invocationKey = invocationId;
    if (entry.activeAsync.has(invocationKey)) {
      throw new UniffiError({ errorName: "UniffiCallbackInvocation", data: { callbackType, callbackId, invocationId }, message: "callback invocation ID is already active" });
    }
    const methodSpec = this._methodSpec(entry, methodId);
    if (!methodSpec) throw new UniffiError({ errorName: "UniffiCallbackMethod", message: `unknown callback method ${String(methodId)}` });
    if (methodSpec.async === false) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: "sync callback method invoked asynchronously" });
    const convertedArgs = methodSpec?.args
      ? methodSpec.args.map((descriptor, index) => liftValue(args[index], descriptor, this.session, entry.context))
      : args;
    entry.activeAsync.add(invocationKey);
    const generation = this.session?.generation;
    try {
      let result = this._invokeLocal(entry, methodSpec, convertedArgs);
      if (this.session) {
        result = await this.session._guardPromise(Promise.resolve(result), generation);
        if (result === DETACHED) throw closedError();
      } else {
        result = await result;
      }
      if (this.session && !this.session._generationActive(generation)) throw closedError();
      if (methodSpec?.returnType) result = lowerValue(result, methodSpec.returnType, entry.context, this.session, { callbackContracts: methodSpec.callbackContracts || {} }, "return");
      return result;
    } catch (raw) {
      throw lowerCallbackError(raw, methodSpec, entry.context, this.session);
    } finally {
      entry.activeAsync.delete(invocationKey);
      this._maybeCleanup(entry);
    }
  }

  drain() {
    for (const entry of [...this.callbacks.values()]) this.unregister(entry.typeId, entry.id);
  }

  detach() {
    for (const entry of this.callbacks.values()) entry.cleaned = true;
    this.callbacks.clear();
  }
}

/** Default host SPI.  Engines can subclass or provide an object with these
 * methods; the session never needs a namespace/string operation dispatcher. */
export class Host {
  constructor() {}
  retainCallback(_typeId, _callbackId) {}
  releaseCallback(_typeId, _callbackId) {}
  invokeCallbackSync(callbackType, callbackId, methodId, args) {
    void args;
    throw new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${callbackType}:${callbackId}:${methodId}` });
  }
  async invokeCallbackAsync(callbackType, callbackId, methodId, _invocationId, args) {
    return await this.invokeCallbackSync(callbackType, callbackId, methodId, args);
  }
  pullInputStream(_handle) { return Promise.resolve({ kind: "done" }); }
  cancelInputStream(_handle) { return Promise.resolve(); }
  releaseInputStream(_handle) {}
  releaseObject(_handle) {}
}

// The engine receives the exact host object supplied to BackendSession.  Keep
// its callback and input-stream registries on that object so an engine call to
// host.invokeCallback*/pullInputStream observes the same entries as JS calls.
const HOST_REGISTRIES = new WeakMap();

function installHostRegistries(host) {
  if (!host || (typeof host !== "object" && typeof host !== "function")) return new Host();
  if (HOST_REGISTRIES.has(host)) return host;
  const original = {
    retainCallback: typeof host.retainCallback === "function" ? host.retainCallback : null,
    releaseCallback: typeof host.releaseCallback === "function" ? host.releaseCallback : null,
    pullInputStream: typeof host.pullInputStream === "function" ? host.pullInputStream : null,
    cancelInputStream: typeof host.cancelInputStream === "function" ? host.cancelInputStream : null,
    releaseInputStream: typeof host.releaseInputStream === "function" ? host.releaseInputStream : null,
  };
  const inputHost = new InputStreamHost();
  const registries = { inputHost, original, callbackRegistry: null, session: null, detached: false, everBound: false };
  HOST_REGISTRIES.set(host, registries);
  host.retainCallback = function retainCallback(typeId, callbackId) {
    if (registries.detached || registries.session?.phase !== "open") return undefined;
    registries.callbackRegistry?.hostRetain(typeId, callbackId);
    if (original.retainCallback) return original.retainCallback.call(this, typeId, callbackId);
    return undefined;
  };
  host.releaseCallback = function releaseCallback(typeId, callbackId) {
    if (registries.detached) return undefined;
    registries.callbackRegistry?.hostRelease(typeId, callbackId);
    if (original.releaseCallback) return original.releaseCallback.call(this, typeId, callbackId);
    return undefined;
  };
  host.invokeCallbackSync = function invokeCallbackSync(typeId, callbackId, methodId, args = []) {
    if (registries.detached) throw closedError();
    const registry = registries.callbackRegistry;
    if (registry?.callbacks.has(`${typeId}:${callbackId}`)) return registry.invokeSync(typeId, callbackId, methodId, args);
    throw new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${typeId}:${callbackId}` });
  };
  host.invokeCallbackAsync = function invokeCallbackAsync(typeId, callbackId, methodId, invocationId, args = []) {
    if (registries.detached || registries.session?.phase !== "open") return Promise.reject(closedError());
    const registry = registries.callbackRegistry;
    if (registry?.callbacks.has(`${typeId}:${callbackId}`)) {
      const result = registry.invokeAsync(typeId, callbackId, methodId, invocationId, args);
      result.catch(() => {});
      return result;
    }
    return Promise.reject(new UniffiError({ errorName: "UniffiCallbackMissing", message: `unknown callback ${typeId}:${callbackId}` }));
  };
  host.registerInputStream = function registerInputStream(source, options = {}) {
    if (registries.detached || registries.session?.phase !== "open") throw closedError();
    const callerClose = options.onClose;
    return inputHost.add(source, {
      ...options,
      onClose: (handle) => {
        try { if (typeof callerClose === "function") callerClose(handle); } catch (_) {}
        try { if (original.releaseInputStream) original.releaseInputStream.call(this, handle); } catch (_) {}
      },
    });
  };
  host.pullInputStream = function pullInputStream(handle) {
    if (registries.detached) return Promise.resolve({ kind: "done" });
    if (inputHost.slots.has(handle)) {
      const result = inputHost.pullInputStream(handle);
      result.catch(() => {});
      return result;
    }
    if (inputHost.closedHandles.has(handle)) return Promise.resolve({ kind: "done" });
    if (original.pullInputStream) {
      const result = original.pullInputStream.call(this, handle);
      Promise.resolve(result).catch(() => {});
      return result;
    }
    return Promise.resolve({ kind: "done" });
  };
  host.cancelInputStream = function cancelInputStream(handle) {
    if (registries.detached) return Promise.resolve();
    if (inputHost.slots.has(handle)) {
      const result = inputHost.cancelInputStream(handle);
      Promise.resolve(result).catch(() => {});
      return result;
    }
    if (inputHost.closedHandles.has(handle)) return Promise.resolve();
    if (original.cancelInputStream) {
      const result = original.cancelInputStream.call(this, handle);
      Promise.resolve(result).catch(() => {});
      return result;
    }
    return Promise.resolve();
  };
  host.releaseInputStream = function releaseInputStream(handle) {
    if (registries.detached) return undefined;
    if (inputHost.slots.has(handle)) return inputHost.releaseInputStream(handle);
    if (inputHost.closedHandles.has(handle)) return undefined;
    if (original.releaseInputStream) return original.releaseInputStream.call(this, handle);
    return undefined;
  };
  return host;
}

class InputStreamHost extends Host {
  constructor() {
    super();
    this.nextHandle = 1;
    this.slots = new Map();
    this.closedHandles = new Set();
  }

  add(source, options = {}) {
    const isPullSource = source && typeof source.next === "function";
    const asyncIterator = typeof Symbol === "function" ? Symbol.asyncIterator : undefined;
    const isAsyncIterable = Boolean(asyncIterator && source && typeof source[asyncIterator] === "function");
    if (!isPullSource && !isAsyncIterable) throw new UniffiError({ errorName: "UniffiInputStreamType", message: "expected a pull source or AsyncIterable for input stream" });
    const handle = this.nextHandle++;
    this.closedHandles.delete(handle);
    const iterator = isPullSource
      ? {
          next: () => source.next(),
          return: () => typeof source.cancel === "function" ? source.cancel() : undefined,
        }
      : source[asyncIterator]();
    this.slots.set(handle, {
      iterator,
      lowerItem: typeof options.lowerItem === "function" ? options.lowerItem : (value) => value,
      lowerError: typeof options.lowerError === "function" ? options.lowerError : (error) => error,
      onClose: typeof options.onClose === "function" ? options.onClose : null,
      pending: false,
      closed: false,
      detached: false,
    });
    return {
      __uniffiInputStream: true,
      handle,
      next: () => this.pullInputStream(handle),
      cancel: () => this.cancelInputStream(handle),
      release: () => this.releaseInputStream(handle),
    };
  }

  async pullInputStream(handle) {
    const slot = this.slots.get(handle);
    if (!slot || slot.closed) return { kind: "done" };
    if (slot.pending) throw new UniffiError({ errorName: "UniffiInputStreamConcurrentNext", message: "concurrent input stream pull" });
    slot.pending = true;
    try {
      const result = await slot.iterator.next();
      if (slot.closed || slot.detached) return { kind: "done" };
      if (result && result.kind === "done") {
        slot.closed = true;
        this.slots.delete(handle);
        this.closedHandles.add(handle);
        if (!slot.detached) { try { slot.onClose?.(handle); } catch (_) {} }
        return { kind: "done" };
      }
      if (result && result.kind === "error") throw result.error;
      const normalized = result && result.kind === "item"
        ? { value: result.value, done: false }
        : result;
      if (!normalized || typeof normalized !== "object" || typeof normalized.done !== "boolean") throw new UniffiError({ errorName: "UniffiInputStreamProtocol", message: "input stream next must return IteratorResult or tagged step" });
      if (normalized && normalized.done) {
        slot.closed = true;
        this.slots.delete(handle);
        this.closedHandles.add(handle);
        try { slot.onClose?.(handle); } catch (_) {}
        return { kind: "done" };
      }
      return { kind: "item", value: slot.lowerItem(normalized?.value) };
    } catch (raw) {
      if (slot.closed) return { kind: "done" };
      slot.closed = true;
      this.slots.delete(handle);
      this.closedHandles.add(handle);
      try { slot.onClose?.(handle); } catch (_) {}
      return { kind: "error", error: slot.lowerError(raw) };
    } finally {
      slot.pending = false;
    }
  }

  async cancelInputStream(handle) {
    const slot = this.slots.get(handle);
    if (!slot || slot.closed) return;
    slot.closed = true;
    this.slots.delete(handle);
    this.closedHandles.add(handle);
    if (!slot.detached) { try { slot.onClose?.(handle); } catch (_) {} }
    if (!slot.detached && slot.iterator && typeof slot.iterator.return === "function") {
      try { await slot.iterator.return(); } catch (_) {}
    }
  }

  releaseInputStream(handle) {
    void this.cancelInputStream(handle).catch(() => {});
  }

  detach() {
    for (const [handle, slot] of this.slots.entries()) {
      slot.closed = true;
      slot.detached = true;
      this.closedHandles.add(handle);
    }
    this.slots.clear();
  }
}

const SESSION_FRAME_STATE = new WeakMap();

export class BackendSession {
  constructor(backend, host = new Host()) {
    if (!backend || typeof backend !== "object") throw new UniffiError({ errorName: "UniffiBackendType", message: "backend must be an object" });
    this.backend = backend;
    this.host = installHostRegistries(host || new Host());
    this.phase = "open";
    this.generation = 1;
    this.detached = false;
    this.closePromise = null;
    this._closeResolve = null;
    this._closeReject = null;
    this._deadlineTimer = null;
    this._waiters = new Set();
    this._idleWaiters = new Set();
    this._activeGuards = 0;
    this.objects = new Set();
    this.outputStreams = new Set();
    this.inputStreams = new Set();
    this.callbacks = new CallbackRegistry(this.host, this);
    const hostRegistries = HOST_REGISTRIES.get(this.host);
    if (!hostRegistries || hostRegistries.session !== null || hostRegistries.everBound) {
      throw new UniffiError({
        errorName: "UniffiHostSession",
        message: "a Host can be bound to only one BackendSession",
      });
    }
    hostRegistries.callbackRegistry = this.callbacks;
    hostRegistries.session = this;
    hostRegistries.detached = false;
    hostRegistries.everBound = true;
    this.callbacks.session = this;
    this.inputHost = hostRegistries.inputHost;
    this.inputCancelled = new Set();
    this.inputReleased = new Set();
    SESSION_FRAME_STATE.set(this, { active: [] });
    SESSION_POLICY_STATE.set(this, { policy: null, installed: false, open: true });
  }

  _generationActive(generation) {
    return generation === this.generation && !this.detached && this.phase !== "closed";
  }

  _guardPromise(promise, generation = this.generation) {
    let waiter;
    this._activeGuards += 1;
    const guarded = new Promise((resolve, reject) => {
      waiter = {
        settle: () => {
          if (!this._waiters.delete(waiter)) return;
          this._activeGuards -= 1;
          this._notifyIdle();
          resolve(DETACHED);
        },
      };
      this._waiters.add(waiter);
      Promise.resolve(promise).then((value) => {
        if (!this._waiters.delete(waiter)) return;
        this._activeGuards -= 1;
        this._notifyIdle();
        resolve(this._generationActive(generation) ? value : DETACHED);
      }, (error) => {
        if (!this._waiters.delete(waiter)) return;
        this._activeGuards -= 1;
        this._notifyIdle();
        if (this._generationActive(generation)) reject(error);
        else resolve(DETACHED);
      });
    });
    // A caller may intentionally fire-and-forget an operation while close is
    // detaching.  Mark the guarded promise handled without changing the
    // promise returned to that caller.
    guarded.catch(() => {});
    return guarded;
  }

  _notifyIdle() {
    if (this._activeGuards !== 0) return;
    for (const resolve of [...this._idleWaiters]) {
      this._idleWaiters.delete(resolve);
      resolve();
    }
  }

  _awaitIdle() {
    if (this._activeGuards === 0) return Promise.resolve();
    return new Promise((resolve) => this._idleWaiters.add(resolve));
  }

  _assertOpen() {
    if (this.phase !== "open") throw closedError();
  }

  invokeSync(operationId, args = []) {
    this._assertOpen();
    assertOperationId(operationId);
    if (typeof this.backend.invokeSync !== "function") throw new UniffiError({ errorName: "UniffiBackendProtocol", message: "backend does not implement invokeSync(operationId, args)" });
    try {
      const result = this.backend.invokeSync(operationId, args);
      if (result && typeof result.then === "function") throw new UniffiError({ errorName: "UniffiBackendProtocol", message: "invokeSync returned a Promise" });
      return unwrapEnvelope(result);
    } catch (raw) {
      throw asUniffiError(raw);
    }
  }

  invokeAsync(operationId, args = []) {
    try {
      this._assertOpen();
      assertOperationId(operationId);
    } catch (error) {
      return Promise.reject(asUniffiError(error));
    }
    if (typeof this.backend.invokeAsync !== "function") return Promise.reject(new UniffiError({ errorName: "UniffiBackendProtocol", message: "backend does not implement invokeAsync(operationId, args)" }));
    const generation = this.generation;
    let call;
    try {
      call = Promise.resolve().then(() => this.backend.invokeAsync(operationId, args));
    } catch (error) {
      return Promise.reject(asUniffiError(error));
    }
    const exposed = this._guardPromise(call, generation).then((raw) => {
      if (raw === DETACHED) throw closedError();
      return unwrapEnvelope(raw);
    }).catch((raw) => { throw asUniffiError(raw); });
    exposed.catch(() => {});
    return exposed;
  }

  releaseObject(handle) {
    if (handle === null || handle === undefined) return;
    if (this.detached || this.phase === "closed") return;
    try {
      if (typeof this.backend.releaseObject === "function") this.backend.releaseObject(handle);
      else if (this.host && typeof this.host.releaseObject === "function") this.host.releaseObject(handle);
    } catch (_) {
      // Object release is explicitly non-throwing and idempotent.
    }
  }

  registerCallback(callbackType, callback, contract = {}) {
    this._assertOpen();
    const typeId = assertCallbackTypeId(callbackType);
    const id = this.callbacks.register(typeId, callback, contract);
    const frameState = SESSION_FRAME_STATE.get(this);
    const frame = frameState?.active[frameState.active.length - 1];
    if (frame) {
      this.callbacks.frameRetain(typeId, id);
      frame.registrations.push([typeId, id]);
    }
    return id;
  }
  beginCallFrame() {
    const frame = { registrations: [], inputStreams: [], ended: false };
    SESSION_FRAME_STATE.get(this)?.active.push(frame);
    return frame;
  }
  endCallFrame(frame) {
    if (!frame || frame.ended) return;
    frame.ended = true;
    const state = SESSION_FRAME_STATE.get(this);
    if (state) {
      const index = state.active.indexOf(frame);
      if (index >= 0) state.active.splice(index, 1);
    }
    for (const [typeId, id] of frame.registrations) this.callbacks.frameRelease(typeId, id);
    for (const handle of frame.inputStreams || []) {
      try {
        Promise.resolve(this.cancelInputStream(handle)).then(() => this.releaseInputStream(handle), () => this.releaseInputStream(handle));
      } catch (_) {
        this.releaseInputStream(handle);
      }
    }
  }
  retainCallback(callbackType, callbackId) { return this.callbacks.retain(callbackType, callbackId); }
  releaseCallback(callbackType, callbackId) { this.callbacks.release(callbackType, callbackId); }
  invokeCallbackSync(callbackType, callbackId, methodId, args = []) { return this.callbacks.invokeSync(callbackType, callbackId, methodId, args); }
  invokeCallbackAsync(callbackType, callbackId, methodId, invocationId, args = []) {
    const result = this.callbacks.invokeAsync(callbackType, callbackId, methodId, invocationId, args);
    result.catch(() => {});
    return result;
  }

  createInputStream(source, options = {}) {
    this._assertOpen();
    const frameState = SESSION_FRAME_STATE.get(this);
    const frame = frameState?.active[frameState.active.length - 1];
    const callerOnClose = options.onClose;
    const streamOptions = { ...options };
    let inputHandle;
    if (frame) {
      frame.inputStreams.push(null);
      streamOptions.onClose = (handle) => {
        this.inputStreams.delete(inputHandle);
        const index = frame.inputStreams.indexOf(inputHandle);
        if (index >= 0) frame.inputStreams.splice(index, 1);
        try { callerOnClose?.(handle); } catch (_) {}
      };
    } else {
      streamOptions.onClose = (handle) => {
        this.inputStreams.delete(inputHandle);
        try { callerOnClose?.(handle); } catch (_) {}
      };
    }
    let marker;
    try {
      marker = this.host.registerInputStream(source, streamOptions);
    } catch (error) {
      if (frame) {
        const index = frame.inputStreams.indexOf(null);
        if (index >= 0) frame.inputStreams.splice(index, 1);
      }
      throw error;
    }
    inputHandle = marker.handle;
    this.inputStreams.add(marker.handle);
    if (frame) {
      const index = frame.inputStreams.indexOf(null);
      if (index >= 0) frame.inputStreams[index] = marker.handle;
    }
    marker.cancel = () => this.cancelInputStream(marker.handle);
    marker.release = () => this.releaseInputStream(marker.handle);
    return marker;
  }

  pullInputStream(handle) {
    this._assertOpen();
    const generation = this.generation;
    let pending;
    try { pending = this.host.pullInputStream(handle); }
    catch (error) { return Promise.reject(asUniffiError(error)); }
    const result = this._guardPromise(pending, generation).then((step) => step === DETACHED ? { kind: "done" } : step);
    result.catch(() => {});
    return result;
  }

  async cancelInputStream(handle) {
    if (this.detached) return;
    if (this.inputCancelled.has(handle)) return;
    this.inputCancelled.add(handle);
    this.inputStreams.delete(handle);
    const generation = this.generation;
    try {
      if (this.host && typeof this.host.cancelInputStream === "function") {
        const result = await this._guardPromise(this.host.cancelInputStream(handle), generation);
        if (result === DETACHED) return;
      }
    } catch (_) {}
  }

  releaseInputStream(handle) {
    if (this.inputReleased.has(handle)) return;
    this.inputReleased.add(handle);
    this.inputStreams.delete(handle);
    if (this.detached || this.phase === "closed") return;
    try { if (this.host && typeof this.host.releaseInputStream === "function") this.host.releaseInputStream(handle); } catch (_) {}
  }

  cancelOutputStream(handle) {
    if (this.detached || this.phase === "closed") return Promise.resolve();
    if (this.backend && typeof this.backend.cancelOutputStream === "function") return Promise.resolve().then(() => this.backend.cancelOutputStream(handle));
    if (this.host && typeof this.host.cancelOutputStream === "function") return Promise.resolve().then(() => this.host.cancelOutputStream(handle));
    return Promise.reject(streamPlanError("output stream cancel operation is unavailable"));
  }

  releaseOutputStream(handle) {
    if (this.detached || this.phase === "closed") return undefined;
    try {
      let result;
      if (this.backend && typeof this.backend.releaseOutputStream === "function") result = this.backend.releaseOutputStream(handle);
      else if (this.host && typeof this.host.releaseOutputStream === "function") result = this.host.releaseOutputStream(handle);
      else throw streamPlanError("output stream release operation is unavailable");
      if (result && typeof result.catch === "function") result.catch(() => {});
      return result;
    } catch (_) {
      // Output release is explicitly best effort and idempotent.
    }
    return undefined;
  }

  /** Build a strict output stream from operation-ID slots.  `start` is lazy,
   * `next` accepts only `{kind:"item"|"done"|"error", ...}` and cancel is
   * asynchronous while release is best-effort/non-throwing. */
  createOutputStream(options = {}) {
    this._assertOpen();
    const session = this;
    const generation = session.generation;
    let phase = "idle";
    let handle;
    let pending = false;
    let consumer = null;
    let cancelStarted = false;
    let cancelPromise = null;
    let cancelError = null;
    let releaseStarted = false;
    let startPromise = null;
    let detached = false;
    const start = options.start;
    const next = options.next;
    const cancel = options.cancel;
    const release = options.release;
    const liftItem = typeof options.liftItem === "function" ? options.liftItem : (value) => value;
    const finishFrame = () => { if (detached) return; try { options.onClose?.(); } catch (_) {} };
    const terminal = () => ({ done: true, value: undefined });
    const validateStep = (step) => {
      if (!isObject(step) || typeof step.kind !== "string") throw new UniffiError({ errorName: "UniffiStreamProtocolError", message: "output stream step must be tagged" });
      if (step.kind === "item" && own(step, "value") && !own(step, "error")) return { kind: "item", value: step.value };
      if (step.kind === "done" && Object.keys(step).length === 1) return { kind: "done" };
      if (step.kind === "error" && own(step, "error") && !own(step, "value")) return { kind: "error", error: step.error };
      throw new UniffiError({ errorName: "UniffiStreamProtocolError", message: `invalid output stream ${step.kind} step` });
    };
    const ensureStarted = () => {
      if (phase === "active") return Promise.resolve(handle);
      if (phase === "starting") return startPromise;
      if (phase !== "idle") return Promise.resolve(null);
      phase = "starting";
      startPromise = Promise.resolve().then(() => typeof start === "function" ? start() : options.handle).then((started) => {
        if (detached || !session._generationActive(generation)) return DETACHED;
        handle = started;
        if (phase === "cancelled") return handle;
        phase = "active";
        session.outputStreams.add(stream);
        return handle;
      }).catch((raw) => {
        if (detached || !session._generationActive(generation)) return DETACHED;
        if (phase !== "cancelled") phase = "failed";
        throw asUniffiError(raw);
      });
      startPromise.catch(() => {});
      return startPromise;
    };
    const doRelease = (activeHandle = handle) => {
      if (releaseStarted) return;
      releaseStarted = true;
      try {
        if (typeof release === "function") release(activeHandle);
        else session.releaseOutputStream(activeHandle);
      } catch (_) {}
    };
    const doCancel = async (activeHandle = handle, { propagate = false } = {}) => {
      if (cancelStarted) {
        if (cancelPromise) await cancelPromise;
        if (propagate && cancelError) throw cancelError;
        return;
      }
      cancelStarted = true;
      phase = phase === "done" ? "done" : "cancelled";
      cancelPromise = (async () => {
        if (startPromise) {
          try { activeHandle = await session._guardPromise(startPromise, generation); } catch (_) { activeHandle = handle; }
          if (activeHandle === DETACHED || detached) return;
        }
        try {
          if (activeHandle !== undefined && activeHandle !== null) {
            if (typeof cancel === "function") await cancel(activeHandle);
            else await session.cancelOutputStream(activeHandle);
          }
        } catch (raw) {
          cancelError = asUniffiError(raw);
        } finally {
          if (activeHandle !== undefined && activeHandle !== null) doRelease(activeHandle);
          session.outputStreams.delete(stream);
          finishFrame();
        }
      })();
      const observed = await session._guardPromise(cancelPromise, generation);
      if (observed === DETACHED) return;
      if (propagate && cancelError) throw cancelError;
    };
    const pull = async (owner) => {
      if (consumer === null) consumer = owner;
      else if (consumer !== owner) throw new UniffiError({ errorName: "UniffiStreamConsumed", message: "output stream has one consumer" });
      if (["done", "failed", "cancelled"].includes(phase)) return terminal();
      if (pending) throw new UniffiError({ errorName: "UniffiStreamConcurrentNext", message: "concurrent output stream pull" });
      pending = true;
      let streamError = null;
      try {
        const activeHandle = await session._guardPromise(ensureStarted(), generation);
        if (activeHandle === DETACHED || activeHandle === null || phase !== "active" || detached) return terminal();
        if (typeof next !== "function") throw streamPlanError("output stream is missing canonical next operation");
        const raw = await session._guardPromise(next(activeHandle), generation);
        if (raw === DETACHED || phase !== "active" || detached) return terminal();
        const step = validateStep(raw);
        if (step.kind === "item") return { done: false, value: liftItem(step.value) };
        if (step.kind === "done") { phase = "done"; session.outputStreams.delete(stream); doRelease(activeHandle); finishFrame(); return terminal(); }
        try {
          streamError = typeof options.liftError === "function" ? options.liftError(step.error) : asUniffiError(step.error);
        } catch (error) {
          streamError = asUniffiError(error);
        }
        phase = "done";
        session.outputStreams.delete(stream);
        doRelease(activeHandle);
        finishFrame();
        throw streamError;
      } catch (raw) {
        if (streamError) throw streamError;
        if (phase === "cancelled" || phase === "done") return terminal();
        phase = "failed";
        await doCancel(handle);
        throw asUniffiError(raw);
      } finally { pending = false; }
    };
    const stream = {
      next: () => pull(stream),
      async cancel() { if (phase === "idle") { phase = "cancelled"; session.outputStreams.delete(stream); finishFrame(); return; } if (phase === "starting" || phase === "active") await doCancel(handle, { propagate: true }); },
      detach() {
        detached = true;
        phase = "cancelled";
        session.outputStreams.delete(stream);
        if (startPromise) startPromise.catch(() => {});
        if (cancelPromise) cancelPromise.catch(() => {});
      },
    };
    session.outputStreams.add(stream);
    return stream;
  }

  close() {
    if (this.closePromise) return this.closePromise;
    if (this.phase === "closed") return Promise.resolve();
    let policy;
    try {
      policy = sessionClosePolicy(this);
    } catch (error) {
      const rejected = Promise.reject(error);
      rejected.catch(() => {});
      this.closePromise = rejected;
      this.phase = "closed";
      this.detached = true;
      this.generation += 1;
      markPolicyClosed(this);
      this.outputStreams.clear();
      this.inputStreams.clear();
      for (const lease of [...this.objects]) { try { lease.dispose(); } catch (_) {} }
      this.objects.clear();
      this.callbacks.detach();
      const frameState = SESSION_FRAME_STATE.get(this);
      for (const frame of [...(frameState?.active || [])]) {
        try { this.endCallFrame(frame); } catch (_) {}
      }
      this._releaseHostBindings();
      return rejected;
    }
    this.phase = "closing";
    markPolicyClosed(this);
    this.closePromise = new Promise((resolve, reject) => {
      this._closeResolve = resolve;
      this._closeReject = reject;
    });
    const timer = setTimeout(() => this._deadlineDetach(), policy.graceMs);
    this._deadlineTimer = timer;
    // The deadline is an owned teardown resource.  It is cleared on every
    // natural completion path, so an already-finished close never leaves a
    // timer that can keep Node alive; while close is pending the reference is
    // intentional so the advertised deadline can actually resolve close().
    this._runTeardown().then(
      (errors) => this._finishNaturalClose(errors),
      (error) => this._finishNaturalClose([error]),
    ).catch(() => {});
    return this.closePromise;
  }

  async _runTeardown() {
    const errors = [];
    const pending = [];
    // Start every teardown leg in the same turn.  In particular backend.close
    // must not wait for a user iterator/callback before it gets its shared
    // policy deadline.
    for (const stream of [...this.outputStreams]) {
      try {
        pending.push(Promise.resolve(stream.cancel()).catch((error) => {
          if (!this.detached) errors.push(error);
        }));
      } catch (error) {
        if (!this.detached) errors.push(error);
      }
    }
    for (const handle of [...this.inputStreams]) {
      try {
        pending.push(this.cancelInputStream(handle).then(() => {
          this.releaseInputStream(handle);
        }).catch((error) => {
          if (!this.detached) errors.push(error);
        }));
      } catch (error) {
        if (!this.detached) errors.push(error);
      }
    }
    for (const lease of [...this.objects]) {
      try { lease.dispose(); } catch (_) {}
    }
    if (typeof this.backend.close === "function") {
      try {
        const backendResult = this.backend.close();
        pending.push(this._guardPromise(backendResult, this.generation).then((result) => {
          void result;
        }).catch((error) => {
          if (!this.detached) errors.push(error);
        }));
      } catch (error) {
        if (!this.detached) errors.push(error);
      }
    }
    await Promise.all(pending);
    if (!this.detached) await this._awaitIdle();
    return errors;
  }

  _releaseHostBindings() {
    const registries = HOST_REGISTRIES.get(this.host);
    if (!registries) return;
    registries.callbackRegistry = null;
    registries.session = null;
    registries.detached = true;
    try { registries.inputHost.detach(); } catch (_) {}
  }

  _finishNaturalClose(errors) {
    if (this.phase === "closed") return;
    if (this._deadlineTimer !== null) {
      clearTimeout(this._deadlineTimer);
      this._deadlineTimer = null;
    }
    if (!this.detached) {
      this.callbacks.drain();
      this.phase = "closed";
      this.generation += 1;
      this._releaseHostBindings();
    }
    const resolve = this._closeResolve;
    const reject = this._closeReject;
    this._closeResolve = null;
    this._closeReject = null;
    if (this.detached) {
      resolve?.();
    } else if (errors && errors.length) {
      reject?.(asUniffiError(errors[0]));
    } else {
      resolve?.();
    }
  }

  _deadlineDetach() {
    if (this.phase === "closed" || this.detached) return;
    this.detached = true;
    this.phase = "closed";
    this.generation += 1;
    for (const waiter of [...this._waiters]) waiter.settle();
    for (const resolve of [...this._idleWaiters]) { this._idleWaiters.delete(resolve); resolve(); }
    for (const stream of [...this.outputStreams]) {
      try { stream.detach?.(); } catch (_) {}
    }
    this.outputStreams.clear();
    this.inputStreams.clear();
    this.inputCancelled.clear();
    this.inputReleased.clear();
    for (const lease of [...this.objects]) {
      try { lease.dispose(); } catch (_) {}
    }
    this.objects.clear();
    this.callbacks.detach();
    const frameState = SESSION_FRAME_STATE.get(this);
    for (const frame of [...(frameState?.active || [])]) {
      try { this.endCallFrame(frame); } catch (_) {}
    }
    this._releaseHostBindings();
    if (this._deadlineTimer !== null) {
      clearTimeout(this._deadlineTimer);
      this._deadlineTimer = null;
    }
    const resolve = this._closeResolve;
    this._closeResolve = null;
    this._closeReject = null;
    resolve?.();
  }
}

export function createBackendSession(backend, host = new Host()) {
  if (typeof backend === "function") {
    const session = backend(host);
    if (session instanceof BackendSession) return session;
    return new BackendSession(session, host);
  }
  throw new UniffiError({ errorName: "UniffiBackendFactory", message: "createBackendSession requires factory(host)" });
}

const OBJECT_LEASE_STATE = new WeakMap();
const OBJECT_CLASS_REGISTRY = new Map();

export class ObjectLease {
  constructor() {
    throw new UniffiError({
      errorName: "UniffiObjectConstructor",
      message: "object wrappers are created by the generated facade",
    });
  }
  dispose() {
    const state = OBJECT_LEASE_STATE.get(this);
    if (!state || state.disposed) return;
    state.disposed = true;
    const handle = state.handle;
    state.handle = null;
    try {
      if (state.session) {
        state.session.objects?.delete(this);
        state.session.releaseObject(handle);
      }
    } catch (_) {}
  }
}

function createObjectWrapper(PublicClass, session, typeId, handle) {
  if (typeof PublicClass !== "function") {
    throw new UniffiError({ errorName: "UniffiTypeDescriptor", message: "object class descriptor is not constructible" });
  }
  if (!session || typeof session !== "object") {
    throw new UniffiError({ errorName: "UniffiObjectSession", message: "object wrapper requires a backend session" });
  }
  const object = Object.create(PublicClass.prototype);
  OBJECT_LEASE_STATE.set(object, { handle, session, typeId, disposed: false });
  session.objects?.add(object);
  return object;
}

function objectState(value, expectedSession = null, expectedTypeId = null) {
  const state = OBJECT_LEASE_STATE.get(value);
  if (!state || state.disposed) throw new UniffiError({ errorName: "UniffiUseAfterDispose", message: "object lease was disposed" });
  if (expectedSession && state.session !== expectedSession) throw new UniffiError({ errorName: "UniffiObjectSession", message: "object lease belongs to another backend session" });
  if (expectedTypeId !== null && expectedTypeId !== undefined && state.typeId !== expectedTypeId) {
    throw new UniffiError({ errorName: "UniffiObjectType", message: "object lease belongs to another object type" });
  }
  return state;
}

function objectHandle(value, expectedSession = null, expectedTypeId = null) {
  return objectState(value, expectedSession, expectedTypeId).handle;
}

export function invokeObjectOperation(lease, descriptor, args = []) {
  const state = objectState(lease, null, descriptor?.receiverTypeId);
  return makeOperation(state.session, descriptor)(lease, ...args);
}

function normalizeOperationError(raw, descriptor, session) {
  const declared = descriptor?.throws;
  if (!declared) return asUniffiError(raw);
  if (!descriptor?.context?.types) {
    throw new UniffiError({ errorName: "UniffiErrorProtocol", message: "declared error is missing its type descriptor" });
  }
  const typeDescriptor = descriptor.context.types[declared.typeId];
  if (!typeDescriptor) {
    throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `missing declared error descriptor ${String(declared.typeId)}` });
  }
  const details = errorDescriptor(raw);
  if (typeDescriptor.kind !== "enum") return asUniffiError(raw);
  if (typeof details.variant !== "string") {
    throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `declared error ${declared.name} is missing its variant` });
  }
  const variant = typeDescriptor.variants?.[details.variant];
  if (!variant) {
    throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `unknown ${declared.name} error variant ${details.variant}` });
  }
  const fields = variant.fields || {};
  let data = details.data;
  if (Object.keys(fields).length > 0) {
    if (!data || typeof data !== "object" || Array.isArray(data)) {
      throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `error variant ${details.variant} requires a payload object` });
    }
    const payload = {};
    for (const [name, field] of Object.entries(fields)) {
      if (!own(data, name)) {
        throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `error variant ${details.variant} is missing payload field ${name}` });
      }
      payload[name] = liftValue(data[name], field?.type || field, session, descriptor.context, descriptor);
    }
    data = payload;
  }
  const ErrorClass = descriptor.context.errorClasses?.[declared.typeId];
  if (typeof ErrorClass !== "function") {
    throw new UniffiError({ errorName: "UniffiErrorProtocol", message: `missing generated error class ${String(declared.typeId)}` });
  }
  const result = new ErrorClass(details.message, details.variant, data);
  result.errorName = declared.name || result.errorName;
  result.descriptor = typeDescriptor;
  if (typeof details.stack === "string") result.stack = details.stack;
  return result;
}

function lowerCallbackError(raw, methodSpec, context, session) {
  if (raw instanceof UniffiError && raw.errorName.startsWith("UniffiCallback")) return raw;
  const declared = methodSpec?.throws;
  if (!declared) return raw;
  if (!context?.types) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: "callback error is missing its type descriptor" });
  const typeDescriptor = context.types[declared.typeId];
  if (!typeDescriptor || typeDescriptor.kind !== "enum") throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: `missing callback error descriptor ${String(declared.typeId)}` });
  const details = errorDescriptor(raw);
  if (typeof details.variant !== "string") throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: "callback error is missing its variant" });
  const variant = typeDescriptor.variants?.[details.variant];
  if (!variant) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: `unknown callback error variant ${details.variant}` });
  const fields = variant.fields || {};
  let data = details.data;
  if (Object.keys(fields).length > 0) {
    if (!data || typeof data !== "object" || Array.isArray(data)) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: `callback error variant ${details.variant} requires a payload object` });
    const payload = {};
    for (const [name, field] of Object.entries(fields)) {
      if (!own(data, name)) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: `callback error variant ${details.variant} is missing payload field ${name}` });
      payload[name] = lowerValue(data[name], field?.type || field, context, session);
    }
    data = payload;
  }
  const ErrorClass = context.errorClasses?.[declared.typeId];
  if (typeof ErrorClass !== "function") {
    // Hand-authored runtime contexts (used by embedders and low-level tests)
    // do not carry generated classes.  Generated facades always provide the
    // registry above; if it is present but incomplete, report a protocol
    // error instead of silently returning a generic declared error.
    if (context.errorClasses) throw new UniffiError({ errorName: "UniffiCallbackProtocol", message: `missing generated callback error class ${String(declared.typeId)}` });
    return new UniffiError({ errorName: declared.name || details.errorName, variant: details.variant, data, message: details.message, descriptor: typeDescriptor, stack: details.stack });
  }
  const result = new ErrorClass(details.message, details.variant, data);
  result.errorName = declared.name || result.errorName;
  result.descriptor = typeDescriptor;
  if (typeof details.stack === "string") result.stack = details.stack;
  return result;
}

function lowerPrimitive(value, name) {
  if (value === undefined) throw new UniffiError({ errorName: "UniffiUndefined", message: "undefined is not a UniFFI value; use null for optional" });
  if (name === "I64" || name === "U64") {
    let result;
    try { result = typeof value === "bigint" ? value : (typeof value === "number" && Number.isSafeInteger(value) ? BigInt(value) : (typeof value === "string" ? BigInt(value) : (() => { throw new Error(); })())); }
    catch (_) { throw new UniffiError({ errorName: "UniffiNumericError", message: `${name} requires a lossless bigint` }); }
    const bigintBounds = {
      I64: [-(1n << 63n), (1n << 63n) - 1n],
      U64: [0n, (1n << 64n) - 1n],
    }[name];
    if (bigintBounds && (result < bigintBounds[0] || result > bigintBounds[1])) throw new UniffiError({ errorName: "UniffiNumericError", message: `${name} is out of range` });
    return result;
  }
  if (name === "Bytes") {
    if (!(value instanceof Uint8Array)) throw new UniffiError({ errorName: "UniffiBytesType", message: "bytes require Uint8Array" });
    return value;
  }
  const integerBounds = {
    I8: [-128, 127], U8: [0, 255], I16: [-32768, 32767], U16: [0, 65535],
    I32: [-2147483648, 2147483647], U32: [0, 4294967295],
  }[name];
  if (integerBounds) {
    if (typeof value !== "number" || !Number.isInteger(value) || value < integerBounds[0] || value > integerBounds[1]) throw new UniffiError({ errorName: "UniffiNumericError", message: `${name} requires an in-range integer` });
  } else if (name === "F32" || name === "F64") {
    if (typeof value !== "number") throw new UniffiError({ errorName: "UniffiNumericError", message: `${name} requires a number` });
  } else if (name === "Bool" && typeof value !== "boolean") throw new UniffiError({ errorName: "UniffiValueType", message: "bool requires a boolean" });
  else if (name === "String" && typeof value !== "string") throw new UniffiError({ errorName: "UniffiValueType", message: "string requires a string" });
  return value;
}

function liftPrimitive(value, name) {
  if (name === "I64" || name === "U64") {
    let result;
    try {
      result = typeof value === "bigint" ? value : (typeof value === "number" && Number.isSafeInteger(value) ? BigInt(value) : (typeof value === "string" ? BigInt(value) : (() => { throw new Error(); })()));
    } catch (_) {
      throw new UniffiError({ errorName: "UniffiNumericError", message: name + " requires a lossless bigint from backend" });
    }
    const bounds = name === "I64" ? [-(1n << 63n), (1n << 63n) - 1n] : [0n, (1n << 64n) - 1n];
    if (result < bounds[0] || result > bounds[1]) throw new UniffiError({ errorName: "UniffiNumericError", message: name + " is out of range" });
    return result;
  }
  if (name === "Bytes") {
    if (!(value instanceof Uint8Array)) throw new UniffiError({ errorName: "UniffiBytesType", message: "backend bytes must be Uint8Array" });
    return value;
  }
  const integerBounds = {
    I8: [-128, 127], U8: [0, 255], I16: [-32768, 32767], U16: [0, 65535],
    I32: [-2147483648, 2147483647], U32: [0, 4294967295],
  }[name];
  if (integerBounds && (typeof value !== "number" || !Number.isInteger(value) || value < integerBounds[0] || value > integerBounds[1])) {
    throw new UniffiError({ errorName: "UniffiNumericError", message: name + " requires an in-range integer from backend" });
  }
  if ((name === "F32" || name === "F64") && typeof value !== "number") throw new UniffiError({ errorName: "UniffiNumericError", message: name + " requires a number from backend" });
  if (name === "Bool" && typeof value !== "boolean") throw new UniffiError({ errorName: "UniffiValueType", message: "backend bool must be boolean" });
  if (name === "String" && typeof value !== "string") throw new UniffiError({ errorName: "UniffiValueType", message: "backend string must be string" });
  return value;
}

function resolveNamedDescriptor(descriptor, context) {
  if (!context || !context.types || !descriptor || descriptor.kind !== "named") return descriptor;
  const resolved = context.types[descriptor.typeId];
  if (!resolved) throw new UniffiError({ errorName: "UniffiTypeDescriptor", message: `missing named type descriptor ${String(descriptor.typeId)}` });
  return resolved;
}

function typeDescriptorForName(descriptors, name) {
  const id = descriptors.typeNames?.[name];
  return id === undefined ? undefined : descriptors.types?.[id];
}

function applyCustomExpression(expression, value) {
  if (expression === undefined || expression === null) return value;
  if (typeof expression !== "function") throw new UniffiError({ errorName: "UniffiCustomTypeError", message: "custom conversion descriptor is not callable" });
  try { return expression(value); }
  catch (error) { throw new UniffiError({ errorName: "UniffiCustomTypeError", message: `custom conversion failed: ${error?.message || String(error)}` }); }
}

function appendValuePath(path, segment) {
  if (!path) return null;
  return `${path}.${segment}`;
}

function streamPlanError(message) {
  return new UniffiError({ errorName: "UniffiStreamPlan", message });
}

function streamResourceAt(operation, path, direction) {
  const resources = operation?.streamResources;
  if (!Array.isArray(resources)) throw streamPlanError("operation is missing canonical stream resources");
  const matches = resources.filter((resource) => resource && resource.path === path && resource.direction === direction);
  if (matches.length !== 1) throw streamPlanError(`expected one ${direction} stream resource at ${String(path)}`);
  return matches[0];
}

function pathForStream(operation, descriptor, direction) {
  const resources = operation?.streamResources;
  if (!Array.isArray(resources)) throw streamPlanError("operation is missing canonical stream resources");
  if (direction === "Output" && descriptor?.kind === "outputStream") return "return";
  const matches = resources.filter((resource) => resource && resource.direction === direction);
  if (matches.length !== 1) throw streamPlanError(`cannot select one ${direction} stream resource`);
  return matches[0].path;
}

function streamSlot(resource, kind) {
  const id = resource?.slots?.[kind];
  if (!Number.isInteger(id) || id < 0) throw streamPlanError(`stream resource is missing ${kind} slot`);
  return id;
}

function streamStep(step) {
  if (!isObject(step) || typeof step.kind !== "string") throw new UniffiError({ errorName: "UniffiStreamProtocolError", message: "stream step must be tagged" });
  if (step.kind === "item" && own(step, "value") && !own(step, "error")) return { kind: "item", value: step.value };
  if (step.kind === "done" && Object.keys(step).length === 1) return { kind: "done" };
  if (step.kind === "error" && own(step, "error") && !own(step, "value")) return { kind: "error", error: step.error };
  throw new UniffiError({ errorName: "UniffiStreamProtocolError", message: `invalid stream ${step.kind} step` });
}

function streamErrorLifter(resource, context, session, operation) {
  const errorDescriptor = resource?.error;
  if (errorDescriptor?.kind === "named") {
    const named = resolveNamedDescriptor(errorDescriptor, context);
    if (named?.kind === "enum" && named.error) {
      const declared = { throws: { name: errorDescriptor.name, typeId: errorDescriptor.typeId }, context };
      return (raw) => normalizeOperationError(raw, declared, session);
    }
  }
  return (raw) => asUniffiError(raw);
}

function createBackendInputStream(session, handle, resource, context, operation) {
  const pullId = streamSlot(resource, "InputStreamPull");
  const cancelId = streamSlot(resource, "InputStreamCancel");
  const liftItem = (item) => liftValue(item, resource.item, session, context, operation);
  const liftError = streamErrorLifter(resource, context, session, operation);
  let cancelled = false;
  let released = false;
  let pending = false;
  const marker = {
    __uniffiInputStream: true,
    handle,
    async next() {
      if (cancelled) return { done: true, value: undefined };
      if (pending) throw new UniffiError({ errorName: "UniffiInputStreamConcurrentNext", message: "concurrent input stream pull" });
      pending = true;
      try {
        const step = streamStep(await session.invokeAsync(pullId, [handle]));
        if (step.kind === "done") { cancelled = true; return { done: true, value: undefined }; }
        if (step.kind === "error") { cancelled = true; throw liftError(step.error); }
        return { done: false, value: liftItem(step.value) };
      } finally { pending = false; }
    },
    async cancel() {
      if (cancelled) return;
      cancelled = true;
      try { await session.invokeAsync(cancelId, [handle]); } finally { if (!released) marker.release(); }
    },
    release() {
      if (released) return;
      released = true;
      session.releaseInputStream(handle);
    },
  };
  return marker;
}

export function lowerValue(value, descriptor, context = null, session = null, operation = null, path = null) {
  if (!descriptor) return value;
  if (descriptor.kind === "optional") {
    if (value === undefined) throw new UniffiError({ errorName: "UniffiUndefined", message: "undefined is not a UniFFI value; use null for an optional value" });
    return value === null ? null : lowerValue(value, descriptor.inner, context, session, operation, path);
  }
  if (value === undefined) throw new UniffiError({ errorName: "UniffiUndefined", message: "undefined is not a UniFFI value; use null for an optional value" });
  switch (descriptor.kind) {
    case "scalar": return lowerPrimitive(value, descriptor.name);
    case "timestamp": if (!(value instanceof Date) || Number.isNaN(value.getTime())) throw new UniffiError({ errorName: "UniffiTimestampType", message: "timestamp requires a valid Date" }); return value;
    case "duration": if (typeof value !== "number" || !Number.isFinite(value) || value < 0) throw new UniffiError({ errorName: "UniffiDurationType", message: "duration requires a finite non-negative number" }); return value;
    case "sequence": if (!Array.isArray(value)) throw new UniffiError({ errorName: "UniffiSequenceType", message: "sequence requires an Array" }); return value.map((item) => lowerValue(item, descriptor.inner, context, session, operation, appendValuePath(path, "item")));
    case "map": if (!(value instanceof Map)) throw new UniffiError({ errorName: "UniffiMapType", message: "map requires a Map" }); return new Map([...value].map(([key, item]) => [lowerValue(key, descriptor.key, context, session, operation, appendValuePath(path, "key")), lowerValue(item, descriptor.value, context, session, operation, appendValuePath(path, "value"))]));
    case "set": if (!(value instanceof Set)) throw new UniffiError({ errorName: "UniffiSetType", message: "set requires a Set" }); return new Set([...value].map((item) => lowerValue(item, descriptor.inner, context, session, operation, appendValuePath(path, "set-item"))));
    case "inputStream": {
      if (!session || !session.createInputStream) return value;
      const marker = session.createInputStream(value, {
        lowerItem: (item) => lowerValue(item, descriptor.inner, context, session, operation, appendValuePath(path, "item")),
      });
      return marker && own(marker, "handle") ? marker.handle : marker;
    }
    case "outputStream": return value;
    case "named": {
      const named = resolveNamedDescriptor(descriptor, context);
      if (named === descriptor) return value;
      if (named.kind === "custom") {
        const customValue = applyCustomExpression(named.fromCustom, value);
        return lowerValue(customValue, named.builtin, context, session, operation, path);
      }
      if (named.kind === "object") {
        if (named.callback) {
          const callbackTypeId = assertCallbackTypeId(descriptor.typeId);
          const canonical = path && operation?.callbackContracts?.[path];
          if (canonical) {
            assertCallbackTypeId(canonical.callbackTypeId);
            if (canonical.callbackTypeId !== callbackTypeId) throw new UniffiError({ errorName: "UniffiCallbackContract", message: `callback type mismatch at ${path}` });
            const contract = { ...canonical, methods: named.methods || {}, context };
            return session && session.registerCallback ? session.registerCallback(callbackTypeId, value, contract) : value;
          }
          if (!named.callbackOnly && value instanceof ObjectLease) return objectHandle(value, session, descriptor.typeId);
          throw new UniffiError({ errorName: "UniffiCallbackContract", message: `missing canonical callback contract at ${path || "unknown path"}` });
        }
        if (!(value instanceof ObjectLease)) throw new UniffiError({ errorName: "UniffiObjectType", message: `expected object wrapper ${descriptor.name}` });
        return objectHandle(value, session, descriptor.typeId);
      }
      if (named.kind === "callback") {
        const callbackTypeId = assertCallbackTypeId(descriptor.typeId);
        const canonical = path && operation?.callbackContracts?.[path];
        if (!canonical) throw new UniffiError({ errorName: "UniffiCallbackContract", message: `missing canonical callback contract at ${path || "unknown path"}` });
        assertCallbackTypeId(canonical.callbackTypeId);
        if (canonical.callbackTypeId !== callbackTypeId) throw new UniffiError({ errorName: "UniffiCallbackContract", message: `callback type mismatch at ${path}` });
        const contract = { ...canonical, methods: named.methods || {}, context };
        return session && session.registerCallback ? session.registerCallback(callbackTypeId, value, contract) : value;
      }
      if (named.kind === "record") {
        if (!isObject(value) || Array.isArray(value)) throw new UniffiError({ errorName: "UniffiRecordType", message: `expected record ${descriptor.name}` });
        const result = {};
        for (const [name, field] of Object.entries(named.fields || {})) {
          const fieldType = field?.type || field;
          let fieldValue;
          if (!own(value, name)) {
            if (field?.rustDefault) continue;
            fieldValue = field && own(field, "default") ? field.default : undefined;
          } else {
            fieldValue = value[name];
          }
          result[name] = lowerValue(fieldValue, fieldType, context, session, operation, appendValuePath(path, `field[${name}]`));
        }
        return result;
      }
      if (named.kind === "enum") {
        if (named.unit) {
          if (typeof value !== "string" || !named.variants?.[value]) throw new UniffiError({ errorName: "UniffiEnumType", message: `expected unit ${descriptor.name} variant` });
          return value;
        }
        if (!isObject(value) || typeof value.tag !== "string") throw new UniffiError({ errorName: "UniffiEnumType", message: `expected tagged ${descriptor.name}` });
        const variant = named.variants?.[value.tag];
        if (!variant) throw new UniffiError({ errorName: "UniffiEnumVariant", message: `unknown ${descriptor.name} variant ${value.tag}` });
        const result = { tag: value.tag };
        for (const [name, field] of Object.entries(variant.fields || {})) result[name] = lowerValue(value[name], field, context, session, operation, appendValuePath(appendValuePath(path, `variant[${value.tag}]`), `field[${name}]`));
        return result;
      }
      return value;
    }
    default: return value;
  }
}

export function liftValue(value, descriptor, session = null, context = null, operation = null) {
  if (!descriptor) return value;
  if (value === undefined) throw new UniffiError({ errorName: "UniffiUndefined", message: "undefined is not a UniFFI value; backend omitted a required value" });
  if (value === null) {
    if (descriptor.kind === "optional") return null;
    throw new UniffiError({ errorName: "UniffiNullValue", message: `null is not valid for ${descriptor.kind}` });
  }
  switch (descriptor.kind) {
    case "scalar":
      return liftPrimitive(value, descriptor.name);
    case "timestamp":
      if (!(value instanceof Date) || Number.isNaN(value.getTime())) throw new UniffiError({ errorName: "UniffiTimestampType", message: "backend timestamp must be a valid Date" });
      return value;
    case "duration":
      if (typeof value !== "number" || !Number.isFinite(value) || value < 0) throw new UniffiError({ errorName: "UniffiDurationType", message: "backend duration must be finite and non-negative" });
      return value;
    case "optional": return value === null ? null : liftValue(value, descriptor.inner, session, context, operation);
    case "sequence":
      if (!Array.isArray(value)) throw new UniffiError({ errorName: "UniffiSequenceType", message: "backend sequence must be an Array" });
      return value.map((item) => liftValue(item, descriptor.inner, session, context, operation));
    case "map":
      if (!(value instanceof Map)) throw new UniffiError({ errorName: "UniffiMapType", message: "backend map must be a Map" });
      return new Map([...value].map(([key, item]) => [liftValue(key, descriptor.key, session, context, operation), liftValue(item, descriptor.value, session, context, operation)]));
    case "set":
      if (!(value instanceof Set)) throw new UniffiError({ errorName: "UniffiSetType", message: "backend set must be a Set" });
      return new Set([...value].map((item) => liftValue(item, descriptor.inner, session, context, operation)));
    case "inputStream": {
      if (value === null || value === undefined) throw new UniffiError({ errorName: "UniffiStreamType", message: "backend input stream handle is missing" });
      if (!session || !operation) return value;
      const resource = streamResourceAt(operation, pathForStream(operation, descriptor, "Input"), "Input");
      const handle = value && own(value, "handle") ? value.handle : value;
      return createBackendInputStream(session, handle, resource, context, operation);
    }
    case "outputStream": {
      if (value === null || value === undefined) throw new UniffiError({ errorName: "UniffiStreamType", message: "backend output stream handle is missing" });
      if ((typeof value === "object" || typeof value === "function") && typeof value.next === "function") return value;
      const handle = value && own(value, "handle") ? value.handle : value;
      if (handle === null || handle === undefined) throw new UniffiError({ errorName: "UniffiStreamType", message: "backend output stream handle is missing" });
      if (session && typeof session.createOutputStream === "function") {
        const resource = streamResourceAt(operation, pathForStream(operation, descriptor, "Output"), "Output");
        const nextId = streamSlot(resource, "OutputStreamNext");
        const cancelId = streamSlot(resource, "OutputStreamCancel");
        return session.createOutputStream({
          handle,
          next: (activeHandle) => session.invokeAsync(nextId, [activeHandle]),
          cancel: (activeHandle) => session.invokeAsync(cancelId, [activeHandle]),
          liftItem: (item) => liftValue(item, descriptor.inner, session, context, operation),
          liftError: streamErrorLifter(resource, context, session, operation),
        });
      }
      return value;
    }
    case "named": {
      const named = resolveNamedDescriptor(descriptor, context);
      if (named === descriptor) return value;
      if (named.kind === "custom") return applyCustomExpression(named.intoCustom, liftValue(value, named.builtin, session, context, operation));
      if (named.kind === "object") {
        if (named.callback) return value;
        const classEntry = context?.classes?.[descriptor.typeId];
        if (!classEntry) throw new UniffiError({ errorName: "UniffiTypeDescriptor", message: `missing object class descriptor ${String(descriptor.typeId)}` });
        if (typeof classEntry.construct === "function") return classEntry.construct(session, value);
        if (typeof classEntry.publicClass === "function") return createObjectWrapper(classEntry.publicClass, session, descriptor.typeId, value);
        throw new UniffiError({ errorName: "UniffiTypeDescriptor", message: `invalid object class descriptor ${String(descriptor.typeId)}` });
      }
      if (named.kind === "record") {
        if (!isObject(value) || Array.isArray(value)) throw new UniffiError({ errorName: "UniffiRecordType", message: `backend record ${descriptor.name} must be an object` });
        const result = {};
        for (const [name, field] of Object.entries(named.fields || {})) {
          if (!own(value, name)) throw new UniffiError({ errorName: "UniffiRecordType", message: `backend record ${descriptor.name} is missing field ${name}` });
          result[name] = liftValue(value[name], field?.type || field, session, context, operation);
        }
        return result;
      }
      if (named.kind === "enum") {
        if (named.unit) {
          if (typeof value !== "string" || !named.variants?.[value]) throw new UniffiError({ errorName: "UniffiEnumVariant", message: `unknown backend ${descriptor.name} unit variant ${String(value)}` });
          return value;
        }
        if (!isObject(value) || Array.isArray(value) || typeof value.tag !== "string") throw new UniffiError({ errorName: "UniffiEnumType", message: `backend enum ${descriptor.name} must be tagged` });
        const variant = named.variants?.[value.tag];
        if (!variant) throw new UniffiError({ errorName: "UniffiEnumVariant", message: `unknown backend ${descriptor.name} variant ${value.tag}` });
        const result = { tag: value.tag };
        for (const [name, field] of Object.entries(variant.fields || {})) {
          if (!own(value, name)) throw new UniffiError({ errorName: "UniffiEnumVariant", message: `backend enum ${descriptor.name} variant ${value.tag} is missing field ${name}` });
          result[name] = liftValue(value[name], field, session, context, operation);
        }
        return result;
      }
      return value;
    }
    default: return value;
  }
}

function makeOperation(session, descriptor) {
  return (...args) => {
    if (args.length > descriptor.args.length + (descriptor.receiver ? 1 : 0)) throw new UniffiError({ errorName: "UniffiArgumentCount", message: `too many arguments for ${descriptor.name}` });
    const frame = session.beginCallFrame ? session.beginCallFrame() : null;
    const finishFrame = () => { try { session.endCallFrame?.(frame); } catch (_) {} };
    let receiver;
    let lowered;
    let nativeReceiver;
    let nativeArgs;
    try {
      receiver = descriptor.receiver || descriptor.valueSelf ? args.shift() : undefined;
      lowered = [];
      for (let index = 0; index < descriptor.args.length; index += 1) {
        const argument = descriptor.args[index];
        if (index >= args.length) {
          if (argument.rustDefault) break;
          if (argument.default !== undefined) {
            lowered.push(lowerValue(argument.default, argument.type, descriptor.context || descriptor, session, descriptor, `argument[${index}]`));
            continue;
          }
          throw new UniffiError({ errorName: "UniffiArgumentCount", message: `missing argument ${argument.name} for ${descriptor.name}` });
        }
        lowered.push(lowerValue(args[index], argument.type, descriptor.context || descriptor, session, descriptor, `argument[${index}]`));
      }
      nativeReceiver = descriptor.receiver
        ? descriptor.ownerSurface === "value"
          ? lowerValue(receiver, { kind: "named", name: descriptor.receiverType, typeId: descriptor.receiverTypeId }, descriptor.context || descriptor, session, descriptor, "receiver")
          : (receiver instanceof ObjectLease ? objectHandle(receiver, session, descriptor.receiverTypeId) : receiver)
        : receiver;
      nativeArgs = descriptor.receiver || descriptor.valueSelf ? [nativeReceiver, ...lowered] : lowered;
    } catch (error) {
      finishFrame();
      throw error;
    }
    if (descriptor.kind === "OutputStreamStart" && descriptor.returnType?.kind === "outputStream") {
      const resource = streamResourceAt(descriptor, "return", "Output");
      const nextId = streamSlot(resource, "OutputStreamNext");
      const cancelId = streamSlot(resource, "OutputStreamCancel");
      return session.createOutputStream({
        start: () => descriptor.async ? session.invokeAsync(descriptor.id, nativeArgs) : session.invokeSync(descriptor.id, nativeArgs),
        next: (handle) => session.invokeAsync(nextId, [handle]),
        cancel: (handle) => session.invokeAsync(cancelId, [handle]),
        liftItem: (item) => liftValue(item, descriptor.returnType.inner, session, descriptor.context || descriptor, descriptor),
        liftError: streamErrorLifter(resource, descriptor.context || descriptor, session, descriptor),
        onClose: finishFrame,
      });
    }
    const lift = (value) => descriptor.returnType == null
      ? undefined
      : liftValue(value, descriptor.returnType, session, descriptor.context || descriptor, descriptor);
    try {
      const invoke = descriptor.async ? session.invokeAsync(descriptor.id, nativeArgs) : session.invokeSync(descriptor.id, nativeArgs);
      if (descriptor.async) return invoke.then((value) => { finishFrame(); return lift(value); }, (error) => { finishFrame(); throw normalizeOperationError(error, descriptor, session); });
      const value = lift(invoke);
      finishFrame();
      return value;
    } catch (error) {
      finishFrame();
      throw normalizeOperationError(error, descriptor, session);
    }
  };
}

export function invokeOperation(session, descriptor, args = []) {
  return makeOperation(session, descriptor)(...args);
}

function enumVariantConstructor(variantName, variantDescriptor) {
  return (value) => {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      throw new UniffiError({ errorName: "UniffiEnumPayload", message: "enum variant payload is required" });
    }
    const result = { tag: variantName };
    for (const fieldName of Object.keys(variantDescriptor?.fields || {})) {
      if (!own(value, fieldName)) throw new UniffiError({ errorName: "UniffiEnumPayload", message: `missing enum variant payload field ${fieldName}` });
      result[fieldName] = value[fieldName];
    }
    return result;
  };
}

/** Construct a namespace facade from descriptors emitted by the Rust AST
 * printer.  Every call goes through the session's dense operation ID. */
export function createFacade(session, descriptors = {}) {
  if (!session || typeof session.invokeSync !== "function" || typeof session.invokeAsync !== "function") throw new UniffiError({ errorName: "UniffiSessionType", message: "createFacade requires a BackendSession" });
  if (descriptors.closePolicy !== undefined) installClosePolicy(session, descriptors.closePolicy);
  const namespace = {};
  for (const descriptor of Object.values(descriptors.operations || {})) {
    descriptor.context = descriptors;
    if (descriptor.surface === "namespace" && !descriptor.receiver && descriptor.componentId === descriptors.componentId) namespace[descriptor.name] = makeOperation(session, descriptor);
  }
  const objectConstructors = new Map();
  for (const descriptor of Object.values(descriptors.operations || {})) {
    if (descriptor.surface === "object" && descriptor.ownerTypeId !== null && descriptor.ownerTypeId !== undefined && descriptor.kind === "Constructor" && !descriptor.receiver) {
      const constructors = objectConstructors.get(descriptor.ownerTypeId) || [];
      constructors.push(descriptor);
      objectConstructors.set(descriptor.ownerTypeId, constructors);
    }
  }
  for (const [typeId, classEntry] of Object.entries(descriptors.classes || {})) {
    const typeName = classEntry?.typeName;
    if (typeof typeName !== "string") continue;
    const registryKey = typeof classEntry.typeKey === "string" ? classEntry.typeKey : String(typeId);
    const existing = OBJECT_CLASS_REGISTRY.get(registryKey);
    // Prefer the declaration owned by its component over a foreign projection
    // encountered first.  Every component then shares the same prototype and
    // factory for this source type.
    const canonical = !existing || (classEntry.public === true && existing.public !== true)
      ? { ...classEntry, typeId: Number(typeId) }
      : existing;
    OBJECT_CLASS_REGISTRY.set(registryKey, canonical);
    const PublicClass = canonical?.publicClass;
    if (typeof PublicClass !== "function") continue;
    const canonicalEntry = {
      ...canonical,
      construct: (ownerSession, handle) => createObjectWrapper(PublicClass, ownerSession, Number(typeId), handle),
    };
    descriptors.classes[typeId] = canonicalEntry;
    const BoundClass = function BoundObjectConstructor() {
      throw new UniffiError({ errorName: "UniffiObjectConstructor", message: "object wrappers are created by the facade" });
    };
    Object.setPrototypeOf(BoundClass, PublicClass);
    BoundClass.prototype = PublicClass.prototype;
    for (const descriptor of objectConstructors.get(Number(typeId)) || []) BoundClass[descriptor.name] = makeOperation(session, descriptor);
    Object.freeze(BoundClass);
    if (classEntry?.public !== false) namespace[typeName] = BoundClass;
  }
  const valueTypeNames = new Set(Object.keys(descriptors.values || {}));
  for (const typeName of descriptors.publicTypes || []) {
    const typeDescriptor = typeDescriptorForName(descriptors, typeName);
    if (typeDescriptor?.kind === "enum" && !typeDescriptor.error) valueTypeNames.add(typeName);
  }
  for (const typeName of valueTypeNames) {
    const methods = descriptors.values?.[typeName] || {};
    const typeDescriptor = typeDescriptorForName(descriptors, typeName);
    if (typeDescriptor?.error) continue;
    const valueSurface = {};
    if (typeDescriptor?.kind === "enum" && !typeDescriptor.error) {
      for (const [variantName, variantDescriptor] of Object.entries(typeDescriptor.variants || {})) valueSurface[variantName] = typeDescriptor.unit ? variantName : enumVariantConstructor(variantName, variantDescriptor);
    }
    for (const [publicName, operationId] of Object.entries(methods)) {
      const descriptor = descriptors.operations?.[operationId];
      if (descriptor && descriptor.componentId === descriptors.componentId && descriptor.surface === "value" && !own(valueSurface, publicName)) valueSurface[publicName] = makeOperation(session, descriptor);
    }
    if (typeDescriptor?.kind !== "object" || !namespace[typeName]) namespace[typeName] = Object.freeze(valueSurface);
  }
  return Object.freeze(namespace);
}
