/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Rust wasm-bindgen shim generator.
//!
//! Covers (Path A contract v1):
//!
//! - Scalars, bool, String, Vec<u8>, Option<T>, Vec<T>
//! - Records / enums via **explicit lowering/lifting**. The shim emits a
//!   `__lower_<name>` / `__lift_<name>` helper for every record and
//!   non-error enum. Lowering reads fields via `js_sys::Reflect::get`;
//!   lifting builds a fresh `js_sys::Object` / string / array. There is
//!   no `serde` or `serde_wasm_bindgen` anywhere in the wasm link — not
//!   on the downstream core crate, not in the generated shim, and not
//!   in the auto-generated wasm host crate.
//! - Error enums still propagate via `JsError::new(&format!("{e:?}"))`
//!   because they only cross the boundary as exceptions, never as value
//!   returns or arguments.
//! - Opaque objects (struct + trait-interface) via per-object thread-local
//!   registry. Constructors returning `Self` or `Arc<Self>` both work via
//!   the `__Coerce` autoref-specialisation trick.
//! - Free functions taking or returning object handles.
//! - Callback interfaces / `with_foreign` traits: the JS object is
//!   registered in the runtime callback map, its handle is lowered as a
//!   `u32`, and the shim wraps it in a generated `__Js<Name>` struct that
//!   implements the biz trait by dispatching back to JS via a pair of
//!   `thread_local!`-stored `js_sys::Function`s. `Drop` releases the JS
//!   registry slot.
//!
//! Anything still unsupported (Map/Set) is emitted as a stub
//! that throws `JsError` at runtime — never a silent skip. Timestamp
//! and duration are covered with explicit `Date` / millisecond
//! lowering and lifting.

use std::fmt::Write;

use heck::ToSnakeCase;
use uniffi_bindgen::interface::{
    AsType, ComponentInterface, Constructor, Enum, Function, Method, Object, ObjectImpl, Record,
    Type,
};

pub fn render_wasm_rust(ci: &ComponentInterface) -> String {
    let crate_ident = ci.crate_name().replace('-', "_");
    let mut out = String::new();
    writeln!(
        out,
        "// AUTOGENERATED by uniffi_bindgen_javascript (wasm flavor)."
    )
    .unwrap();
    writeln!(
        out,
        "// Do not edit by hand; regenerate via uniffi-bindgen."
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// wasm-bindgen shim for the `{}` namespace.",
        ci.namespace()
    )
    .unwrap();
    writeln!(out).unwrap();
    // NB: no inner `#![allow(...)]` — this file is consumed via
    // `include!()` from the auto-generated host crate, and inner
    // attributes aren't permitted inside an `include!` expansion.
    writeln!(
        out,
        "#[allow(unused_imports)] use wasm_bindgen::prelude::*;"
    )
    .unwrap();
    writeln!(out, "#[allow(unused_imports)] use wasm_bindgen::JsCast;").unwrap();
    writeln!(
        out,
        "#[allow(unused_imports)] use std::collections::HashMap;"
    )
    .unwrap();
    writeln!(out, "#[allow(unused_imports)] use std::sync::Arc;").unwrap();
    writeln!(
        out,
        "#[allow(unused_imports)] use std::cell::{{Cell, RefCell}};"
    )
    .unwrap();
    writeln!(out).unwrap();

    let has_objects = ci
        .object_definitions()
        .iter()
        .any(|o| !matches!(o.imp(), ObjectImpl::CallbackTrait));
    let has_cb_objects = ci
        .object_definitions()
        .iter()
        .any(|o| matches!(o.imp(), ObjectImpl::CallbackTrait));
    let has_cb_ifaces = !ci.callback_interface_definitions().is_empty();
    let has_callbacks = has_cb_objects || has_cb_ifaces;

    // Emit explicit `__lower_<name>` / `__lift_<name>` helpers for
    // every record and non-error enum.
    emit_value_helpers(&mut out, ci, &crate_ident);
    emit_temporal_helpers(&mut out);

    if has_objects {
        emit_object_helpers(&mut out);
    }
    if has_callbacks {
        emit_callback_helpers(&mut out);
    }

    // Registries + shims for opaque objects (struct / trait-interface).
    for obj in ci.object_definitions() {
        if matches!(obj.imp(), ObjectImpl::CallbackTrait) {
            continue;
        }
        render_object(&mut out, &crate_ident, obj);
        writeln!(out).unwrap();
    }

    // `__Js<Name>` wrappers for each callback trait.
    for cbi in ci.callback_interface_definitions() {
        render_callback_wrapper(
            &mut out,
            &crate_ident,
            cbi.name(),
            &cbi.methods()
                .iter()
                .map(|m| (*m).clone())
                .collect::<Vec<_>>(),
        );
    }
    for obj in ci.object_definitions() {
        if !matches!(obj.imp(), ObjectImpl::CallbackTrait) {
            continue;
        }
        render_callback_wrapper(
            &mut out,
            &crate_ident,
            obj.name(),
            obj.methods()
                .into_iter()
                .cloned()
                .collect::<Vec<_>>()
                .as_slice(),
        );
    }

    // Value-type constructors/methods for records and non-error enums.
    for record in ci.record_definitions() {
        for constructor in record.constructors() {
            render_value_constructor(
                &mut out,
                &crate_ident,
                record.name(),
                &record.as_type(),
                constructor,
            );
            writeln!(out).unwrap();
        }
        for method in record.methods() {
            render_value_method(
                &mut out,
                &crate_ident,
                record.name(),
                &record.as_type(),
                method,
            );
            writeln!(out).unwrap();
        }
    }
    for enum_ in ci.enum_definitions() {
        if ci.is_name_used_as_error(enum_.name()) {
            continue;
        }
        for constructor in enum_.constructors() {
            render_value_constructor(
                &mut out,
                &crate_ident,
                enum_.name(),
                &enum_.as_type(),
                constructor,
            );
            writeln!(out).unwrap();
        }
        for method in enum_.methods() {
            render_value_method(
                &mut out,
                &crate_ident,
                enum_.name(),
                &enum_.as_type(),
                method,
            );
            writeln!(out).unwrap();
        }
    }

    // Free functions.
    for f in ci.function_definitions() {
        render_function(&mut out, &crate_ident, &f);
        writeln!(out).unwrap();
    }
    out
}

// ---------------------------------------------------------------------
// Helper blocks
// ---------------------------------------------------------------------

/// Emitted once when any struct/trait object is present.
fn emit_object_helpers(out: &mut String) {
    // Autoref-specialisation trick: the inherent impl on `__Coerce<Arc<T>>`
    // wins over the blanket trait impl on `__Coerce<T>`, so the same
    // `__Coerce(x).__into_arc()` call site handles both `-> Self` and
    // `-> Arc<Self>` constructor shapes with no codegen-side branching.
    writeln!(
        out,
        "struct __Coerce<T>(T);\n\
         impl<T: ?Sized> __Coerce<Arc<T>> {{ #[inline] fn __into_arc(self) -> Arc<T> {{ self.0 }} }}\n\
         trait __CoerceFallback<T> {{ fn __into_arc(self) -> Arc<T>; }}\n\
         impl<T> __CoerceFallback<T> for __Coerce<T> {{ #[inline] fn __into_arc(self) -> Arc<T> {{ Arc::new(self.0) }} }}"
    )
    .unwrap();
    writeln!(out).unwrap();
}

/// Emitted once when any callback-trait / `callback interface` is present.
/// Provides the thread-local `js_sys::Function` slots that the generated
/// `__Js<Name>` trait impls dispatch through, plus the `#[wasm_bindgen]`
/// setter that `backend-wasm.ts` calls during `initBackend()`.
fn emit_callback_helpers(out: &mut String) {
    writeln!(
        out,
        r#"thread_local! {{
    static __UNIFFI_CB_INVOKE: RefCell<Option<::js_sys::Function>> = RefCell::new(None);
    static __UNIFFI_CB_RELEASE: RefCell<Option<::js_sys::Function>> = RefCell::new(None);
}}

#[wasm_bindgen]
pub fn __uniffi_set_cb_invoker(invoke: ::js_sys::Function, release: ::js_sys::Function) {{
    __UNIFFI_CB_INVOKE.with(|c| *c.borrow_mut() = Some(invoke));
    __UNIFFI_CB_RELEASE.with(|c| *c.borrow_mut() = Some(release));
}}

fn __uniffi_cb_invoke(handle: u32, method: &str, args: JsValue) -> JsValue {{
    __UNIFFI_CB_INVOKE.with(|c| {{
        let b = c.borrow();
        let f = b.as_ref().expect("uniffi: callback invoker not installed");
        f.call3(
            &JsValue::NULL,
            &JsValue::from_f64(handle as f64),
            &JsValue::from_str(method),
            &args,
        )
        .unwrap_or(JsValue::NULL)
    }})
}}

fn __uniffi_cb_release(handle: u32) {{
    __UNIFFI_CB_RELEASE.with(|c| {{
        if let Some(f) = c.borrow().as_ref() {{
            let _ = f.call1(&JsValue::NULL, &JsValue::from_f64(handle as f64));
        }}
    }});
}}
"#
    )
    .unwrap();
    writeln!(out).unwrap();
}

/// Emitted once for timestamp/duration lowering/lifting. Keeps
/// chronological conversions explicit and serde-free.
fn emit_temporal_helpers(out: &mut String) {
    out.push_str(
        r#"#[allow(dead_code)]
fn __uniffi_lower_timestamp(__js: JsValue) -> Result<::std::time::SystemTime, JsError> {
    let __date: ::js_sys::Date = __js.dyn_into().map_err(|_| JsError::new("expected Date"))?;
    let __ms = __date.get_time();
    if !__ms.is_finite() {
        return Err(JsError::new("invalid Date"));
    }
    if __ms.abs() > 8.64e15 {
        return Err(JsError::new("timestamp exceeds JS Date range"));
    }
    let __ms_i = __ms.trunc() as i64;
    if __ms_i >= 0 {
        ::std::time::UNIX_EPOCH
            .checked_add(::std::time::Duration::from_millis(__ms_i as u64))
            .ok_or_else(|| JsError::new("timestamp overflow"))
    } else {
        ::std::time::UNIX_EPOCH
            .checked_sub(::std::time::Duration::from_millis((-__ms_i) as u64))
            .ok_or_else(|| JsError::new("timestamp overflow"))
    }
}

#[allow(dead_code)]
fn __uniffi_lift_timestamp(__ts: ::std::time::SystemTime) -> Result<JsValue, JsError> {
    let __ms = match __ts.duration_since(::std::time::UNIX_EPOCH) {
        Ok(__delta) => {
            (__delta.as_secs() as f64) * 1000.0 + (__delta.subsec_nanos() as f64) / 1_000_000.0
        }
        Err(__err) => {
            let __delta = __err.duration();
            -((__delta.as_secs() as f64) * 1000.0 + (__delta.subsec_nanos() as f64) / 1_000_000.0)
        }
    };
    if !__ms.is_finite() || __ms.abs() > 8.64e15 {
        return Err(JsError::new("timestamp exceeds JS Date range"));
    }
    Ok::<JsValue, JsError>(::js_sys::Date::new(&JsValue::from_f64(__ms)).into())
}

#[allow(dead_code)]
fn __uniffi_lower_duration(__js: JsValue) -> Result<::std::time::Duration, JsError> {
    let __ms = __js
        .as_f64()
        .ok_or_else(|| JsError::new("expected duration milliseconds number"))?;
    if !__ms.is_finite() {
        return Err(JsError::new("duration must be finite"));
    }
    if __ms < 0.0 {
        return Err(JsError::new("duration must be non-negative"));
    }
    let __secs_f = (__ms / 1000.0).trunc();
    if __secs_f > u64::MAX as f64 {
        return Err(JsError::new("duration exceeds Rust range"));
    }
    let mut __secs = __secs_f as u64;
    let mut __nanos = ((__ms % 1000.0) * 1_000_000.0).round() as u32;
    if __nanos == 1_000_000_000 {
        __nanos = 0;
        __secs = __secs
            .checked_add(1)
            .ok_or_else(|| JsError::new("duration exceeds Rust range"))?;
    }
    Ok::<::std::time::Duration, JsError>(::std::time::Duration::new(__secs, __nanos))
}

#[allow(dead_code)]
fn __uniffi_lift_duration(__dur: ::std::time::Duration) -> Result<JsValue, JsError> {
    let __ms = (__dur.as_secs() as f64) * 1000.0 + (__dur.subsec_nanos() as f64) / 1_000_000.0;
    if !__ms.is_finite() {
        return Err(JsError::new("duration exceeds JS number range"));
    }
    Ok::<JsValue, JsError>(JsValue::from_f64(__ms))
}
"#,
    );
    writeln!(out).unwrap();
}

// ---------------------------------------------------------------------
// Objects (struct + trait interface)
// ---------------------------------------------------------------------

fn rust_ty_for_object(crate_ident: &str, obj: &Object) -> String {
    match obj.imp() {
        ObjectImpl::Struct => format!("::{crate_ident}::{}", obj.name()),
        ObjectImpl::Trait => format!("dyn ::{crate_ident}::{}", obj.name()),
        ObjectImpl::CallbackTrait => format!("dyn ::{crate_ident}::{}", obj.name()),
    }
}

fn rust_ty_for_type(crate_ident: &str, ty: &Type) -> String {
    match ty {
        Type::Object { name, imp, .. } => match imp {
            ObjectImpl::Struct => format!("::{crate_ident}::{name}"),
            _ => format!("dyn ::{crate_ident}::{name}"),
        },
        Type::CallbackInterface { name, .. } => format!("dyn ::{crate_ident}::{name}"),
        _ => unreachable!(),
    }
}

fn render_object(out: &mut String, crate_ident: &str, obj: &Object) {
    let name = obj.name();
    let snake = name.to_snake_case();
    let rust_ty = rust_ty_for_object(crate_ident, obj);
    let reg = format!("__{}_REG", snake.to_uppercase());
    let next = format!("__{}_NEXT", snake.to_uppercase());

    writeln!(out, "// --- object `{name}` ---").unwrap();
    writeln!(out, "thread_local! {{").unwrap();
    writeln!(
        out,
        "    static {reg}: RefCell<HashMap<u32, Arc<{rust_ty}>>> = RefCell::new(HashMap::new());"
    )
    .unwrap();
    writeln!(out, "    static {next}: Cell<u32> = Cell::new(0);").unwrap();
    writeln!(out, "}}").unwrap();

    // Helper names use the `__uniffi_` prefix so they can never collide
    // with an exported method shim (e.g. an object method called `get`
    // would otherwise clash with the registry `counter_get` lookup).
    writeln!(
        out,
        "fn __uniffi_{snake}_insert(obj: Arc<{rust_ty}>) -> u32 {{\n    \
         let id = {next}.with(|c| {{ let n = c.get() + 1; c.set(n); n }});\n    \
         {reg}.with(|r| {{ r.borrow_mut().insert(id, obj); }});\n    \
         id\n\
         }}"
    )
    .unwrap();
    writeln!(
        out,
        "fn __uniffi_{snake}_get(handle: u32) -> Result<Arc<{rust_ty}>, JsError> {{\n    \
         {reg}.with(|r| r.borrow().get(&handle).cloned()\n        \
         .ok_or_else(|| JsError::new(&format!(\"invalid handle for `{name}`: {{}}\", handle))))\n\
         }}"
    )
    .unwrap();

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(
        out,
        "pub fn __uniffi_{snake}_object_free(handle: u32) {{\n    \
         {reg}.with(|r| {{ r.borrow_mut().remove(&handle); }});\n\
         }}"
    )
    .unwrap();

    for c in obj.constructors() {
        render_constructor(out, crate_ident, &snake, &rust_ty, c);
    }
    for m in obj.methods() {
        render_method(out, crate_ident, &snake, m);
    }
}

fn render_constructor(
    out: &mut String,
    crate_ident: &str,
    snake: &str,
    rust_ty: &str,
    c: &Constructor,
) {
    let fn_name = format!("{snake}_{}", c.name().to_snake_case());
    let arg_info: Vec<(String, Lowering)> = c
        .arguments()
        .iter()
        .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident)))
        .collect();
    let is_async = c.is_async();
    let throws = c.throws_type().is_some();

    if arg_info
        .iter()
        .any(|(_, l)| matches!(l, Lowering::Unsupported(_)))
    {
        writeln!(out, "#[wasm_bindgen]").unwrap();
        writeln!(
            out,
            "pub fn {fn_name}() -> Result<u32, JsError> {{\n    \
             Err(JsError::new(\"constructor has unsupported argument types\"))\n\
             }}"
        )
        .unwrap();
        return;
    }

    let params = param_list(&arg_info);
    let async_kw = if is_async { "async " } else { "" };
    let call_await = if is_async { ".await" } else { "" };

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(
        out,
        "pub {async_kw}fn {fn_name}({params}) -> Result<u32, JsError> {{"
    )
    .unwrap();
    emit_arg_decoders(out, &arg_info);
    let pass = arg_pass(&arg_info);
    let call = format!("<{rust_ty}>::{}({pass}){call_await}", c.name());
    let obj_expr = if throws {
        format!("{call}.map_err(|e| JsError::new(&format!(\"{{e:?}}\")))?")
    } else {
        call
    };
    writeln!(
        out,
        "    let __obj: Arc<_> = __Coerce({obj_expr}).__into_arc();"
    )
    .unwrap();
    writeln!(
        out,
        "    Ok::<u32, JsError>(__uniffi_{snake}_insert(__obj))"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
}

fn render_method(out: &mut String, crate_ident: &str, snake: &str, m: &Method) {
    let fn_name = format!("{snake}_{}", m.name().to_snake_case());
    let arg_info: Vec<(String, Lowering)> = m
        .arguments()
        .iter()
        .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident)))
        .collect();
    let ret_info = m.return_type().map(|t| classify(t, crate_ident));

    if let Some(reason) = first_unsupported(&arg_info, &ret_info) {
        let params = arg_info
            .iter()
            .map(|(n, _)| format!("_{n}: JsValue"))
            .collect::<Vec<_>>()
            .join(", ");
        let comma = if params.is_empty() { "" } else { ", " };
        writeln!(out, "#[wasm_bindgen]").unwrap();
        writeln!(
            out,
            "pub fn {fn_name}(_handle: u32{comma}{params}) -> Result<JsValue, JsError> {{\n    \
             Err(JsError::new(\"method not yet lowered: {reason}\"))\n\
             }}"
        )
        .unwrap();
        return;
    }

    let is_async = m.is_async();
    let throws = m.throws_type().is_some();
    let async_kw = if is_async { "async " } else { "" };
    let call_await = if is_async { ".await" } else { "" };

    let params = param_list(&arg_info);
    let comma = if params.is_empty() { "" } else { ", " };
    let rust_ret = return_type(&ret_info, throws);

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(
        out,
        "pub {async_kw}fn {fn_name}(handle: u32{comma}{params}) -> {rust_ret} {{"
    )
    .unwrap();
    writeln!(out, "    let __self = __uniffi_{snake}_get(handle)?;").unwrap();
    emit_arg_decoders(out, &arg_info);
    let pass = arg_pass(&arg_info);
    let call = format!("__self.{}({pass}){call_await}", m.name());
    let bound = if throws {
        format!("{call}.map_err(|e| JsError::new(&format!(\"{{e:?}}\")))?")
    } else {
        call
    };
    emit_return(out, &ret_info, &bound);
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------
// Callback wrappers
// ---------------------------------------------------------------------

/// Emit `struct __Js<Name>` implementing the biz-side trait by dispatching
/// through the thread-local `__uniffi_cb_invoke` helper. This lets Rust
/// transparently call back into a foreign JS object.
fn render_callback_wrapper(out: &mut String, crate_ident: &str, name: &str, methods: &[Method]) {
    writeln!(out, "// --- callback wrapper for `{name}` ---").unwrap();
    writeln!(out, "struct __Js{name} {{ handle: u32 }}").unwrap();
    writeln!(out, "impl Drop for __Js{name} {{").unwrap();
    writeln!(
        out,
        "    fn drop(&mut self) {{ __uniffi_cb_release(self.handle); }}"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "impl ::{crate_ident}::{name} for __Js{name} {{").unwrap();
    for m in methods {
        let m_name = m.name();
        let arg_info: Vec<(String, Lowering)> = m
            .arguments()
            .iter()
            .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident)))
            .collect();
        // Build the biz-facing Rust signature. We take the args by value so
        // the `impl Trait for __Js<Name>` matches a simple `fn m(&self, a: T)`.
        let rust_args = arg_info
            .iter()
            .map(|(n, l)| {
                let t = match l {
                    Lowering::Native(t) => t.clone(),
                    Lowering::Value { core_ty, .. } => core_ty.clone(),
                    Lowering::Object { rust_ty, .. } => format!("Arc<{rust_ty}>"),
                    Lowering::Callback { rust_ty, .. } => format!("Arc<{rust_ty}>"),
                    Lowering::Unsupported(_) => "JsValue".to_string(),
                };
                format!("{n}: {t}")
            })
            .collect::<Vec<_>>()
            .join(", ");
        let ret_info = m.return_type().map(|t| classify(t, crate_ident));
        let ret_ty = match &ret_info {
            Some(Lowering::Native(s)) => s.clone(),
            Some(Lowering::Value { core_ty, .. }) => core_ty.clone(),
            _ => "()".to_string(),
        };
        writeln!(
            out,
            "    fn {m_name}(&self{}{rust_args}) -> {ret_ty} {{",
            if rust_args.is_empty() { "" } else { ", " }
        )
        .unwrap();
        // Build a JS args array via explicit lift_expr — no serde.
        writeln!(out, "        let __args_arr = ::js_sys::Array::new();").unwrap();
        for (arg, (n, l)) in m.arguments().iter().zip(arg_info.iter()) {
            match l {
                Lowering::Native(_) | Lowering::Value { .. } => {
                    let ty = arg.as_type();
                    let lift = lift_expr(n, &ty, 0);
                    writeln!(out, "        let __lifted_{n} = {lift};").unwrap();
                    writeln!(out, "        let _ = __args_arr.push(&__lifted_{n});").unwrap();
                }
                _ => {
                    writeln!(out, "        let _ = __args_arr.push(&JsValue::NULL);").unwrap();
                }
            }
        }
        writeln!(out, "        let __args: JsValue = __args_arr.into();").unwrap();
        writeln!(
            out,
            "        let __ret = __uniffi_cb_invoke(self.handle, \"{}\", __args);",
            lower_camel(m_name)
        )
        .unwrap();
        // Lift return via explicit lower_expr — no serde.
        match &ret_info {
            Some(Lowering::Native(_)) | Some(Lowering::Value { .. }) => {
                let ty = m
                    .return_type()
                    .expect("ret_info Some implies return_type")
                    .clone();
                let lower = lower_expr("__ret", &ty, 0);
                writeln!(
                    out,
                    "        ({lower}).unwrap_or_else(|e| panic!(\"uniffi wasm callback bad return: {{e:?}}\"))"
                )
                .unwrap();
            }
            Some(_) | None => {
                writeln!(out, "        let _ = __ret;").unwrap();
            }
        }
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn lower_camel(rust: &str) -> String {
    // tiny local snake→lowerCamel, since heck isn't imported here for it
    // and we only need the same mapping the api_module uses.
    use heck::ToLowerCamelCase;
    rust.to_lower_camel_case()
}

// ---------------------------------------------------------------------
// Value-type methods
// ---------------------------------------------------------------------

fn render_value_method(
    out: &mut String,
    crate_ident: &str,
    owner_name: &str,
    owner_ty: &Type,
    m: &Method,
) {
    let fn_name = format!(
        "{}_{}",
        owner_name.to_snake_case(),
        m.name().to_snake_case()
    );
    let self_info = classify(owner_ty, crate_ident);
    let arg_info: Vec<(String, Lowering)> = std::iter::once(("self_".to_string(), self_info))
        .chain(
            m.arguments()
                .iter()
                .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident))),
        )
        .collect();
    let ret_info = m.return_type().map(|t| classify(t, crate_ident));

    if let Some(reason) = first_unsupported(&arg_info, &ret_info) {
        let arg_params = arg_info
            .iter()
            .map(|(n, _)| format!("_{n}: JsValue"))
            .collect::<Vec<_>>()
            .join(", ");
        let async_kw = if m.is_async() { "async " } else { "" };
        writeln!(out, "#[wasm_bindgen]").unwrap();
        writeln!(
            out,
            "pub {async_kw}fn {fn_name}({arg_params}) -> Result<JsValue, JsError> {{"
        )
        .unwrap();
        writeln!(
            out,
            "    Err(JsError::new(\"uniffi wasm: `{fn_name}` not yet lowered: {reason}\"))"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
        return;
    }

    let is_async = m.is_async();
    let throws = m.throws_type().is_some();
    let async_kw = if is_async { "async " } else { "" };
    let call_await = if is_async { ".await" } else { "" };
    let params = param_list(&arg_info);
    let rust_ret = return_type(&ret_info, throws);

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(out, "pub {async_kw}fn {fn_name}({params}) -> {rust_ret} {{").unwrap();
    emit_arg_decoders(out, &arg_info);
    let pass = m
        .arguments()
        .iter()
        .map(|a| {
            if a.by_ref() || matches!(a.as_type(), Type::Record { .. } | Type::Enum { .. }) {
                format!("&{}", a.name())
            } else {
                a.name().to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("self_.{}({pass}){call_await}", m.name());
    let bound = if throws {
        format!("{call}.map_err(|e| JsError::new(&format!(\"{{e:?}}\")))?")
    } else {
        call
    };
    emit_return(out, &ret_info, &bound);
    writeln!(out, "}}").unwrap();
}

fn render_value_constructor(
    out: &mut String,
    crate_ident: &str,
    owner_name: &str,
    owner_ty: &Type,
    c: &Constructor,
) {
    let fn_name = format!(
        "{}_{}",
        owner_name.to_snake_case(),
        c.name().to_snake_case()
    );
    let arg_info: Vec<(String, Lowering)> = c
        .arguments()
        .iter()
        .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident)))
        .collect();
    let ret_info = Some(classify(owner_ty, crate_ident));

    if let Some(reason) = first_unsupported(&arg_info, &ret_info) {
        let arg_params = arg_info
            .iter()
            .map(|(n, _)| format!("_{n}: JsValue"))
            .collect::<Vec<_>>()
            .join(", ");
        let async_kw = if c.is_async() { "async " } else { "" };
        writeln!(out, "#[wasm_bindgen]").unwrap();
        writeln!(
            out,
            "pub {async_kw}fn {fn_name}({arg_params}) -> Result<JsValue, JsError> {{"
        )
        .unwrap();
        writeln!(
            out,
            "    Err(JsError::new(\"uniffi wasm: `{fn_name}` not yet lowered: {reason}\"))"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
        return;
    }

    let is_async = c.is_async();
    let throws = c.throws_type().is_some();
    let async_kw = if is_async { "async " } else { "" };
    let call_await = if is_async { ".await" } else { "" };
    let params = param_list(&arg_info);
    let rust_ret = return_type(&ret_info, throws);
    let core_ty = core_ty_for(owner_ty, crate_ident);

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(out, "pub {async_kw}fn {fn_name}({params}) -> {rust_ret} {{").unwrap();
    emit_arg_decoders(out, &arg_info);
    let pass = c
        .arguments()
        .iter()
        .map(|a| {
            if a.by_ref() || matches!(a.as_type(), Type::Record { .. } | Type::Enum { .. }) {
                format!("&{}", a.name())
            } else {
                a.name().to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("{core_ty}::{}({pass}){call_await}", c.name());
    let bound = if throws {
        format!("{call}.map_err(|e| JsError::new(&format!(\"{{e:?}}\")))?")
    } else {
        call
    };
    emit_return(out, &ret_info, &bound);
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------
// Free functions
// ---------------------------------------------------------------------

fn render_function(out: &mut String, crate_ident: &str, f: &Function) {
    let name = f.name();
    let arg_info: Vec<(String, Lowering)> = f
        .arguments()
        .iter()
        .map(|a| (a.name().to_string(), classify(&a.as_type(), crate_ident)))
        .collect();
    let ret_info = f.return_type().map(|t| classify(t, crate_ident));

    if let Some(reason) = first_unsupported(&arg_info, &ret_info) {
        let arg_params = arg_info
            .iter()
            .map(|(n, _)| format!("_{n}: JsValue"))
            .collect::<Vec<_>>()
            .join(", ");
        let async_kw = if f.is_async() { "async " } else { "" };
        writeln!(out, "#[wasm_bindgen]").unwrap();
        writeln!(
            out,
            "pub {async_kw}fn {name}({arg_params}) -> Result<JsValue, JsError> {{"
        )
        .unwrap();
        writeln!(
            out,
            "    Err(JsError::new(\"uniffi wasm: `{name}` not yet lowered: {reason}\"))"
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
        return;
    }

    let is_async = f.is_async();
    let throws = f.throws_type().is_some();
    let async_kw = if is_async { "async " } else { "" };
    let call_await = if is_async { ".await" } else { "" };

    let params = param_list(&arg_info);
    let rust_ret = return_type(&ret_info, throws);

    writeln!(out, "#[wasm_bindgen]").unwrap();
    writeln!(out, "pub {async_kw}fn {name}({params}) -> {rust_ret} {{").unwrap();
    emit_arg_decoders(out, &arg_info);
    let pass = arg_pass(&arg_info);
    let call = format!("::{crate_ident}::{name}({pass}){call_await}");
    let bound = if throws {
        format!("{call}.map_err(|e| JsError::new(&format!(\"{{e:?}}\")))?")
    } else {
        call
    };
    emit_return(out, &ret_info, &bound);
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------
// Shared emit helpers
// ---------------------------------------------------------------------

fn param_list(arg_info: &[(String, Lowering)]) -> String {
    arg_info
        .iter()
        .map(|(n, l)| match l {
            Lowering::Native(t) => format!("{n}: {t}"),
            Lowering::Value { .. } => format!("{n}: JsValue"),
            Lowering::Object { .. } => format!("{n}: u32"),
            Lowering::Callback { .. } => format!("{n}: u32"),
            Lowering::Unsupported(_) => unreachable!(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit the per-arg decode statements that turn the wasm-bindgen level
/// parameter (`JsValue` / `u32` / native) into the biz-call level value
/// (local variable shadowing the parameter by the same name).
fn emit_arg_decoders(out: &mut String, arg_info: &[(String, Lowering)]) {
    for (n, l) in arg_info {
        match l {
            Lowering::Native(_) => {}
            Lowering::Value { core_ty, ty } => {
                let lower = lower_expr(n, ty, 0);
                writeln!(out, "    let {n}: {core_ty} = ({lower})?;").unwrap();
            }
            Lowering::Object { snake, .. } => {
                writeln!(out, "    let {n} = __uniffi_{snake}_get({n})?;").unwrap();
            }
            Lowering::Callback { rust_ty, .. } => {
                writeln!(
                    out,
                    "    let {n}: Arc<{rust_ty}> = Arc::new(__Js{ty_name} {{ handle: {n} }});",
                    ty_name = rust_ty
                        .trim_start_matches("dyn ")
                        .rsplit("::")
                        .next()
                        .unwrap()
                )
                .unwrap();
            }
            Lowering::Unsupported(_) => unreachable!(),
        }
    }
}

fn arg_pass(arg_info: &[(String, Lowering)]) -> String {
    arg_info
        .iter()
        .map(|(n, _)| n.clone())
        .collect::<Vec<_>>()
        .join(", ")
}

fn first_unsupported(
    arg_info: &[(String, Lowering)],
    ret_info: &Option<Lowering>,
) -> Option<String> {
    for (_, l) in arg_info {
        if let Lowering::Unsupported(r) = l {
            return Some(r.clone());
        }
    }
    if let Some(Lowering::Unsupported(r)) = ret_info {
        return Some(r.clone());
    }
    None
}

fn return_type(ret_info: &Option<Lowering>, throws: bool) -> String {
    // Every path in this file is now `Result<_, JsError>`-friendly because
    // arg decoding can fail even when the biz call is infallible.
    match ret_info {
        None => "Result<(), JsError>".to_string(),
        Some(Lowering::Native(t)) => format!("Result<{t}, JsError>"),
        Some(Lowering::Value { .. }) => "Result<JsValue, JsError>".to_string(),
        Some(Lowering::Object { .. }) => "Result<u32, JsError>".to_string(),
        Some(Lowering::Callback { .. }) => "Result<u32, JsError>".to_string(),
        Some(Lowering::Unsupported(_)) => unreachable!(),
    }
    .tap(|_| {
        let _ = throws;
    })
}

// Tiny inline extension trait so `return_type` can drop the unused
// `throws` parameter without rearranging call sites.
trait Tap: Sized {
    fn tap(self, f: impl FnOnce(&Self)) -> Self {
        f(&self);
        self
    }
}
impl<T> Tap for T {}

fn emit_return(out: &mut String, ret_info: &Option<Lowering>, bound: &str) {
    match ret_info {
        None => {
            writeln!(out, "    {bound};").unwrap();
            writeln!(out, "    Ok::<(), JsError>(())").unwrap();
        }
        Some(Lowering::Native(_)) => {
            writeln!(out, "    Ok::<_, JsError>({bound})").unwrap();
        }
        Some(Lowering::Value { ty, .. }) => {
            writeln!(out, "    let __ret_core = {bound};").unwrap();
            let lift = lift_expr_result("__ret_core", ty, 0);
            writeln!(out, "    let __ret_js = {lift}?;").unwrap();
            writeln!(out, "    Ok::<JsValue, JsError>(__ret_js)").unwrap();
        }
        Some(Lowering::Object { snake, .. }) => {
            writeln!(
                out,
                "    let __obj: Arc<_> = __Coerce({bound}).__into_arc();"
            )
            .unwrap();
            writeln!(
                out,
                "    Ok::<u32, JsError>(__uniffi_{snake}_insert(__obj))"
            )
            .unwrap();
        }
        Some(Lowering::Callback { .. }) => {
            writeln!(
                out,
                "    Err(JsError::new(\"returning callback traits from wasm is not supported\"))"
            )
            .unwrap();
        }
        Some(Lowering::Unsupported(_)) => unreachable!(),
    }
}

// ---------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------

/// How a uniffi `Type` crosses the wasm-bindgen boundary.
enum Lowering {
    /// wasm-bindgen native: scalar / bool / String / Vec<u8>. No conversion.
    Native(String),
    /// Non-scalar carried as `JsValue`, lowered/lifted via explicit
    /// generator-emitted helpers. No serde anywhere on this path.
    Value {
        /// Concrete downstream core rust type, e.g.
        /// `::crate_ident::Foo`, `Option<::crate_ident::Foo>`, …
        core_ty: String,
        /// The original uniffi `Type`, so `lower_expr` / `lift_expr`
        /// can recurse through `Option` / `Vec` / nested records.
        ty: Type,
    },
    /// Opaque object handle: u32 on the boundary, looked up via
    /// `{snake}_get` / `{snake}_insert`.
    Object { snake: String, rust_ty: String },
    /// Foreign trait callback: u32 on the boundary, wrapped in
    /// `Arc::new(__Js{Name}{handle})` on the Rust side.
    Callback {
        #[allow(dead_code)]
        snake: String,
        rust_ty: String,
    },
    /// Type we know we haven't wired up yet. The reason is embedded in
    /// the generated code so the skip is diagnosable at runtime.
    Unsupported(String),
}

fn classify(ty: &Type, crate_ident: &str) -> Lowering {
    use Lowering::*;
    match ty {
        Type::UInt8 => Native("u8".into()),
        Type::Int8 => Native("i8".into()),
        Type::UInt16 => Native("u16".into()),
        Type::Int16 => Native("i16".into()),
        Type::UInt32 => Native("u32".into()),
        Type::Int32 => Native("i32".into()),
        Type::UInt64 => Native("u64".into()),
        Type::Int64 => Native("i64".into()),
        Type::Float32 => Native("f32".into()),
        Type::Float64 => Native("f64".into()),
        Type::Boolean => Native("bool".into()),
        Type::String => Native("String".into()),
        Type::Bytes => Native("Vec<u8>".into()),
        Type::Record { .. } | Type::Enum { .. } => Value {
            core_ty: core_ty_for(ty, crate_ident),
            ty: ty.clone(),
        },
        Type::Optional { inner_type } => match classify(inner_type, crate_ident) {
            Native(t) => Native(format!("Option<{t}>")),
            Value { .. } => Value {
                core_ty: core_ty_for(ty, crate_ident),
                ty: ty.clone(),
            },
            Unsupported(r) => Unsupported(format!("Option<…>: {r}")),
            other => Unsupported(format!(
                "Option<{}>: nested object/callback not supported",
                type_debug(&other)
            )),
        },
        Type::Sequence { inner_type } => match classify(inner_type, crate_ident) {
            Native(t) => Native(format!("Vec<{t}>")),
            Value { .. } => Value {
                core_ty: core_ty_for(ty, crate_ident),
                ty: ty.clone(),
            },
            Unsupported(r) => Unsupported(format!("Vec<…>: {r}")),
            other => Unsupported(format!(
                "Vec<{}>: nested object/callback not supported",
                type_debug(&other)
            )),
        },
        Type::Object { name, imp, .. } => {
            let snake = name.to_snake_case();
            let rust_ty = rust_ty_for_type(crate_ident, ty);
            match imp {
                ObjectImpl::CallbackTrait => Callback { snake, rust_ty },
                _ => Object { snake, rust_ty },
            }
        }
        Type::CallbackInterface { name, .. } => {
            let snake = name.to_snake_case();
            let rust_ty = format!("dyn ::{crate_ident}::{name}");
            Callback { snake, rust_ty }
        }
        Type::Timestamp => Value {
            core_ty: "::std::time::SystemTime".into(),
            ty: ty.clone(),
        },
        Type::Duration => Value {
            core_ty: "::std::time::Duration".into(),
            ty: ty.clone(),
        },
        Type::Custom { name, builtin, .. } => match classify(builtin, crate_ident) {
            Native(_) | Value { .. } => Value {
                core_ty: format!("::{crate_ident}::{name}"),
                ty: ty.clone(),
            },
            Unsupported(r) => Unsupported(format!("Custom<{r}>")),
            other => Unsupported(format!(
                "Custom<{}>: nested object/callback not supported",
                type_debug(&other)
            )),
        },
        Type::Map {
            key_type,
            value_type,
        } => {
            if !matches!(key_type.as_ref(), Type::String) {
                Unsupported("Map keys other than string are not supported in this pass".into())
            } else {
                match classify(value_type, crate_ident) {
                    Native(_) | Value { .. } => Value {
                        core_ty: core_ty_for(ty, crate_ident),
                        ty: ty.clone(),
                    },
                    Unsupported(r) => Unsupported(format!("Map value: {r}")),
                    value => Unsupported(format!(
                        "Map<string, {}>: nested object/callback not supported",
                        type_debug(&value)
                    )),
                }
            }
        }
    }
}

// ---------------------------------------------------------------------
// Explicit record/enum lowering & lifting (no serde)
// ---------------------------------------------------------------------

/// Emit a `__lower_<snake>` and `__lift_<snake>` helper for each record
/// and non-error enum. These translate between `JsValue` and downstream
/// core types via `js_sys::Reflect` / `js_sys::Array` only. Error enums
/// are skipped because they only ever cross as exceptions via
/// `JsError::new(&format!("{e:?}"))`.
fn emit_value_helpers(out: &mut String, ci: &ComponentInterface, crate_ident: &str) {
    let records = ci.record_definitions();
    let enums = ci.enum_definitions();
    if records.is_empty() && enums.is_empty() {
        return;
    }
    writeln!(
        out,
        "// --- explicit record/enum lowering & lifting (no serde) ---"
    )
    .unwrap();
    for r in records {
        emit_record_helpers(out, r, crate_ident);
    }
    for e in enums {
        if ci.is_name_used_as_error(e.name()) {
            continue;
        }
        emit_enum_helpers(out, e, crate_ident);
    }
    writeln!(out).unwrap();
}

fn emit_record_helpers(out: &mut String, r: &Record, crate_ident: &str) {
    let name = r.name();
    let snake = name.to_snake_case();
    let core = format!("::{crate_ident}::{name}");

    writeln!(
        out,
        "#[allow(non_snake_case, dead_code)]\n\
         fn __lower_{snake}(__js: JsValue) -> Result<{core}, JsError> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let __obj: ::js_sys::Object = __js.dyn_into().map_err(|_| JsError::new(\"expected object for `{name}`\"))?;"
    )
    .unwrap();
    for f in r.fields() {
        let key = lower_camel(f.name());
        let field_ident = format!("__f_{}", f.name());
        writeln!(
            out,
            "    let {field_ident}: JsValue = ::js_sys::Reflect::get(&__obj, &JsValue::from_str(\"{key}\")).map_err(|_| JsError::new(\"reflect get `{key}` on `{name}` failed\"))?;"
        )
        .unwrap();
        let lower = lower_expr(&field_ident, &f.as_type(), 0);
        writeln!(
            out,
            "    let {ident}: {ty} = ({lower})?;",
            ident = f.name(),
            ty = core_ty_for(&f.as_type(), crate_ident),
        )
        .unwrap();
    }
    writeln!(out, "    Ok::<{core}, JsError>({core} {{").unwrap();
    for f in r.fields() {
        writeln!(out, "        {n},", n = f.name()).unwrap();
    }
    writeln!(out, "    }})\n}}").unwrap();

    writeln!(
        out,
        "#[allow(non_snake_case, dead_code)]\n\
         fn __lift_{snake}(__c: {core}) -> Result<JsValue, JsError> {{"
    )
    .unwrap();
    writeln!(out, "    let __obj = ::js_sys::Object::new();").unwrap();
    let binds: Vec<String> = r.fields().iter().map(|f| f.name().to_string()).collect();
    writeln!(
        out,
        "    let {core} {{ {fields} }} = __c;",
        fields = binds.join(", ")
    )
    .unwrap();
    for f in r.fields() {
        let key = lower_camel(f.name());
        let lift = lift_expr_result(f.name(), &f.as_type(), 0);
        writeln!(
            out,
            "    let _ = ::js_sys::Reflect::set(&__obj, &JsValue::from_str(\"{key}\"), &({lift})?);"
        )
        .unwrap();
    }
    writeln!(out, "    Ok::<JsValue, JsError>(__obj.into())\n}}").unwrap();
}

fn emit_enum_helpers(out: &mut String, e: &Enum, crate_ident: &str) {
    let name = e.name();
    let snake = name.to_snake_case();
    let core = format!("::{crate_ident}::{name}");
    let all_unit = e.variants().iter().all(|v| v.fields().is_empty());

    writeln!(
        out,
        "#[allow(non_snake_case, dead_code, unused_variables)]\n\
         fn __lower_{snake}(__js: JsValue) -> Result<{core}, JsError> {{"
    )
    .unwrap();
    if all_unit {
        writeln!(
            out,
            "    let __tag = __js.as_string().ok_or_else(|| JsError::new(\"expected string for enum `{name}`\"))?;"
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "    let __obj: ::js_sys::Object = __js.dyn_into().map_err(|_| JsError::new(\"expected object for enum `{name}`\"))?;"
        )
        .unwrap();
        writeln!(
            out,
            "    let __tag_js: JsValue = ::js_sys::Reflect::get(&__obj, &JsValue::from_str(\"tag\")).map_err(|_| JsError::new(\"reflect get `tag` on `{name}` failed\"))?;"
        )
        .unwrap();
        writeln!(
            out,
            "    let __tag = __tag_js.as_string().ok_or_else(|| JsError::new(\"enum `{name}`: tag not a string\"))?;"
        )
        .unwrap();
    }
    writeln!(out, "    match __tag.as_str() {{").unwrap();
    for v in e.variants() {
        let vname = v.name();
        if v.fields().is_empty() {
            writeln!(
                out,
                "        \"{vname}\" => Ok::<{core}, JsError>({core}::{vname}),"
            )
            .unwrap();
            continue;
        }
        writeln!(out, "        \"{vname}\" => {{").unwrap();
        let nameless = v.has_nameless_fields();
        let binds: Vec<String> = v
            .fields()
            .iter()
            .enumerate()
            .map(|(i, f)| {
                if f.name().is_empty() {
                    format!("v{i}")
                } else {
                    f.name().to_string()
                }
            })
            .collect();
        for (bind, f) in binds.iter().zip(v.fields().iter()) {
            let key = lower_camel(bind);
            let field_ident = format!("__vf_{bind}");
            writeln!(
                out,
                "            let {field_ident}: JsValue = ::js_sys::Reflect::get(&__obj, &JsValue::from_str(\"{key}\")).map_err(|_| JsError::new(\"reflect get `{key}` on `{name}::{vname}` failed\"))?;"
            )
            .unwrap();
            let lower = lower_expr(&field_ident, &f.as_type(), 0);
            writeln!(
                out,
                "            let {bind}: {ty} = ({lower})?;",
                ty = core_ty_for(&f.as_type(), crate_ident),
            )
            .unwrap();
        }
        if nameless {
            writeln!(
                out,
                "            Ok::<{core}, JsError>({core}::{vname}({args}))",
                args = binds.join(", ")
            )
            .unwrap();
        } else {
            writeln!(out, "            Ok::<{core}, JsError>({core}::{vname} {{").unwrap();
            for (bind, f) in binds.iter().zip(v.fields().iter()) {
                writeln!(out, "                {fname}: {bind},", fname = f.name()).unwrap();
            }
            writeln!(out, "            }})").unwrap();
        }
        writeln!(out, "        }},").unwrap();
    }
    writeln!(
        out,
        "        __other => Err(JsError::new(&format!(\"enum `{name}`: unknown tag {{}}\", __other))),"
    )
    .unwrap();
    writeln!(out, "    }}\n}}").unwrap();

    writeln!(
        out,
        "#[allow(non_snake_case, dead_code, unused_variables)]\n\
         fn __lift_{snake}(__c: {core}) -> Result<JsValue, JsError> {{"
    )
    .unwrap();
    writeln!(out, "    match __c {{").unwrap();
    for v in e.variants() {
        let vname = v.name();
        if v.fields().is_empty() {
            if all_unit {
                writeln!(
                    out,
                    "        {core}::{vname} => Ok::<JsValue, JsError>(JsValue::from_str(\"{vname}\")),"
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        {core}::{vname} => {{\n            \
                     let __obj = ::js_sys::Object::new();\n            \
                     let _ = ::js_sys::Reflect::set(&__obj, &JsValue::from_str(\"tag\"), &JsValue::from_str(\"{vname}\"));\n            \
                    Ok::<JsValue, JsError>(__obj.into())\n        \
                     }},"
                )
                .unwrap();
            }
            continue;
        }
        let nameless = v.has_nameless_fields();
        let binds: Vec<String> = v
            .fields()
            .iter()
            .enumerate()
            .map(|(i, f)| {
                if f.name().is_empty() {
                    format!("v{i}")
                } else {
                    f.name().to_string()
                }
            })
            .collect();
        if nameless {
            writeln!(
                out,
                "        {core}::{vname}({args}) => {{",
                args = binds.join(", ")
            )
            .unwrap();
        } else {
            // Bind names always equal UDL field names here, so we can
            // emit the shorthand `{ x, y }` pattern and avoid the
            // `non_shorthand_field_patterns` warning.
            writeln!(
                out,
                "        {core}::{vname} {{ {fields} }} => {{",
                fields = binds.join(", ")
            )
            .unwrap();
        }
        writeln!(out, "            let __obj = ::js_sys::Object::new();").unwrap();
        writeln!(
            out,
            "            let _ = ::js_sys::Reflect::set(&__obj, &JsValue::from_str(\"tag\"), &JsValue::from_str(\"{vname}\"));"
        )
        .unwrap();
        for (bind, f) in binds.iter().zip(v.fields().iter()) {
            let key = lower_camel(bind);
            let lift = lift_expr_result(bind, &f.as_type(), 0);
            writeln!(
                out,
                "            let _ = ::js_sys::Reflect::set(&__obj, &JsValue::from_str(\"{key}\"), &({lift})?);"
            )
            .unwrap();
        }
        writeln!(
            out,
            "            Ok::<JsValue, JsError>(__obj.into())\n        }},"
        )
        .unwrap();
    }
    writeln!(out, "    }}\n}}").unwrap();
}

/// Build a Rust expression `Result<CoreTy, JsError>` that lowers the
/// JS value held in `expr` into the downstream core type for `ty`.
fn lower_expr(expr: &str, ty: &Type, depth: usize) -> String {
    match ty {
        Type::String => format!(
            "{expr}.as_string().ok_or_else(|| JsError::new(\"expected string\"))"
        ),
        Type::Boolean => format!(
            "{expr}.as_bool().ok_or_else(|| JsError::new(\"expected boolean\"))"
        ),
        Type::UInt8 => num_lower(expr, "u8"),
        Type::Int8 => num_lower(expr, "i8"),
        Type::UInt16 => num_lower(expr, "u16"),
        Type::Int16 => num_lower(expr, "i16"),
        Type::UInt32 => num_lower(expr, "u32"),
        Type::Int32 => num_lower(expr, "i32"),
        Type::UInt64 => num_lower(expr, "u64"),
        Type::Int64 => num_lower(expr, "i64"),
        Type::Float32 => num_lower(expr, "f32"),
        Type::Float64 => format!(
            "{expr}.as_f64().ok_or_else(|| JsError::new(\"expected number\"))"
        ),
        Type::Bytes => format!(
            "{expr}.dyn_into::<::js_sys::Uint8Array>().map(|__u| __u.to_vec()).map_err(|_| JsError::new(\"expected Uint8Array\"))"
        ),
        Type::Timestamp => timestamp_lower(expr),
        Type::Duration => duration_lower(expr),
        Type::Record { name, .. } | Type::Enum { name, .. } => {
            let s = name.to_snake_case();
            format!("__lower_{s}({expr})")
        }
        Type::Optional { inner_type } => {
            let bind = format!("__inner{depth}");
            let inner = lower_expr(&bind, inner_type, depth + 1);
            format!(
                "{{ let {bind}: JsValue = {expr}; if {bind}.is_null() || {bind}.is_undefined() {{ Ok::<_, JsError>(None) }} else {{ ({inner}).map(Some) }} }}"
            )
        }
        Type::Sequence { inner_type } => {
            let bind = format!("__item{depth}");
            let inner = lower_expr(&bind, inner_type, depth + 1);
            format!(
                "{{ let __arr{depth}: ::js_sys::Array = {expr}.dyn_into().map_err(|_| JsError::new(\"expected array\"))?; let mut __out{depth} = ::std::vec::Vec::with_capacity(__arr{depth}.length() as usize); for __i{depth} in 0..__arr{depth}.length() {{ let {bind}: JsValue = __arr{depth}.get(__i{depth}); __out{depth}.push(({inner})?); }} Ok::<_, JsError>(__out{depth}) }}"
            )
        }
        Type::Map {
            key_type,
            value_type,
        } => {
            let key = format!("__key{depth}");
            let value = format!("__value{depth}");
            let key_lower = lower_expr(&key, key_type, depth + 1);
            let value_lower = lower_expr(&value, value_type, depth + 1);
            format!(
                "{{ let __obj{depth}: ::js_sys::Object = {expr}.dyn_into().map_err(|_| JsError::new(\"expected object for map\"))?; let __keys{depth} = ::js_sys::Object::keys(&__obj{depth}); let mut __out{depth} = ::std::collections::HashMap::new(); for __i{depth} in 0..__keys{depth}.length() {{ let {key}: JsValue = __keys{depth}.get(__i{depth}); let {value}: JsValue = ::js_sys::Reflect::get(&__obj{depth}, &{key}).map_err(|_| JsError::new(\"reflect get map value failed\"))?; __out{depth}.insert(({key_lower})?, ({value_lower})?); }} Ok::<_, JsError>(__out{depth}) }}"
            )
        }
        Type::Custom {
            module_path,
            name,
            builtin,
        } => {
            let builtin_lower = lower_expr(expr, builtin, depth + 1);
            let crate_ident = module_path
                .split("::")
                .next()
                .expect("custom type module path should have a crate root");
            let builtin_ty = core_ty_for(builtin, crate_ident);
            let tag_ty = core_tag_path(module_path);
            let custom_ty = format!("::{crate_ident}::{name}");
            format!(
                "Ok::<{custom_ty}, JsError>({{ let __builtin = ({builtin_lower})?; let __ffi = <{builtin_ty} as ::uniffi::Lower<{tag_ty}>>::lower(__builtin); <{custom_ty} as ::uniffi::Lift<{tag_ty}>>::try_lift(__ffi).expect(\"uniffi wasm custom type lift failed\") }})"
            )
        }
        _ => "Err::<_, JsError>(JsError::new(\"unsupported wasm value type in lower\"))".to_string(),
    }
}

fn num_lower(expr: &str, rust_ty: &str) -> String {
    format!(
        "{expr}.as_f64().ok_or_else(|| JsError::new(\"expected number\")).map(|__n| __n as {rust_ty})"
    )
}

fn timestamp_lower(expr: &str) -> String {
    format!("__uniffi_lower_timestamp({expr})")
}

fn duration_lower(expr: &str) -> String {
    format!("__uniffi_lower_duration({expr})")
}

/// Build a Rust expression of type `JsValue` that lifts the core value
/// held in `expr` into a JS value. Infallible.
fn lift_expr(expr: &str, ty: &Type, depth: usize) -> String {
    match ty {
        Type::String => format!("JsValue::from_str(&{expr})"),
        Type::Boolean => format!("JsValue::from_bool({expr})"),
        Type::UInt8
        | Type::Int8
        | Type::UInt16
        | Type::Int16
        | Type::UInt32
        | Type::Int32
        | Type::UInt64
        | Type::Int64
        | Type::Float32
        | Type::Float64 => format!("JsValue::from_f64({expr} as f64)"),
        Type::Bytes => format!("JsValue::from(::js_sys::Uint8Array::from(&{expr}[..]))"),
        Type::Timestamp => timestamp_lift_value(expr),
        Type::Duration => duration_lift_value(expr),
        Type::Record { name, .. } | Type::Enum { name, .. } => {
            let s = name.to_snake_case();
            format!("__lift_{s}({expr})")
        }
        Type::Optional { inner_type } => {
            let bind = format!("__inner{depth}");
            let inner = lift_expr(&bind, inner_type, depth + 1);
            format!("match {expr} {{ Some({bind}) => {inner}, None => JsValue::NULL }}")
        }
        Type::Sequence { inner_type } => {
            let bind = format!("__item{depth}");
            let inner = lift_expr(&bind, inner_type, depth + 1);
            format!(
                "{{ let __arr{depth} = ::js_sys::Array::new(); for {bind} in {expr} {{ let _ = __arr{depth}.push(&{inner}); }} JsValue::from(__arr{depth}) }}"
            )
        }
        Type::Map {
            key_type,
            value_type,
        } => {
            let key = format!("__key{depth}");
            let value = format!("__value{depth}");
            let key_lift = lift_expr(&key, key_type, depth + 1);
            let value_lift = lift_expr(&value, value_type, depth + 1);
            format!(
                "{{ let __obj{depth} = ::js_sys::Object::new(); for ({key}, {value}) in {expr} {{ let _ = ::js_sys::Reflect::set(&__obj{depth}, &{key_lift}, &{value_lift}); }} JsValue::from(__obj{depth}) }}"
            )
        }
        Type::Custom {
            module_path,
            name,
            builtin,
        } => {
            let tag_ty = core_tag_path(module_path);
            let crate_ident = module_path
                .split("::")
                .next()
                .expect("custom type module path should have a crate root");
            let custom_ty = format!("::{crate_ident}::{name}");
            let builtin_ty = core_ty_for(builtin, crate_ident);
            let lifted = format!(
                "{{ let __builtin = <{builtin_ty} as ::uniffi::Lift<{tag_ty}>>::try_lift(<{custom_ty} as ::uniffi::Lower<{tag_ty}>>::lower({expr})).expect(\"uniffi wasm custom type lift failed\"); {} }}",
                lift_expr("__builtin", builtin, depth + 1)
            );
            lifted
        }
        _ => "JsValue::NULL".to_string(),
    }
}

/// Build a Rust expression of type `Result<JsValue, JsError>` that lifts
/// the core value held in `expr` into a JS value. This is used at public
/// return boundaries and for generated record/enum helpers where a
/// `Date` overflow should surface as a thrown `JsError`.
fn lift_expr_result(expr: &str, ty: &Type, depth: usize) -> String {
    match ty {
        Type::Timestamp => timestamp_lift_result(expr),
        Type::Duration => duration_lift_result(expr),
        Type::Record { name, .. } | Type::Enum { name, .. } => {
            let s = name.to_snake_case();
            format!("__lift_{s}({expr})")
        }
        Type::Optional { inner_type } => {
            let bind = format!("__inner{depth}");
            let inner = lift_expr_result(&bind, inner_type, depth + 1);
            format!(
                "match {expr} {{ Some({bind}) => {inner}, None => Ok::<JsValue, JsError>(JsValue::NULL) }}"
            )
        }
        Type::Sequence { inner_type } => {
            let bind = format!("__item{depth}");
            let inner = lift_expr_result(&bind, inner_type, depth + 1);
            format!(
                "{{ let __arr{depth} = ::js_sys::Array::new(); for {bind} in {expr} {{ let _ = __arr{depth}.push(&({inner})?); }} Ok::<JsValue, JsError>(JsValue::from(__arr{depth})) }}"
            )
        }
        Type::Map {
            key_type,
            value_type,
        } => {
            let key = format!("__key{depth}");
            let value = format!("__value{depth}");
            let key_lift = lift_expr_result(&key, key_type, depth + 1);
            let value_lift = lift_expr_result(&value, value_type, depth + 1);
            format!(
                "{{ let __obj{depth} = ::js_sys::Object::new(); for ({key}, {value}) in {expr} {{ let _ = ::js_sys::Reflect::set(&__obj{depth}, &({key_lift})?, &({value_lift})?); }} Ok::<JsValue, JsError>(JsValue::from(__obj{depth})) }}"
            )
        }
        Type::Custom {
            module_path,
            name,
            builtin,
        } => {
            let crate_ident = module_path
                .split("::")
                .next()
                .expect("custom type module path should have a crate root");
            let builtin_ty = core_ty_for(builtin, crate_ident);
            let tag_ty = core_tag_path(module_path);
            let custom_ty = format!("::{crate_ident}::{name}");
            let lowered = format!(
                "{{ let __builtin = <{builtin_ty} as ::uniffi::Lift<{tag_ty}>>::try_lift(<{custom_ty} as ::uniffi::Lower<{tag_ty}>>::lower({expr})).expect(\"uniffi wasm custom type lift failed\"); {} }}",
                lift_expr_result("__builtin", builtin, depth + 1)
            );
            lowered
        }
        _ => format!("Ok::<JsValue, JsError>({})", lift_expr(expr, ty, depth)),
    }
}

fn timestamp_lift_value(expr: &str) -> String {
    format!(
        "match __uniffi_lift_timestamp({expr}) {{ Ok(__v) => __v, Err(__e) => panic!(\"uniffi wasm timestamp lift failed: {{:?}}\", __e) }}"
    )
}

fn duration_lift_value(expr: &str) -> String {
    format!(
        "match __uniffi_lift_duration({expr}) {{ Ok(__v) => __v, Err(__e) => panic!(\"uniffi wasm duration lift failed: {{:?}}\", __e) }}"
    )
}

fn timestamp_lift_result(expr: &str) -> String {
    format!("__uniffi_lift_timestamp({expr})")
}

fn duration_lift_result(expr: &str) -> String {
    format!("__uniffi_lift_duration({expr})")
}

fn core_tag_path(module_path: &str) -> String {
    let crate_ident = module_path
        .split("::")
        .next()
        .expect("custom type module path should have a crate root");
    format!("::{crate_ident}::UniFfiTag")
}

/// Downstream core Rust type for a `Type`.
///
/// Primitives/strings/etc. are included so `Option<Record>` /
/// `Vec<Record>` can be expressed end-to-end alongside record/enum
/// explicit lowering.
fn core_ty_for(ty: &Type, crate_ident: &str) -> String {
    match ty {
        Type::UInt8 => "u8".into(),
        Type::Int8 => "i8".into(),
        Type::UInt16 => "u16".into(),
        Type::Int16 => "i16".into(),
        Type::UInt32 => "u32".into(),
        Type::Int32 => "i32".into(),
        Type::UInt64 => "u64".into(),
        Type::Int64 => "i64".into(),
        Type::Float32 => "f32".into(),
        Type::Float64 => "f64".into(),
        Type::Boolean => "bool".into(),
        Type::String => "String".into(),
        Type::Bytes => "Vec<u8>".into(),
        Type::Timestamp => "::std::time::SystemTime".into(),
        Type::Duration => "::std::time::Duration".into(),
        Type::Record { name, .. } | Type::Enum { name, .. } => format!("::{crate_ident}::{name}"),
        Type::Optional { inner_type } => {
            format!("Option<{}>", core_ty_for(inner_type, crate_ident))
        }
        Type::Sequence { inner_type } => {
            format!("Vec<{}>", core_ty_for(inner_type, crate_ident))
        }
        Type::Map {
            key_type,
            value_type,
        } => format!(
            "::std::collections::HashMap<{}, {}>",
            core_ty_for(key_type, crate_ident),
            core_ty_for(value_type, crate_ident)
        ),
        Type::Custom { name, .. } => format!("::{crate_ident}::{name}"),
        _ => "::wasm_bindgen::JsValue".into(),
    }
}

fn type_debug(l: &Lowering) -> &'static str {
    match l {
        Lowering::Native(_) => "native",
        Lowering::Value { .. } => "value",
        Lowering::Object { .. } => "object",
        Lowering::Callback { .. } => "callback",
        Lowering::Unsupported(_) => "unsupported",
    }
}
