/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! Wasm flavor backend — Path A (wasm-bindgen JS glue).
//!
//! The public wasm path is committed to wasm-bindgen: the generated
//! `<crate_name>.rs` shim uses `#[wasm_bindgen]`, and `backend-wasm.ts`
//! consumes the **JS glue module** produced by wasm-bindgen (for example by
//! the in-process `wasm-bindgen-cli-support` API used by the test suite). It does
//! **not** load raw `.wasm` bytes — raw exports can't carry async,
//! bigint lowering or JsError, which wasm-bindgen handles for us.
//!
//! Emits three files per component:
//!
//! - `<crate_name>.rs` — wasm-bindgen Rust shim (see `codegen.rs`).
//! - `backend-wasm.ts` — Path A adapter. Exposes
//!   `adaptWasmBindgenGlue(glue)` which wraps a wasm-bindgen module
//!   object so the shared runtime's `__call` / `__callAsync` can
//!   dispatch against it by Rust snake_case name.
//! - `index.ts` — stable consumer entry. Exports async `initBackend`
//!   that takes the wasm-bindgen glue module and installs the backend
//!   before any API call.
//!
//! Currently covered: scalar free functions (sync / fallible / async),
//! records, enums (incl. payload variants), errors-with-data, opaque
//! objects (`Self` and `Arc<Self>` constructors, methods, free-function
//! `Type::Object` args/returns, trait objects like `Arc<dyn Greeter>`),
//! timestamp / duration, sync and async callback-trait lowering
//! including fallible async methods, and callback methods returning
//! ordinary UniFFI objects / trait objects via the object registry or
//! callback traits / callback interfaces via the callback registry.
//! Async and fallible callback methods can return callback traits /
//! callback interfaces too, and those return values are rehydrated through
//! the same callback registry path.
//! Also covered: custom types, and string-key `Map` / `HashMap<String, V>`
//! lowering (validated against `Logger` and dedicated custom/map fixtures
//! in `bindgen-tests/javascript/tests/smoke.rs`).
//!
//! Still **not** covered: callback object args, non-string-key maps,
//! nested object/callback values in maps, `Set`, and cancellation.
//! Unsupported exported shapes are emitted as runtime-throwing stubs
//! (with the reason embedded in the thrown `JsError`) rather than being
//! silently skipped.
//!
//! Downstream build prerequisite: any client crate with async UniFFI
//! exports targeting wasm must enable `uniffi`'s
//! `wasm-unstable-single-threaded` feature (see
//! `docs/manual/src/wasm/configuration.md`). This is a *client crate*
//! build requirement, not a generator blocker.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;
use uniffi_bindgen::Component;

use crate::JsConfig;

pub(crate) mod codegen;

pub fn emit(dir: &Utf8Path, component: &Component<JsConfig>) -> Result<()> {
    let ci = &component.ci;
    let ns = ci.namespace();

    let rust_source = codegen::render_wasm_rust(ci);
    fs::write(
        dir.join(format!("{}.rs", ci.crate_name())),
        normalize_generated_text(rust_source),
    )?;

    fs::write(dir.join("backend-wasm.ts"), render_backend(ns))?;
    fs::write(dir.join("index.ts"), render_index(ns))?;
    Ok(())
}

fn normalize_generated_text(mut text: String) -> String {
    while text.ends_with("\n\n") {
        text.pop();
    }
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text
}

fn render_backend(namespace: &str) -> String {
    format!(
        r#"// AUTOGENERATED by uniffi_bindgen_javascript (wasm flavor adapter).
//
// Path A adapter for namespace `{namespace}`: consumes a wasm-bindgen
// JS glue module directly. Raw `.wasm` bytes are intentionally NOT a
// supported public input — only the JS glue that wasm-bindgen produces.
// The glue handles bigint lowering, async Promise wiring and JsError
// marshalling for us; a raw-exports adapter could not.

// Shape of a wasm-bindgen glue module. Every `#[wasm_bindgen] pub fn`
// becomes a named export on this object. `default` is the optional
// async init function present in `--target web` builds.
export interface WasmBindgenGlue {{
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    [key: string]: any;
    default?: ((input?: unknown) => Promise<unknown>) | unknown;
}}

export interface WasmBackend {{
    readonly __uniffiAbiVersion: 2;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    [method: string]: any;
}}

/** Adapt a wasm-bindgen glue module (sync value or Promise) into a
 *  ABI-v2 backend object. For web-target glue pass `init` to
 *  forward it to the module's default export. `--target nodejs` glue
 *  auto-initialises on require, so no init is needed. */
export async function adaptWasmBindgenGlue(
    glue: WasmBindgenGlue | Promise<WasmBindgenGlue>,
    init?: unknown,
): Promise<WasmBackend> {{
    const g = await glue;
    if (typeof g.default === "function") {{
        await (g.default as (i?: unknown) => Promise<unknown>)(init);
    }}
    // If the shim has any callback-trait lowering, it exposes a setter for
    // the JS-side dispatch / release / register thunks. Hook them into the
    // shared callback registry so Rust can call back into JS by handle.
    const {{ lookupCallback, releaseCallback, registerCallback, UniffiError }} = await import(
        "../common/runtime.ts"
    );
    if (typeof g.__uniffi_set_cb_invoker === "function") {{
        const invoke = (handle: number, method: string, args: unknown): unknown => {{
            const cb = lookupCallback(handle) as Record<string, (...a: unknown[]) => unknown> | undefined;
            if (!cb) {{
                throw new UniffiError({{
                    errorName: "UniffiCallbackMissing",
                    message: `no callback registered for handle ${{handle}}`,
                }});
            }}
            const fn = cb[method];
            if (typeof fn !== "function") {{
                throw new UniffiError({{
                    errorName: "UniffiCallbackMissing",
                    message: `callback ${{handle}} does not implement ${{method}}`,
                }});
            }}
            const arr = Array.isArray(args) ? args : [args];
            return fn.apply(cb, arr);
        }};
        const release = (handle: number): void => releaseCallback(handle);
        (g.__uniffi_set_cb_invoker as (i: unknown, r: unknown, reg: unknown) => void)(
            invoke,
            release,
            registerCallback,
        );
    }}
    const callbackErrorPayload = (error: unknown, shape: unknown): unknown => {{
        if (error !== null && typeof error === "object") {{
            const raw = error as Record<string, unknown>;
            if (shape === "flat") {{
                if (typeof raw.variant === "string") return raw.variant;
                if (typeof raw.tag === "string") return raw.tag;
                if (typeof raw.type === "string") return raw.type;
            }}
            if (typeof raw.tag === "string") return raw;
            if (typeof raw.type === "string") {{
                const {{ type, ...data }} = raw;
                return {{ tag: type, ...data }};
            }}
            if (typeof raw.variant === "string") {{
                const data = raw.data;
                const payload: Record<string, unknown> = {{ tag: raw.variant }};
                if (data !== null && typeof data === "object" && !Array.isArray(data)) {{
                    Object.assign(payload, data as Record<string, unknown>);
                }}
                return payload;
            }}
        }}
        throw error;
    }};
    const normalizeCallbackObject = (marker: {{
        object: object;
        fallibleMethods?: Record<string, string>;
        asyncMethods?: Record<string, boolean>;
    }}): object => {{
        const obj = marker.object as Record<string, unknown>;
        const fallibleMethods = marker.fallibleMethods ?? {{}};
        const asyncMethods = marker.asyncMethods ?? {{}};
        const out: Record<string, unknown> = {{}};
        for (const [k, v] of Object.entries(obj)) {{
            if (typeof v !== "function") {{
                out[k] = v;
                continue;
            }}
            out[k] = (...args: unknown[]) => {{
                const fn = v as (...a: unknown[]) => unknown;
                const errorShape = fallibleMethods[k];
                const isAsync = asyncMethods[k] === true;
                if (!errorShape) {{
                    if (isAsync) {{
                        try {{
                            return Promise.resolve(fn.apply(obj, args));
                        }} catch (error) {{
                            return Promise.reject(error);
                        }}
                    }}
                    return fn.apply(obj, args);
                }}
                if (isAsync) {{
                    try {{
                        return Promise.resolve(fn.apply(obj, args)).then(
                            (value) => ({{ ok: true, value }}),
                            (error) => ({{ ok: false, error: callbackErrorPayload(error, errorShape) }}),
                        );
                    }} catch (error) {{
                        return Promise.resolve({{ ok: false, error: callbackErrorPayload(error, errorShape) }});
                    }}
                }}
                try {{
                    return {{ ok: true, value: fn.apply(obj, args) }};
                }} catch (error) {{
                    return {{ ok: false, error: callbackErrorPayload(error, errorShape) }};
                }}
            }};
        }}
        return out;
    }};
    const coerce = (a: unknown): unknown => {{
        if (
            a !== null &&
            typeof a === "object" &&
            (a as {{ __uniffiCallback?: boolean }}).__uniffiCallback === true
        ) {{
            // Tagged marker from common/api.ts — convert JS callback
            // object to a u32 handle the wasm-bindgen shim expects.
            return registerCallback(
                normalizeCallbackObject(a as {{
                    object: object;
                    fallibleMethods?: Record<string, string>;
                    asyncMethods?: Record<string, boolean>;
                }}),
            );
        }}
        return a;
    }};
    return new Proxy({{}} as WasmBackend, {{
        get(_t, name: string) {{
            if (name === "__uniffiAbiVersion") return 2;
            const v = (g as Record<string, unknown>)[name];
            if (typeof v !== "function") return undefined;
            const fn = v as (...args: unknown[]) => unknown;
            return (...args: unknown[]) => fn.apply(g, args.map(coerce));
        }},
    }});
}}
"#
    )
}

fn render_index(namespace: &str) -> String {
    format!(
        r#"// AUTOGENERATED by uniffi_bindgen_javascript (wasm flavor).
//
// Browser entry for namespace `{namespace}`. Wasm is inherently async,
// so unlike the napi entry this one requires an explicit
// `await initBackend(glue)` once before any generated API call.
// `glue` is the wasm-bindgen JS module — see backend-wasm.ts for details.

import {{ __installBackend }} from "../common/runtime.ts";
import {{
    adaptWasmBindgenGlue,
    type WasmBindgenGlue,
}} from "./backend-wasm.ts";
export * from "../common/api.ts";
export type {{ WasmBindgenGlue }} from "./backend-wasm.ts";

let initialized = false;

/** Install the wasm-bindgen backend. Idempotent: later calls are
 *  ignored so hot-reload loops don't double-install. */
export async function initBackend(
    glue: WasmBindgenGlue | Promise<WasmBindgenGlue>,
    init?: unknown,
): Promise<void> {{
    if (initialized) return;
    const backend = await adaptWasmBindgenGlue(glue, init);
    __installBackend(backend);
    initialized = true;
}}
"#
    )
}
